kotlin-redux/src/main/kotlin/redux/Helpers.kt

This pull request fixes #84 by flipping key, value pairs for the combineReducers helper.

kotlin-redux: Fix combineReducers by switching key, value pairs

---

kotlin-react-redux/src/main/kotlin/react/redux/Helpers.kt
kotlin-react-redux/src/main/kotlin/react/redux/Imports.kt

Changes the return type of connect, connectAdvanced, and rConnect from `(RClass<P>) -> RClass<OP>` to `HOC<P, OP>`. Not a breaking change 👍

Return HOC from connect, connectAdvanced, and rConnect

---

examples/build.gradle
kotlin-react-redux/src/main/kotlin/react/redux/Helpers.kt
kotlin-react-redux/src/main/kotlin/react/redux/Types.kt

connect supports using no parameters to pass dispatch as props to connected component. This adds support for this behavior using rConnect.

rConnect no parameters

---

kotlin-react-redux/README.md
kotlin-react/src/main/kotlin/react/HOC.kt
kotlin-react/src/main/kotlin/react/React.kt

- Added an `rClass` extension property to `KClass<RComponent<*,*>>`. This will help to reduce to boilerplate to call `rConnect` (and any other `HOC`)
- Added an `allOf` function to `HOC.kt` that will take a list of wrapper functions, chain them to the given component, and return the resulting `RClass`.
```kotlin
private val wrappedMyComponent = 
allOf<MyComponentProps>(withTheme(), withSnackbar())(MyComponent::class.rClass)
fun RBuilder.myComponent(...) = wrappedMyComponent { // this: RElementBuilder<MyComponentProps>
// render something here
}
```
Imports for `withTheme`:
```kotlin
@JsModule("@material-ui/core/styles")
external val materialUiCoreStyles: dynamic
fun <P : WithTheme> withTheme() = materialUiCoreStyles.withTheme().unsafeCast<HOC<P, P>>()
external interface WithTheme : RProps …
```

HOC enhancement

---

kotlin-css/src/main/kotlin/kotlinx/css/StyledElement.kt

If you take a look on the compiled code you would notice that `StyledElement` has a huge constructor:
```
function StyledElement() {
this.declarations = LinkedHashMap_init();
this.alignContent_7m0jmp$_0 = this.declarations;
this.alignItems_9mpmew$_0 = this.declarations;
this.alignSelf_dai5xs$_0 = this.declarations;
this.animation_9ca8n1$_0 = new StyledElement$WithDefault(this, StyledElement$animation$lambda);
this.background_dt9zfp$_0 = this.declarations;
this.backgroundAttachment_lerym6$_0 = this.declarations;
this.backgroundClip_v98mrv$_0 = this.declarations;
this.backgroundColor_piuh1o$_0 = this.declarations;
this.backgroundImage_sbtf4k$_0 = this.declarations;
this.backgroundOrigin_pp8gf5$_0 = this.declarations;
this.backgroundPosition_jdky2s$_0 = this.declarations; …
```

Significantly reduce StyledElement object memory consumption

---

kotlin-css/src/main/kotlin/kotlinx/css/CSSBuilder.kt
kotlin-styled/src/main/kotlin/styled/StyleSheet.kt

For example, the following code
```
styledDiv {
css {
specific {
+SomeStaticStyleSheet.someClass
}
}
}
```
produces something like `<div class="SomeStaticStyleSheet-someClass hFRAPv"></div>` from now on
instead of just `<div class="hFRAPv"></div>`.
It allows overriding some properties of the static class from the outside
```
object OverridingStyleSheet : StyleSheet("OverridingStyleSheet", isStatic = true) {
val greenText by css {
descendants(SomeStaticStyleSheet.getClassSelector { it::someClass }) {
color = Color.green
}
}
}
```
and not being afraid that `SomeStaticStyleSheet-someClass` won't be applied to the element because of nesting.

Assign static class names to an element even if they are applied under `specific`

---

kotlin-react/src/main/kotlin/react/Imports.kt
kotlin-react/src/main/kotlin/react/RBuilder.kt
kotlin-react/src/main/kotlin/react/hooks.kt

Wrappers for react hooks and way to create functional component like this
```kotlin
val renderCount = functionalComponent<RProps> {
val (count, setCount) = useState(0)
useEffect {
console.log("useEffect $count")
}
+"count $count"
button {
attrs {
onClickFunction = {
setCount(count + 1)
}
}
}
}
fun RBuilder.renderCount() {
child(renderCount)
}
```

React Hooks v16.8

---

kotlin-react/src/main/kotlin/react/React.kt
kotlin-react/src/main/kotlin/react/ReactComponent.kt

Static fields of react component classes can be used:
```kotlin
companion object : ReactStatics<RProps, RState, RComponent, Nothing> {
init {
defaultProps = ...
...
}
}
```

Wrapper for static fields of React component class

---

kotlin-react/src/main/kotlin/react/Imports.kt

The TypeScript definition of the `useCallback` hook is
```typescript
function useCallback<T extends (...args: any[]) => any>(callback: T, deps: DependencyList): T;
```
I have modified the Kotlin wrapper definition to match it.

Fix useCallback hook type definition

---

kotlin-css/kotlin-css-js/package.json
kotlin-css/kotlin-css-jvm/package.json
kotlin-css/package.json
kotlin-extensions/package.json
kotlin-mocha/package.json
kotlin-react-dom/package.json
kotlin-react-redux/package.json
kotlin-react-router-dom/package.json
kotlin-react/package.json
kotlin-redux/package.json
kotlin-styled/package.json

https://spdx.org/licenses/Apache-2.0.html
Using standard identifiers helps downstream folks correctly identify the license your project (and npm packages) are under.

Fix Apache-2.0 SPDX identifier

---

kotlin-react/src/main/kotlin/react/hooks.kt

For using state hook with
```
var count by state(0)
count = count + 1
```
instead of 
```
val (count, setCount) = useState(0)
setCount(count + 1)
```

Add state delegate for useState hook

---

build.gradle
buildSrc/build.gradle.kts
buildSrc/gradle.properties
buildSrc/src/main/kotlin/ArchivesConfigurationAccessors.kt
buildSrc/src/main/kotlin/Kotlin.kt
buildSrc/src/main/kotlin/Versions.kt
buildSrc/src/main/kotlin/publishing-conventions.gradle.kts
gradle.properties
kotlin-css/build.gradle

Part of #161
* Update bintray plugin. `1.8.4` -> `1.8.5`
Additional info:
* [Bintray plugin Kotlin DSL support](https://github.com/bintray/gradle-bintray-plugin/issues/258)

Kotlin DSL. Standard publishing convensions

---

README.md
examples/build.gradle
examples/src/main/kotlin/example/ReactRouterDom.kt
kotlin-react-router-dom/package.json
kotlin-react-router-dom/src/main/kotlin/react/router/dom/hooks.kt
kotlin-react-router-dom/src/main/kotlin/react/router/dom/imports.kt

fix #146 
Add hooks API for react-router-dom and some wrapper methods
- [`useHistory`](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/hooks.md#usehistory)
- [`useLocation`](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/hooks.md#uselocation)
- [`useParams`](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/hooks.md#useParams)
- [`useRouteMatch`](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/hooks.md#useRouteMatch)
And add sample code of react-router-dom.
- https://github.com/subroh0508/kotlin-wrappers/blob/react-router-dom-hooks-api/examples/src/main/kotlin/example/ReactRouterDom.kt
【Official …

Add hooks API for react-router-dom

---

kotlin-react-router-dom/src/main/kotlin/react/router/dom/helpers.kt
kotlin-react-router-dom/src/main/kotlin/react/router/dom/imports.kt

fix #128 
Add wrapper method of withRouter.
```
class TestComponent : RComponent<RProps, RState>() { ... }
val Component: RClass<RProps> = withRouter(TestComponent::class)
```
or
```
val TestComponent = functionalComponent<RProps> { ... }
val Component: RClass<RProps> = withRouter(TestComponent)
```
【Official Document】https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/withRouter.md
ref. #172

Add withRouter

---

build.gradle.kts
kotlin-css/build.gradle.kts
kotlin-css/src/main/kotlin/kotlinx/css/StyleEnums.kt
kotlin-styled/build.gradle.kts

`formatAlpha` - unify double formatting between JS & JVM

Make JS tests running again

---

kotlin-css/src/main/kotlin/kotlinx/css/Extensions.kt

[Playground](https://pl.kotl.in/vFU93tvmr)

Simplify 'hyphenize'

---

kotlin-extensions/src/main/kotlin/kotlinext/js/Object.kt
kotlin-react/src/main/kotlin/react/RBuilder.kt

`childList.first()` couldn't return `null`

Strict contract for `buildElement`

---

kotlin-react-router-dom/src/main/kotlin/react/router/dom/routing.kt
kotlin-react-router-dom/src/main/kotlin/react/router/dom/routingDsl.kt

react-router-dom RedirectComponent can also be used to render an
unconditional redirect. Make the from restriction optional.

redirect-router-dom: Make redirect.from optional

---

kotlin-react/src/main/kotlin/react/React.kt
kotlin-react/src/main/kotlin/react/ReactComponent.kt

There has been a KComponent.rClass property getter in React.kt for a while.
Recently a Component.rClass has been added (that thus also works for PureComponent), however it is not publicly available.
I don't see a reason why these should not be merged.
This change widenes the receiver parameters of the public rClass property, and removes the internal one.

Merge duplicate Component.rClass properties

---

kotlin-react-router-dom/src/main/kotlin/react/router/dom/hooks.kt

Fix #216 
The bug was caused by executing a function with an option value when the argument `path` was empty🥺
The following is a Javascript implementation of useRouteMatch.
https://github.com/ReactTraining/react-router/blob/c0b8ce42d3c6b85e3a53d1c56ae12c88205d00d8/packages/react-router/modules/hooks.js#L43-L55

Fix rawUseRouteMatch when path is empty

---

kotlin-react-router-dom/src/main/kotlin/react/router/dom/routing.kt

fix #226 
Related Javascript code is here.
https://github.com/ReactTraining/react-router/blob/c0b8ce42d3c6b85e3a53d1c56ae12c88205d00d8/packages/react-router-dom/modules/NavLink.js#L68

Fix arguments of NavLinkProps#isActive lambda

---

kotlin-extensions/src/main/kotlin/kotlinext/js/CommonJS.kt

Function `require` already declared in line `20`

Remove duplicated 'require'

---

kotlin-react/src/main/kotlin/react/RBuilder.kt
kotlin-react/src/main/kotlin/react/ReactComponent.kt

relates #130 
Several functions have been added to support the Function as Child Component Pattern.
For example, by JSX
```jsx
const ParentComponent = (props) => {
return (
<div>
{ props.parentText }
{ props.children("Child") }
</div>
)
}
const ChildComponent = (props) => {
return (
<div>
{ props.childText }
</div>
)
}
const App = () => (
<ParentComponent parentText="Parent">
{ (text) => (<ChildComponent childText={ text }>) }
</ParentComponent>
)
/* [Result]
* <div>
*   Parent
*   <div>Child</div>
*  </div>
*/
```
On this Pull Request, for example
```kotlin
external interface ParentProps : RProps {
var parentText: String
}
external interface ChildProps : RProps {
var childText: String
}
// Functional Component
val FunctionalParentComponent = functionalComponent<ParentProps> { props -> …
```

Add support method for Function as Child Component Pattern

---

kotlin-react/src/main/kotlin/react/hooks.kt

Additionally, deprecate state delegate
It leads to consistent usage of react hooks and it respect hooks naming with `use*`

Add extensions to use useState as delegate

---

build.gradle.kts
examples/build.gradle.kts
kotlin-react-dom/build.gradle.kts
kotlin-styled/build.gradle.kts

Before:
* Dependency for all (9) subprojects
After:
* Dependency for `kotlin-react-dom` & `kotlin-styled`

Fix 'kotlinx-html' dependency usage

---

kotlin-react/README.md

Add installation instructions for Gradle-based projects
Add description of React entry point
Use functionalComponents instead of RBuilders in example code
Add usage instructions for function and class components using child function and two type of extensions
Add section on RBuilders for structuring complex components
Add section on React Hooks

Update README for kotlin-react

---

kotlin-css/src/commonMain/kotlin/kotlinx/css/CSSBuilder.kt
kotlin-css/src/commonMain/kotlin/kotlinx/css/properties/Keyframes.kt
kotlin-css/src/commonTest/kotlin/kotlinx/css/TestFontFace.kt
kotlin-styled/src/main/kotlin/styled/StyledComponents.kt

I suggest this fix for https://github.com/JetBrains/kotlin-wrappers/issues/292
Next to `rules: MutableList<Rule>` It introduces another List `multiRules: MutableList<Rule>` that is simply rendered after all the regular rules by `StringBuilder.buildRules`.
This solution does not ensure that all rules are rendered in the same order as they were specified.
I think this should in general not be a problem, except in a scenario like this:
1. the user specifies some rule `r1: Rule` as `multiRules` with a selector `s`
1. the user specifies a rule `r2: Rule` with the same selector `s` in `rules` after these
In regular css, `r1` would possibly be overwritten by `r2`, but here `r1` will instead appear later in the printed css code, and overwrite `r2`.
However, this scenario seems like a clear abuse …

fix css fontFace - issue #292

---

kotlin-react/README.md

Adds a section on using delegation syntax for React Hooks.
Also bumps gradle snippet version number to 105.

Add section on hooks via delegation syntax to react wrappers README

---

kotlin-react/src/main/kotlin/react/hooks.kt

```Kotlin
import react.getValue // redundant
import react.setValue // redundant
import react.useState
val (n, setN) = useState("n") // works
var k by useState("k") // works
```

useState. Avoid additional imports (getValue, setValue)

---

kotlin-react-router-dom/src/main/kotlin/react/router/dom/alias.kt
kotlin-react-router-dom/src/main/kotlin/react/router/dom/routing.kt
kotlin-react-router-dom/src/main/kotlin/react/router/dom/routingDsl.kt

Enabled setting the attribute values of BrowserRouter and HashRouter.
ref. https://reacttraining.com/react-router/web/api/BrowserRouter
ref. https://reacttraining.com/react-router/web/api/HashRouter

Support setter of BrowserRouter / HashRouter attributes

---

kotlin-react-redux/README.md

https://react-redux.js.org/api/connect#ownprops
In mapState ToProps and mapDispatchToProps we should use props of connectedComponent as second argument.

Fix ownProps in rConnect Type Parameters

---

kotlin-css/src/commonMain/kotlin/kotlinx/css/StyleEnums.kt
kotlin-css/src/commonTest/kotlin/kotlinx/css/TestColor.kt

I added a `hex` color function like `rgb` and `hsl` for Kotlin styled.
As parameter it takes an integer.
It is meant to be used like `hex(0xdeadbe)`.
I think it's a useful function as I use a lot of hex codes and using a function is more idiomatic than `Color("#deadbe")`.

Add hex function for Color with unit test

---

kotlin-react/src/main/kotlin/react/ReactComponent.kt

By inlining `rFunction`, React Developer Tools Chrome extension shows any hooks deeply nested within some structure. Not inlining removes these extra layers of structure, which make debugging component hooks much easier.
Here's what it looks like before:
Here's what it looks like after:
This is how `functionalComponent` works (doesn't inline) but that builder doesn't support naming the component which gives a tree of `Anonymous` components which is worse. The other option would be to add `displayName` support to `functionalComponent` if that is the direction this library is moving and the goal is to remove `rFunction`.

Do not inline react.rFunction builder

---

build.gradle.kts
kotlin-css/build.gradle.kts

This 3 explicit targets are required for now so that kotlin-css can be consumed by Kotlin/Native ios targets. Can be extended later for all native targets, if needed.

Add ios target and workaround native plugin late evaluation

---

kotlin-css/src/commonMain/kotlin/kotlinx/css/CSSBuilder.kt
kotlin-react/src/main/kotlin/react/RBuilder.kt
kotlin-styled/build.gradle.kts
kotlin-styled/src/main/kotlin/styled/StyleSheet.kt
kotlin-styled/src/main/kotlin/styled/StyledComponents.kt
kotlin-styled/src/main/kotlin/styled/styled-components.kt

There were two problems:
1) Animation keyframes internal rules generation changed
2) `createGlobalStyle` has internal check of using in render by hook `useRef` and it was called conditionally against hooks rules.
And just added ability to name functionalComponent

Update to styled components v5

---

kotlin-styled/src/main/kotlin/styled/StyleSheet.kt

Now save `holders` and `_properties` in memory
Open question: 
- There are no removes for this mutable collections `holders` and `_properties`, do you think if removals are required, and does redundancy of removals operations lead to memory leaks?

Remove reflection hardcode from kotlin-styled for compatibility with both compiler backends

---

kotlin-styled/src/main/kotlin/styled/InlineStyles.kt

The JS_IR compiler tends to rename locals more often
compared to the old one. This change makes the code
work even if `value` gets renamed to `value_N`.

Fix inline styles to work with JS_IR

---

gradle.properties
kotlin-react-redux/src/main/kotlin/react/redux/Dsl.kt
kotlin-react-redux/src/main/kotlin/react/redux/Imports.kt

Hi there! I ported the following (new) API:
- added `context` prop to [`Provider`](https://react-redux.js.org/api/provider#provider)
- [`batch()`](https://react-redux.js.org/api/batch)
- [`useSelector()`](https://react-redux.js.org/api/hooks#useselector)
- [`useStore()`](https://react-redux.js.org/api/hooks#usestore)
- [`useDispatch()`](https://react-redux.js.org/api/hooks#usedispatch)
- [`createSelectorHook`](https://react-redux.js.org/api/hooks#custom-context)
- [`createStoreHook`](https://react-redux.js.org/api/hooks#custom-context)
- [`createDispatchHook`](https://react-redux.js.org/api/hooks#custom-context)
Comments are welcome.
(closes #357)

Porting react-redux 7.2

---

README.md

If you want to use the new IR in Kotlin/JS, you currently must use these fixes for production mode.
In `developmentRun` these errors don`t show up, which is very hard to fix.
Adding this fixes to the README helps people to prevent unnecessary time trying to fix them.

Add current issues and workarounds based on IR

---

kotlin-redux/src/main/kotlin/redux/Helpers.kt

In fact `WrapperAction` and `RAction` are externals
In https://github.com/JetBrains/kotlin-wrappers/blob/1550ab7e35e6d16afa3f76ebf67c911357486ce7/kotlin-redux/src/main/kotlin/redux/Helpers.kt#L34 we get `action` with dynamic, so we need to get it by name.
Non externals don't get such guarantees (and in IR it doesn't, access will be by property accessors - getter and setter), but externals do (by semantic)

Externalize redux actions

---

kotlin-react/src/main/kotlin/react/Imports.kt

As explained in the React documentation (https://reactjs.org/docs/react-api.html#reactmemo) we should be able to provide a custom comparison function to React.memo for some performance optimizations. Therefore, I added the external declaration to provide this feature.

Adding control over comparison for memo

---

kotlin-react-dom/src/main/kotlin/react/dom/RDOMBuilder.kt

Fixes IR problem where unsafe throws 
```
`props.dangerouslySetInnerHTML` must be in the form `{__html: ...}`
```
https://youtrack.jetbrains.com/issue/KT-45021

Make InnerHTML external interface

---

kotlin-css/src/commonMain/kotlin/kotlinx/css/StyleEnums.kt
kotlin-css/src/commonTest/kotlin/kotlinx/css/TestColor.kt

Adds `changeAlpha` function.
Unlike `withAlpha`, that **multiplies** color's current alpha value on the given number, `changeAlpha` completely replaces color's alpha with a given one.

Add changeAlpha function

---

README.md
build.gradle.kts

Already available in Maven Central

Remove redundand `kotlinx-html` maven repo

---

kotlin-react/src/main/kotlin/react/Imports.kt
kotlin-react/src/main/kotlin/react/ReactComponent.kt

1. Non-strict contract for `current`. `current` must be nullable
2. Non-strict type parameter for reference types (result of problem 1)
[Test project](https://codesandbox.io/s/blissful-beaver-wy7fo)
After second button click one ref is `null` (see console)
* `RReadableRef<MyElement?>` -> `RReadableRef<MyElement>`
* `RMutableRef<MyElement?>` -> `RMutableRef<MyElement>`
* `useRef<MyElement?>` -> `useRef<MyElement>`
* `createRef<MyElement?>` -> `createRef<MyElement>`
cc @vlsi

Fix ref object contract

---

kotlin-react/README.md

Updating the sample for the React Custom Component to better reflect the approach to creating an Initial State for a component from the props that are injected. 
Covers:
- IR Compatibility
- State instantiation 
- @JsExport for class components. 
- Override State `init` function.
This has come about after a conversation with @SebastianAigner regarding state initialisation in `Kotlin-React` components that are built with the new IR compiler.

Update README.md sample for React Component

---

buildSrc/src/main/kotlin/maven-publishing-conventions.gradle.kts

Subtask of #431
Licences section
https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-stdlib/1.5.0

Sync `licences` section with `kotlin` project

---

kotlin-react/src/main/kotlin/react/ReactComponent.kt

[functionalComponent](https://github.com/JetBrains/kotlin-wrappers/blob/0516221ff85f064f38b87d395ec7da0b0afb961b/kotlin-react/src/main/kotlin/react/RBuilder.kt#L253)

#358 Remove `rFunction` (duplicate of `functionalComponent`)

---

kotlin-react/src/main/kotlin/react/Imports.kt

`props` instantiated inside React, the problem that `open val` allow to override with `override var`, and setter will be overridden.
But when during native react constructor, react set props, it calls overridden setter, which is not good, I guess

Remove possibilty to override props

---

kotlin-react/src/main/kotlin/react/REffectBuilder.kt

Add `REffectBuilder`

---

kotlin-react/src/main/kotlin/react/useRefValue.kt

```Kotlin
var count by useRefValue(0)
// debug mode
useEffect {
count++
println(count)
}
```

Add `useRefValue` hook

---

kotlin-react/src/main/kotlin/react/Imports.kt
kotlin-react/src/main/kotlin/react/StateInstance.kt

`StateInstance` - like [`TableInstance`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0db3b0f8fc437d00900166cffa8a884142f1247d/types/react-table/index.d.ts#L163)
`StateSetter` - like [`PropGetter`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0db3b0f8fc437d00900166cffa8a884142f1247d/types/react-table/index.d.ts#L181)
Smooth migration provided by IDEA via formatting

Standard names for `state` classes

---

kotlin-react/src/main/kotlin/react/EffectBuilder.kt
kotlin-react/src/main/kotlin/react/useEffect.kt
kotlin-react/src/main/kotlin/react/useLayoutEffect.kt

Fix #463
New implementation of hooks with vararg dependencies is added, old implementation is deprecated.
Cc @turansky

Consistency of hook dependencies v2

---

kotlin-react-table/src/main/kotlin/react/table/Table.kt

[Definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/51e77dacacf9d22ede03f0c7beeb244dc5346f1a/types/react-table/index.d.ts#L227)

Fix `UseTableHooks` property names

---

kotlin-css/src/commonMain/kotlin/kotlinx/css/StyleEnums.kt
kotlin-css/src/commonTest/kotlin/kotlinx/css/TestGrid.kt

https://developer.mozilla.org/en-US/docs/Web/CSS/grid-auto-rows#syntax
https://developer.mozilla.org/en-US/docs/Web/CSS/grid-auto-columns#syntax

Fix typo in GridAutoRows and GridAutoColumns

---

kotlin-react/src/main/kotlin/react/Imports.kt
kotlin-react/src/main/kotlin/react/useCallback.kt
kotlin-react/src/main/kotlin/react/useMemo.kt

`useMemo` and `useCallback` hooks with array dependencies are deprecated, only hooks with vararg dependencies are recommended for usage.
cc @turansky

Old memoization hooks are deprecated

---

kotlin-react-dom/src/main/kotlin/react/dom/RDOMBuilder.kt
kotlin-react-dom/src/main/kotlin/react/dom/ReactDOMAttributes.kt

`kotlinx.html` has `attributes` map `String` -> `String`
So, it is't allowed to pit dynamic here.
In legacy backend, there is no check in this place (but it is incorrect action in Kotlin type system)
But in IR there is type check, and it breaks on runtime

jsStyle not written into string attributes

---

kotlin-react-router-dom/src/main/kotlin/react/router/dom/helpers.kt
kotlin-react-table/src/main/kotlin/react/table/GroupBy.kt
kotlin-react-table/src/main/kotlin/react/table/Table.kt
kotlin-react/src/main/kotlin/react/ComponentType.kt
kotlin-react/src/main/kotlin/react/Imports.kt
kotlin-react/src/main/kotlin/react/RBuilder.kt
kotlin-react/src/main/kotlin/react/React.kt
kotlin-react/src/main/kotlin/react/ReactComponent.kt

1) `ComponentType` interface is introduced
1) Asterisk is used for Context generic parameter bound
1) `FunctionalComponent` is deprecated (POTENTIALLY BREAKING CHANGE!!!)

`ComponentType` interface is introduced

---

kotlin-react/src/main/kotlin/react/Imports.kt
kotlin-react/src/main/kotlin/react/RBuilder.kt
kotlin-styled/src/main/kotlin/styled/StyledComponents.kt
kotlin-styled/src/main/kotlin/styled/styled-components.kt

`RBuilder` base child methods and `createElement` signature are strict.
These changes relates to #358

RBuilder base child methods is strict

---

kotlin-styled/src/main/kotlin/styled/StyledComponents.kt

Add interface for CSSBuilder injecting directly in styled components. It is needed because CSSBuilder contains already parsed rules, with which we can work directly in CSSOM later

Add interface for CSSBuilder injecting directly in styled components.

---

gradle.properties
kotlin-styled-next/README.md
kotlin-styled-next/build.gradle.kts
kotlin-styled-next/gradle.properties
kotlin-styled-next/src/main/kotlin/styled/CSSBuilder.kt
kotlin-styled-next/src/main/kotlin/styled/GlobalStyles.kt
kotlin-styled-next/src/main/kotlin/styled/InlineStylePrefixer.kt
kotlin-styled-next/src/main/kotlin/styled/InlineStyles.kt
kotlin-styled-next/src/main/kotlin/styled/StyleSheet.kt
kotlin-styled-next/src/main/kotlin/styled/StyledComponents.kt
kotlin-styled-next/src/main/kotlin/styled/StyledCss.kt
kotlin-styled-next/src/main/kotlin/styled/StyledTags.kt
settings.gradle.kts

This PR add styled-components implementation in kotlin. I've tried to save most of the interfaces and the main flow.
One of the main differences from styled-components is missing prefixer in this implementation

Implement styled-components in kotlin

---

examples/src/main/kotlin/example/Quill.kt
kotlin-react-query/src/main/kotlin/react/query/QueryClientProvider.kt
kotlin-react-query/src/main/kotlin/react/query/QueryErrorResetBoundary.kt
kotlin-react-redux/README.md
kotlin-react-redux/src/main/kotlin/react/redux/Types.kt
kotlin-react-router-dom/src/main/kotlin/react/router/dom/helpers.kt
kotlin-react-router-dom/src/main/kotlin/react/router/dom/imports.kt
kotlin-react-router-dom/src/main/kotlin/react/router/dom/routing.kt
kotlin-react/src/main/kotlin/react/Context.kt
kotlin-react/src/main/kotlin/react/Fragment.kt
kotlin-react/src/main/kotlin/react/HOC.kt
kotlin-react/src/main/kotlin/react/Profiler.kt
kotlin-react/src/main/kotlin/react/RBuilder.kt
kotlin-react/src/main/kotlin/react/StrictMode.kt
kotlin-react/src/main/kotlin/react/Suspense.kt
kotlin-styled-next/src/main/kotlin/styled/StyledComponents.kt
kotlin-styled/src/main/kotlin/styled/StyledComponents.kt
kotlin-styled/src/main/kotlin/styled/styled-components.kt

Use `ComponentClass` instead of `RClass`

---

examples/src/main/kotlin/example/AxiosSearch.kt
examples/src/main/kotlin/example/Product.kt
examples/src/main/kotlin/example/Quill.kt
examples/src/main/kotlin/example/TicTacToe.kt
examples/src/main/kotlin/example/Todo.kt
kotlin-react-redux/src/main/kotlin/react/redux/Imports.kt
kotlin-react-router-dom/src/main/kotlin/react/router/dom/routing.kt
kotlin-react/src/main/kotlin/react/Component.ext.kt
kotlin-react/src/main/kotlin/react/Component.kt
kotlin-react/src/main/kotlin/react/ComponentClass.kt
kotlin-react/src/main/kotlin/react/PureComponent.kt
kotlin-react/src/main/kotlin/react/RComponent.kt
kotlin-react/src/main/kotlin/react/RPureComponent.kt
kotlin-react/src/main/kotlin/react/State.kt

`RState` -> `State`

---

kotlin-react-router-dom/src/main/kotlin/react/router/dom/helpers.kt
kotlin-react-router-dom/src/main/kotlin/react/router/dom/routingDsl.kt
kotlin-react/src/main/kotlin/react/ComponentClass.kt
kotlin-react/src/main/kotlin/react/RBuilder.kt

Deprecate `RClass`

---

kotlin-react/src/main/kotlin/react/RBuilder.kt
kotlin-react/src/main/kotlin/react/RComponent.kt
kotlin-react/src/main/kotlin/react/RPureComponent.kt

Part of #358
cc @turansky @aerialist7 
`childFunction` and `RProps.children(value: T)` signatures are removed because of unsafety.
These methods can lead to inconsistency and mistakes in codebase of `kotlin-wrappers` users.
Recommended solution for such cases:
```
interface RenderChildrenProps : RProps {
var children: RBuilder.(value: Int) -> Unit
}
val RenderChildren = fc<RenderChildrenProps> { props ->
div {
props.children(this, 42)
}
}
val Container = fc<RProps> {
RenderChildren {
attrs {
children = { value ->
span {
attrs {
jsStyle {
color = "red"
}
}
+"$value"
}
}
}
}
}
```

Remove unsafe `childFunction`

---

kotlin-css/src/commonMain/kotlin/kotlinx/css/CssBuilder.kt
kotlin-styled-next/src/jsMain/kotlin/styled/StyledCss.kt
kotlin-styled-next/src/jsTest/kotlin/TestUtils.kt
kotlin-styled-next/src/jsTest/kotlin/test/AtRulesTest.kt
kotlin-styled-next/src/jsTest/kotlin/test/ElementTest.kt
kotlin-styled-next/src/jsTest/kotlin/test/PseudoClassRulesTest.kt
kotlin-styled-next/src/jsTest/kotlin/test/PseudoElementsTest.kt
kotlin-styled-next/src/jsTest/kotlin/test/RelativeSelectorsTest.kt
kotlin-styled-next/src/jsTest/kotlin/test/StyleSheetTest.kt
kotlin-styled-next/src/jsTest/kotlin/test/TestBase.kt
kotlin-styled-next/src/jsTest/kotlin/test/styleSheets/SimpleStyleSheet.kt
kotlin-styled-next/src/jsTest/kotlin/test/styleSheets/StaticStyleSheet.kt

More tests for CSSBuilder function integration with `kotlin-styled-next`

Public interface tests 

---

kotlin-react-query/src/main/kotlin/react/query/QueryErrorResetBoundary.kt
kotlin-react/src/main/kotlin/react/Component.kt
kotlin-react/src/main/kotlin/react/ComponentClass.kt
kotlin-react/src/main/kotlin/react/ComponentType.kt
kotlin-react/src/main/kotlin/react/Context.kt
kotlin-react/src/main/kotlin/react/Fragment.kt
kotlin-react/src/main/kotlin/react/FunctionComponent.kt
kotlin-react/src/main/kotlin/react/FunctionalComponent.legacy.kt
kotlin-react/src/main/kotlin/react/HOC.kt
kotlin-react/src/main/kotlin/react/IntrinsicType.kt
kotlin-react/src/main/kotlin/react/Profiler.kt
kotlin-react/src/main/kotlin/react/Props.kt
kotlin-react/src/main/kotlin/react/PureComponent.kt
kotlin-react/src/main/kotlin/react/RBuilder.kt
kotlin-react/src/main/kotlin/react/RComponent.kt
kotlin-react/src/main/kotlin/react/RPureComponent.kt
kotlin-react/src/main/kotlin/react/Raw.kt
kotlin-react/src/main/kotlin/react/React.kt
kotlin-react/src/main/kotlin/react/ReactElement.kt
kotlin-react/src/main/kotlin/react/StrictMode.kt
kotlin-react/src/main/kotlin/react/Suspense.kt
kotlin-react/src/main/kotlin/react/forwardRef.kt
kotlin-react/src/main/kotlin/react/lazy.kt
kotlin-react/src/main/kotlin/react/memo.kt
kotlin-ring-ui/src/main/kotlin/ringui/Checkbox.kt

There are typing vulnerability of currents props: every component now can have children with type `Array<ReactNode>`, even it is not declared obviously. Also there is conflict of names and now there are difficulties with creation of children with custom type (e.g. render children)
This PR - first step to make `Props` more strict.
[TS typings](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L824)
Part of #358
cc @turansky @aerialist7

Prepare Component Props for more strict restrictions

---

kotlin-react/src/main/kotlin/react/ElementType.kt

Strict bounds for `ElementType` type parameter

---

build.gradle.kts
buildSrc/src/main/kotlin/kotlin-conventions.gradle.kts
examples/build.gradle.kts
kotlin-extensions/build.gradle.kts
kotlin-react-dom/build.gradle.kts
kotlin-react-query/build.gradle.kts
kotlin-react-redux/build.gradle.kts
kotlin-react-router-dom/build.gradle.kts
kotlin-react-table/build.gradle.kts
kotlin-react/build.gradle.kts
kotlin-redux/build.gradle.kts
kotlin-ring-ui/build.gradle.kts
kotlin-styled-next/build.gradle.kts
kotlin-styled/build.gradle.kts

Add `kotlin-conventions` plugin

---

kotlin-react/src/main/kotlin/react/RBuilder.kt
kotlin-styled/src/main/kotlin/styled/StyledComponents.kt

Strange and controversial child API is refactored and reduced.
cc @turansky

Reduce ambiguous child API

---

kotlin-react/src/main/kotlin/react/RBuilder.kt
kotlin-styled/src/main/kotlin/styled/StyledComponents.kt

Fix unexpected ambiguity, child signature with props and handler is returned
cc @turansky 
See also: https://youtrack.jetbrains.com/issue/KT-48228

Fix unexpected ambiguity

---

kotlin-ring-ui/src/main/kotlin/ringui/Grid.kt
kotlin-ring-ui/src/main/kotlin/ringui/UserCard.kt

`RProps` is removed from Ring UI

---

kotlin-react-redux/src/main/kotlin/react/redux/Helpers.kt
kotlin-react-redux/src/main/kotlin/react/redux/Imports.kt
kotlin-react-redux/src/main/kotlin/react/redux/Types.kt

`RProps` is removed from react-redux

---

kotlin-react-dom/src/main/kotlin/react/dom/RDOMBuilder.kt
kotlin-styled-next/src/main/kotlin/styled/StyledComponents.kt
kotlin-styled/src/main/kotlin/styled/StyledComponents.kt
kotlin-styled/src/main/kotlin/styled/styled-components.kt

**WARNING:** small breaking change
`CustomStyledProps` does not includes children anymore. This change has been made according to _Interface Segregation Principle_
Before: 
```kotlin
external interface MyButtonProps : CustomStyledProps
```
After:
```kotlin
external interface MyButtonProps : CustomStyledProps, PropsWithChildren
```
**ATTENTION:** add `PropsWithChildren` only if you really need it, only if you somehow use `children` in you component with `CustomStyledProps`
cc @turansky @aerialist7 @tretikoff

`RProps` is removed from dom and styled

---

examples/src/main/kotlin/example/ReactRouterDom.kt
kotlin-react-router-dom/src/main/kotlin/react/router/dom/helpers.kt
kotlin-react-router-dom/src/main/kotlin/react/router/dom/hooks.kt
kotlin-react-router-dom/src/main/kotlin/react/router/dom/imports.kt
kotlin-react-router-dom/src/main/kotlin/react/router/dom/routing.kt
kotlin-react-router-dom/src/main/kotlin/react/router/dom/routingDsl.kt
kotlin-react/src/main/kotlin/react/Props.kt

`RProps` is removed from react-router-dom

---

kotlin-react-virtual/src/main/kotlin/react/virtual/VirtualItem.kt

Strict type for `VirtualItem.measureRef`

---

kotlin-ring-ui/src/main/kotlin/ringui/Footer.kt
kotlin-ring-ui/src/main/kotlin/ringui/FooterItem.kt

``` FooterItem ``` and ``` FooterDataItem ``` are called so because in Ring UI they are referred to as "item":
```js
function renderItem(item) {
if (isValidElement(item)) {
return item;
}
// ...
```
```js
const element = (item.copyright ? copyright(item.copyright) : '') + (item.label || item);
```
```js
FooterLine.propTypes = {
item: PropTypes.oneOfType([
PropTypes.object,
PropTypes.array,
PropTypes.string
])
};
```

[ring-ui] Add Footer component

---

kotlin-css/src/commonMain/kotlin/kotlinx/css/StyleList.kt
kotlin-styled-next/src/main/kotlin/styled/CssBuilder.kt
kotlin-styled-next/src/main/kotlin/styled/GlobalStyles.kt
kotlin-styled-next/src/main/kotlin/styled/InlineStylePrefixer.kt
kotlin-styled-next/src/main/kotlin/styled/InlineStyles.kt
kotlin-styled-next/src/main/kotlin/styled/StyledComponents.kt
kotlin-styled-next/src/main/kotlin/styled/StyledCss.kt
kotlin-styled-next/src/test/kotlin/TestUtils.kt
kotlin-styled-next/src/test/kotlin/test/AtRulesTest.kt
kotlin-styled-next/src/test/kotlin/test/ElementTest.kt
kotlin-styled-next/src/test/kotlin/test/PseudoClassRulesTest.kt
kotlin-styled-next/src/test/kotlin/test/PseudoElementsTest.kt
kotlin-styled-next/src/test/kotlin/test/RelativeSelectorsTest.kt
kotlin-styled-next/src/test/kotlin/test/RemoveCssTest.kt
kotlin-styled-next/src/test/kotlin/test/StyleSheetTest.kt
kotlin-styled-next/src/test/kotlin/test/StyledCssEqualityTest.kt
kotlin-styled-next/src/test/kotlin/test/TestBase.kt
kotlin-styled-next/src/test/kotlin/test/styleSheets/StaticStyleSheet.kt

This pull request includes features (each one with the tests):
- fix multiple animations in a component
- fix classname appending to an existsing external classname
- add prefixer

[kotlin-styled-next] prefixer for styles

---

examples/src/main/kotlin/example/ReactRouterDom.kt
kotlin-react-router-dom/src/main/kotlin/react/router/dom/alias.kt
kotlin-react-router-dom/src/main/kotlin/react/router/dom/hooks.kt
kotlin-react-router-dom/src/main/kotlin/react/router/dom/imports.kt
kotlin-react-router-dom/src/main/kotlin/react/router/dom/routing.kt
kotlin-react-router-dom/src/main/kotlin/react/router/dom/routingDsl.kt

With existing implementation I can declare something like this:
```kotlin
external interface MyRouteParams : Props {
val first: Int
val second: Int
}
val MyComponent = fc<Props> {
val params = useParams<MyRouteParams>() ?: return@fc
println(params.first + params.second) // => for path /:first/:second and url /1/2 it will be string "12"
}
```
Prevent opportunity of creation `Params` type with non-string types of values. Use just `Record<String. String>` or `Params` type alias.
Before:
```kotlin
external interface SomeProps : Props {
val someId: String
}
val someId = useParams<SomeProps>()?.someId
```
After:
```kotlin
val someId = useParams()["someId"]
```
Also you can declare constant with you param and reuse it in you path:
```kotlin
val SOME_ID = "someId"
route("some/path/:$SOME_ID", …
```

Use `Record` for `Route` `Params` to prevent wrong typings

---

kotlin-react-router-dom/src/main/kotlin/react/router/dom/HashRouter.kt
kotlin-react-router-dom/src/main/kotlin/react/router/dom/routingDsl.kt

Strict `HashRouter.hashType`

---

kotlin-react/src/main/kotlin/react/Dependencies.kt
kotlin-react/src/main/kotlin/react/Dependencies.legacy.kt
kotlin-react/src/main/kotlin/react/Raw.kt
kotlin-react/src/main/kotlin/react/useEffect.kt
kotlin-react/src/main/kotlin/react/useImperativeHandle.kt

`Dependencies` type alias is introduced, `RDependenciesArray` is deprecated

---

kotlin-styled-next/src/main/kotlin/styled/GlobalStyles.kt
kotlin-styled-next/src/main/kotlin/styled/StyledComponents.kt

В предыдущей версии была проблема с тем, что когда приходило много одинаковых CSS, они не ставились в очередь на инжект, но инжект уже запланированных классов все равно происходил. Таким образом мы много раз обращались к браузерному API, из-за чего страдала производительность
Сейчас мы инжектим CSS только если рендерим компонент, в котором есть новые CSS, при этом проверяя что не добавилось новый стайлшитов

Inject scheduled only when css and stylesheet classes changed

---

kotlin-styled-next/src/main/kotlin/styled/StyleSheet.kt
kotlin-styled-next/src/test/kotlin/test/StyleSheetTest.kt

Добавился отложенный инжект в getClassName чтобы не обращаться к неинициализированным делегатам во время статической инициализации стайлшитов (в IR компиляторе)

Fix static initialization

---

kotlin-react-dom/src/main/kotlin/react/dom/ReactDOM.kt
kotlin-react-dom/src/main/kotlin/react/dom/createRoot.kt

[Source](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/cf5fb08bddb488919d99e2c3fea9c71f4fabbfa1/types/react-dom/next.d.ts#L39)

React DOM. Remove deprecated `RootOptions`

---

kotlin-react-dom/src/main/kotlin/react/dom/createPortal.kt

[Source](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0a9c9d85e8a9ae8aa4a96abbb2d9feac53dda9f6/types/react-dom/index.d.ts#L32)

React DOM. Missed `key` parameter for `createPortal`

---

kotlin-react/src/main/kotlin/react/ReactPortal.kt

[Source](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0a9c9d85e8a9ae8aa4a96abbb2d9feac53dda9f6/types/react/index.d.ts#L192)

React. Add missed `ReactPortal.children`

---

kotlin-mui/src/main/generated/mui/material/Autocomplete.kt

React. `AutocompleteProps` parent types [generated]

---

kotlin-extensions/src/main/kotlin/kotlinext/js/Symbol.kt
kotlin-react/src/main/kotlin/react/ChildrenBuilder.kt

Symbol declaration is required to avoid clash with [Symbol](https://github.com/Kotlin/kotlinx.coroutines/blob/7cc59e4f2b15961f10e94cddd3f2fb7fe331328a/kotlinx-coroutines-core/common/src/internal/Symbol.kt) in coroutines for IR compiler in Kotlin.

Add `Symbol` declaration

---

kotlin-css/build.gradle.kts

Without this any library with kotlin-css the dependency won't compile for a binary intended to use in Simulator.

Add new target to kotlin-css to support Apple Silicon architecture while building Kotlin/Native iOS binary

---

kotlin-styled-next/build.gradle.kts
kotlin-styled-next/src/main/kotlin/styled/sheets/CSSOMPersistentSheet.kt
kotlin-styled-next/src/main/kotlin/styled/sheets/CSSOMSheet.kt
kotlin-styled-next/src/main/kotlin/styled/sheets/DevSheet.kt
kotlin-styled-next/src/main/kotlin/styled/sheets/Sheet.kt
kotlin-styled-next/src/test/kotlin/TestUtils.kt
kotlin-styled-next/src/test/kotlin/benchmark/BenchmarkBase.kt
kotlin-styled-next/src/test/kotlin/benchmark/InjectCssNPlusOne.kt
kotlin-styled-next/src/test/kotlin/test/ElementTest.kt
kotlin-styled-next/src/test/kotlin/test/RemoveCssTest.kt
kotlin-styled-next/src/test/kotlin/test/SheetPartitioningTest.kt
kotlin-styled-next/src/test/kotlin/test/StyleSheetTest.kt
kotlin-styled-next/src/test/kotlin/test/TestBase.kt

It should make style recalculation cheaper when new CSS is injected

Split style sheet into smaller pieces

---

kotlin-styled-next/build.gradle.kts
kotlin-styled-next/src/test/kotlin/benchmark/AddDuplicateCss.kt
kotlin-styled-next/src/test/kotlin/benchmark/AddStyledElements.kt
kotlin-styled-next/src/test/kotlin/benchmark/BenchmarkBase.kt
kotlin-styled-next/src/test/kotlin/benchmark/ConvertToStyled.kt
kotlin-styled-next/src/test/kotlin/benchmark/CssBuildersInject.kt
kotlin-styled-next/src/test/kotlin/benchmark/DataTypeOperations.kt
kotlin-styled-next/src/test/kotlin/benchmark/InjectCssNPlusOne.kt

Enable `kotlin.time` in one place

---

examples/src/main/kotlin/example/ForwardingRefs.kt
kotlin-react/src/main/kotlin/react/ForwardRef.kt

React. `ForwardRef` factory method

---

kotlin-csstype/src/main/generated/csstype/AutoType.kt
kotlin-csstype/src/main/generated/csstype/GridLine.kt

CSSType. Fix `GridLine` type [generated]

---

kotlin-csstype/src/main/generated/csstype/RuleBuilder.kt
kotlin-csstype/src/main/generated/csstype/Rules.kt

[Related discussion](https://kotlinlang.slack.com/archives/C5ZTZ6ER0/p1648812884243099)
[Multiple `@font-face`](https://github.com/emotion-js/emotion/issues/1395)

CSSType. Support `@font-face` rule [generated]

---

kotlin-csstype/src/main/generated/csstype/Number.kt

CSSType. Numeric `flex` support [generated]

---

kotlin-react/src/main/kotlin/react/ChildrenBuilder.kt

React. Remove deprecated `children()` helper

---

kotlin-react-query/src/main/generated/react/query/mutationCache.core.kt
kotlin-react-query/src/main/generated/react/query/types.kt

React Query. Fix `UseBaseMutationResult` signature

---

kotlin-tanstack-react-table/src/main/generated/tanstack/table/core/CoreOptions.kt

React Table. Fix `getCoreRowModel` in `CoreOptions` [generated]

---

kotlin-popper/src/main/kotlin/popper/core/ReferenceElement.kt

Popper. Fix `ReferenceElement` contract

---

kotlin-react-dom/src/main/generated/react/dom/events/KeyboardEvent.kt
kotlin-react-dom/src/main/generated/react/dom/html/ButtonHTMLAttributes.kt
kotlin-react-dom/src/main/generated/react/dom/html/DataHTMLAttributes.kt
kotlin-react-dom/src/main/generated/react/dom/html/HTMLAttributes.kt
kotlin-react-dom/src/main/generated/react/dom/html/InputHTMLAttributes.kt
kotlin-react-dom/src/main/generated/react/dom/html/LiHTMLAttributes.kt
kotlin-react-dom/src/main/generated/react/dom/html/MeterHTMLAttributes.kt
kotlin-react-dom/src/main/generated/react/dom/html/OptionHTMLAttributes.kt
kotlin-react-dom/src/main/generated/react/dom/html/ParamHTMLAttributes.kt
kotlin-react-dom/src/main/generated/react/dom/html/ProgressHTMLAttributes.kt
kotlin-react-dom/src/main/generated/react/dom/html/SelectHTMLAttributes.kt
kotlin-react-dom/src/main/generated/react/dom/html/TextareaHTMLAttributes.kt

React. Fix `value`, `min`, `max` types [generated]

---

kotlin-node/src/main/generated/node/querystring/ParseOptions.kt
kotlin-node/src/main/generated/node/querystring/ParsedUrlQuery.kt
kotlin-node/src/main/generated/node/querystring/ParsedUrlQueryInput.kt
kotlin-node/src/main/generated/node/querystring/StringifyOptions.kt
kotlin-node/src/main/generated/node/querystring/escape.kt
kotlin-node/src/main/generated/node/querystring/parse.kt
kotlin-node/src/main/generated/node/querystring/stringify.kt
kotlin-node/src/main/generated/node/querystring/unescape.kt

Node. `querystring` [generated]

---

kotlin-node/src/main/generated/node/fs/CopyOptions.kt

Node. Use `PromiseResult` interface [generated]

---

kotlin-node/src/main/generated/node/events/EventEmitter.kt

Node. Fix `EventEmitter` hierarchy [generated]

---

kotlin-node/src/main/generated/node/util/InspectOptions.kt

Node. `util` [generated]

---

kotlin-js/src/main/kotlin/kotlinx/js/AsyncIterator.kt

JS. Non-sealed `AsyncIterable`

---

kotlin-remix-run-router/README.md
kotlin-remix-run-router/karakum/convertGeneratePath.js
kotlin-remix-run-router/karakum/convertGeneratePathParams.js
kotlin-remix-run-router/karakum/convertMatchPath.js
kotlin-remix-run-router/karakum/convertPathParam.js
kotlin-remix-run-router/src/main/generated/remix/run/router/generatePath.kt
kotlin-remix-run-router/src/main/generated/remix/run/router/matchPath.kt

Hardcode for `matchPath` and `generatePath` params is removed.

React Router: hardcode is removed

---

kotlin-react-router/karakum/plugins/convertRouteObjects.js
kotlin-react-router/src/jsMain/generated/react/router/IndexRouteObject.kt
kotlin-react-router/src/jsMain/generated/react/router/NonIndexRouteObject.kt
kotlin-react-router/src/jsMain/kotlin/react/router/IndexRouteObject.ext.kt
kotlin-react-router/src/jsMain/kotlin/react/router/NonIndexRouteObject.ext.kt
kotlin-react-router/src/jsMain/kotlin/react/router/Route.ext.kt
kotlin-react-router/src/jsMain/kotlin/react/router/useRoutes.ext.kt

Fixes for #1916:
1.  Invalid `RouteObject` - ~~single type expected in result~~ checkers with contracts are added
2.  Duplicated `useRoutes` - inline function with single parameter is added

React Router: declarations improvements

---

README.md

Fix Quill link in README as per issue #1934

Fix Quill link in README

---

README.md
kotlin-wrappers-bom/README.md

This avoids warnings when publishing a KMP artifact.

Use Gradle's platform instead of enforcedPlatform for BOM

---

buildSrc/src/main/kotlin/kotlin-conventions.gradle.kts
kotlin-js/src/jsMain/kotlin/js/typedarrays/Uint8Array.kt

Not sure if `as-` is the correct way to express what's happening here.  
A new instance is created, so maybe `to-` is better. But then it's not aligned with `Int8Array`.
Edit: on a second thought, while a new instance is created, no copying is performed, the new `Int8Array` is only a view over the buffer, so maybe `as-` is totally ok.

Allow converting Uint8Array-s to Kotlin's types

---

README.md

The certificate has expired for https://bytelegend.com/, so clicking on the link gives an ugly warning in most browsers.
A quickfix is to remove the link, and instead link to the GitHub page for ByteLegend.
https://github.com/ByteLegend/ByteLegend/issues/169

README: remove link to ByteLegends domain (cert expired)

---

buildSrc/settings.gradle.kts

Prevents Gradle warning: 
> Project accessors enabled, but root project name not explicitly set for 'buildSrc'. Checking out the project in different folders will impact the generated code and implicitly the buildscript classpath, breaking caching.

Add `buildSrc/settings.gradle.kts`

---

settings.gradle.kts

kotlin-history was removed in [e3911204bc241ba9cf8e9518f6c7f0cd0d97db58](https://github.com/JetBrains/kotlin-wrappers/commit/e3911204bc241ba9cf8e9518f6c7f0cd0d97db58)

remove kotlin-history from settings.gradle.kts

---

gradle.properties

[Gradle Build Cache](https://docs.gradle.org/current/userguide/build_cache.html) is a quick and easy way to improve build performance.

enable Gradle Build Cache

---

kotlin-js/src/jsMain/kotlin/js/objects/Object.kt

I'm not 100% sure because my IDE is still in K2 Alpha mode. I think narrowing down the generic type to T: Any prevents T from working with nullable values in this case, barring you from using it on a Record<String, Any?> 
Please confirm before merging, if this is the correct way to go about it.

Allow Object.entries to work on Record<String, Any?>

---

buildSrc/src/main/kotlin/NpmDependencies.kt
buildSrc/src/main/kotlin/Projects.kt
gradle.properties

In this PR:
* I tried to split two helper functions:
* `npmVersion`: npm library name -> dependency version
* `publishVersion`: kotlin wrapper subproject name -> version of published wrapper
* I used the results of refactoring to declare NPM version ranges explicitly in `gradle.properties`
Next possible steps: 
* use `versionCatalogs` to manage NPM dependencies

Use explicit NPM versions

---

.github/workflows/ci.yml
.github/workflows/package-lock.yml

- Consistently use Java 21 to run Gradle (helps with caching and performance).
- Update gradle/actions/wrapper-validation to v4, and add it to all steps.
- Use [gradle/actions/setup-gradle](https://github.com/gradle/actions/blob/v4.0.0/README.md#the-setup-gradle-action) to enable CI caching.

Update Gradle steps on CI

---

buildSrc/src/main/kotlin/Kotlin.kt
buildSrc/src/main/kotlin/publish-conventions.gradle.kts

- Add `readme.txt` to Javadoc JAR to explain why it's empty.
- Avoid conditional build config - always register the Javadoc JAR task, and avoid 'peeking' into KMP internals to conditionally add it. Always adding it is more robust.
- Use pluginsManager to lazily 'react' to plugins.
- Allow Gradle to set the project's group/artifactId/version in the POM. Manually setting these values is discouraged.
- Add a local-repo - very helpful for debugging.

Tidy Publishing Configuration

---

buildSrc/src/main/kotlin/kotlin-wrappers-subprojects-service.gradle.kts
buildSrc/src/main/kotlin/publish-conventions.gradle.kts
kotlin-wrappers-bom/build.gradle.kts

The recent change to automatically aggregate subprojects is nice, but in upcoming Gradle versions they are looking at disabling cross-project configuration, as it harms build configuration performance (https://docs.gradle.org/current/userguide/isolated_projects.html).
Using a BuildService will help with Gradle build performance, and is more future-proof.

Create Gradle BuildService for easier aggregation of kotlin-wrappers subprojects

---

.github/workflows/publish-github-pages.yml

Automatically publish the Dokka API docs to GitHub Pages.
GitHub pages might require some configuration in https://github.com/JetBrains/kotlin-wrappers/settings/pages
Hopefully this is the last step!
Fix https://github.com/JetBrains/kotlin-wrappers/issues/2228

Add GitHub Action to publish Dokka docs to GitHub Pages

---

buildSrc/src/main/kotlin/kotlin-conventions.gradle.kts

According to the YouTrack issue the reason was fixed in 2.0.20 and 2.0.20 is used already.
Thus this PR re-enables the option.

Re-enable `-Xir-generate-inline-anonymous-functions`

---

kotlin-js/src/jsMain/kotlin/js/promise/PromiseLike.kt

https://github.com/JetBrains/kotlin-wrappers/issues/2518

Promise. Non-sealed `PromiseLike` (fix #2518)

---

.editorconfig

Without the `root = true` implementations search further up until the filesystem root is reached.
Usually you want to stop in the root of your project.

Declare .editorconfig as root

---

gradle.properties
kotlin-mui-base/src/jsMain/generated/mui/base/useList.types.kt
kotlin-mui-base/src/jsMain/generated/mui/base/useTab.types.kt
kotlin-mui-material/src/jsMain/generated/mui/material/Tab.kt
kotlin-mui-system/src/jsMain/generated/mui/system/createSpacing.ext.kt

Material UI v5 is now compatible with React 19
https://github.com/mui/material-ui/releases/tag/v5.16.12
Build on CI is currently failed because it needed to update the `package-lock.json` by dependabot.

MUI `5.16.12`

---

build-logic/src/main/kotlin/wrappersbuild.kotlin-test-conventions.gradle.kts

Required for Gradle configuration caches to be enabled

Wrappers Build. Avoid using `project.extensions` in task configuration

---

examples/gradle.properties
gradle.properties

Speeds up the build process by skipping the same tasks configuration phase
Relies on #2784

Build. Enable parallel configuration caching

---

kotlin-js/src/commonMain/kotlin/js/temporal/DateUnit.kt
kotlin-js/src/commonMain/kotlin/js/temporal/PluralUnit.kt
kotlin-js/src/commonMain/kotlin/js/temporal/TimeUnit.kt

Manually inline tricky sealed interfaces in the `js.temporal` like `DateUnit`, `TimeUnit`, `PluralUnit`.
See [this issue](https://github.com/JetBrains/kotlin-wrappers/issues/2449).

JS. WASM-compatible union declarations for the Temporal API Units (#2449)

---

build-logic/generatorlegacybuild/src/main/kotlin/karakum/browser/Ed25519.kt
build-logic/generatorlegacybuild/src/main/kotlin/karakum/browser/Patches.kt
kotlin-web/src/commonMain/generated/web/crypto/Ed25519.kt
kotlin-web/src/commonMain/generated/web/crypto/SubtleCrypto.kt

Remove the remaining JsValue annotations from `browser` and `web` packages. [https://github.com/JetBrains/kotlin-wrappers/issues/2449](https://github.com/JetBrains/kotlin-wrappers/issues/2449)

Web. Remove `@JsValue` from `Ed25519` (#2449)

---

build-logic/generatorlegacybuild/src/main/kotlin/karakum/browser/BrowserExtensionsCollector.kt
build-logic/generatorlegacybuild/src/main/kotlin/karakum/browser/Events.kt
build-logic/generatorlegacybuild/src/main/kotlin/karakum/browser/Functions.kt
build-logic/generatorlegacybuild/src/main/kotlin/karakum/browser/Html.kt
build-logic/generatorlegacybuild/src/main/kotlin/karakum/common/ExtensionsCollector.kt
build-logic/generatorlegacybuild/src/main/kotlin/karakum/common/withSuspendExtensions.kt
kotlin-web/src/commonMain/generated/web/assembly/compile.kt
kotlin-web/src/commonMain/generated/web/assembly/compileStreaming.kt
kotlin-web/src/commonMain/generated/web/assembly/instantiate.kt
kotlin-web/src/commonMain/generated/web/assembly/instantiateStreaming.kt
kotlin-web/src/commonMain/generated/web/images/createImageBitmap.kt

There are no generated `@JsAsync` usages left in `js`, `web` and `browser` modules.

Web. Remove remaining `@JsAsync` from the `web` module (#2449).
