JetBrains/kotlin-wrappers

- kotlin-react/README.md
looks like a typo, or I missed something
> type String"

- examples/src/main/kotlin/example/Product
A thinking-in-react implementation
This is a port of https://reactjs.org/docs/thinking-in-react.html
> Create Product  (This is a port of https://reactjs.org/docs/thinking-in-react.html)

- README.md
An axios-search-example to show how to leverage famous networking lib axios to fetch remote data, also can learn how to add typing for an external lib . Btw, React just UI, so you need other libs to empower your app to do none UI matters.
> Add Axios-search-example

- kotlin-extensions/src/main/kotlin/kotlinext/js/CommonJS.kt
> Remove unneeded foo from CommonJS

- kotlin-react-router-dom/src/main/kotlin/react/router/dom/routing.kt
Added missing props (location and history)
> RouteResultProps enhancement

- kotlin-react-router-dom/src/main/kotlin/react/router/dom/routing.kt
- kotlin-react-router-dom/src/main/kotlin/react/router/dom/routingDsl.kt
I've also added support for className attribute in Link component.
> Add support for NavLink component

- kotlin-css/src/main/kotlin/kotlinx/css/StyleEnums.kt
> Fix using rgba notation with withAlpha

- kotlin-react-router-dom/package.json
- versions.gradle
Changelog: https://github.com/ReactTraining/react-router/blob/master/CHANGES.md#v430
> Bump react-router-dom to 4.3.1

- kotlin-css/src/main/kotlin/kotlinx/css/CSSBuilder.kt
- kotlin-css/src/main/kotlin/kotlinx/css/StyleDimensions.kt
- kotlin-css/src/main/kotlin/kotlinx/css/StyleEnums.kt
- kotlin-css/src/main/kotlin/kotlinx/css/StyledElement.kt
- kotlin-css/src/test/kotlin/kotlinx/css/TestGrid.kt
This pull request implements CSS3 grid support, as well as adding a few pseudo-class selectors.
> CSS grid support.

- build.gradle
- kotlin-react-redux/README.md
- kotlin-react-redux/build.gradle
- kotlin-react-redux/package.json
- kotlin-react-redux/src/main/kotlin/react/redux/Dsl.kt
- kotlin-react-redux/src/main/kotlin/react/redux/Helpers.kt
- kotlin-react-redux/src/main/kotlin/react/redux/Imports.kt
- kotlin-react-redux/src/main/kotlin/react/redux/Types.kt
- kotlin-redux/build.gradle
- settings.gradle
- versions.gradle
Adds react redux wrapper for Kotlin. Also includes helper function `rConnect` for connecting components using type-safe builders.
> React redux

- kotlin-css/src/main/kotlin/kotlinx/css/TagSelectors.kt
This will help developers who need to style all tags.
> Allow css tag for everything (*).

- kotlin-react-redux/src/main/kotlin/react/redux/Types.kt
I accidentally made the option objects immutable, should have been mutable for the builders
> Replace val with var in options

- kotlin-react-redux/README.md
Hi!  I love these libraries but the documentation can be a little opaque at times.
I wouldn't pretend that I've understood all the overloads of rConnect, but I'd like to be able to help get it documented a little better.
Thanks!
> Add some help using rConnect

- kotlin-react-router-dom/src/main/kotlin/react/router/dom/routing.kt
Added go, goBack and goForward functions to RouteResultHistory.
> Added go functions to RouteResultHistory

- kotlin-styled/package.json
- kotlin-styled/src/main/kotlin/styled/CSSBuilder.kt
- kotlin-styled/src/main/kotlin/styled/StyledComponents.kt
Fallback for injectGlobal (deprecated)
Fallback keyframes to keyframesName (deprecated)
> Migrate to styled-components v5.0.0-beta.8

- kotlin-react/src/main/kotlin/react/ReactComponent.kt
As requested by https://github.com/JetBrains/kotlin-wrappers/issues/61
and by https://github.com/JetBrains/kotlin-wrappers/issues/123
> Added RPureComponent to ReactComponent.kt

- README.md
> Remove reference to obsolete kotlinconf app

- build.gradle
- kotlin-css/build.gradle
Remove duplication
[Original extension](https://github.com/gradle/gradle/blob/54e9f7e056e0c6d3c40e64924d2b0ead95cee64a/buildSrc/subprojects/kotlin-dsl/src/main/kotlin/codegen/GenerateKotlinDependencyExtensions.kt#L88)
> Kotlin extension from Kotlin DSL

- build.gradle
- examples/build.gradle
- kotlin-css/build.gradle
- kotlin-extensions/build.gradle
- kotlin-mocha/build.gradle
- kotlin-react-dom/build.gradle
- kotlin-react-redux/build.gradle
- kotlin-react-router-dom/build.gradle
- kotlin-react/build.gradle
- kotlin-redux/build.gradle
- kotlin-styled/build.gradle
- settings.gradle
* Plugin in plugins DSL block
* Configuration via `plugins.withType`
Additional fixes:
* Remove `mavenLocal()` declaration
* Remove unused import
> Kotlin/JS. Standard plugin configuration

- build.gradle
- settings.gradle
> Plugin DSL instead of buildscript

- build.gradle
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/Versions.kt
- kotlin-css/build.gradle
- kotlin-extensions/build.gradle
- kotlin-mocha/build.gradle
- kotlin-react-dom/build.gradle
- kotlin-react-redux/build.gradle
- kotlin-react-router-dom/build.gradle
- kotlin-react/build.gradle
- kotlin-redux/build.gradle
- kotlin-styled/build.gradle
> Automatic publish version calculation

- examples/src/main/kotlin/example/Product.kt
- examples/src/main/kotlin/example/TicTacToe.kt
- gradle.properties
- kotlin-css/src/main/kotlin/kotlinx/css/Extensions.kt
- kotlin-css/src/main/kotlin/kotlinx/css/StyleDimensions.kt
- kotlin-css/src/main/kotlin/kotlinx/css/StyleEnums.kt
- kotlin-css/src/main/kotlin/kotlinx/css/StyledElement.kt
- kotlin-css/src/main/kotlin/kotlinx/css/properties/TextDecoration.kt
- kotlin-css/src/main/kotlin/kotlinx/css/properties/Transition.kt
- kotlin-css/src/test/kotlin/kotlinx/css/TestGrid.kt
- kotlin-react-dom/src/main/kotlin/react/dom/ReactDOMAttributes.kt
- kotlin-react-dom/src/main/kotlin/react/dom/ReactDOMTags.kt
- kotlin-react/src/main/kotlin/react/hooks.kt
- kotlin-styled/src/main/kotlin/styled/StyledTags.kt
[Official Kotlin Code Style](https://kotlinlang.org/docs/reference/code-style-migration-guide.html)
> Kotlin Style Guide

- buildSrc/build.gradle.kts
- buildSrc/gradle.properties
- buildSrc/src/main/kotlin/Dependencies.kt
- buildSrc/src/main/kotlin/Versions.kt
- buildSrc/src/main/kotlin/npm-publishing-conventions.gradle.kts
- gradle.properties
- kotlin-css/kotlin-css-js/package.json
- kotlin-css/kotlin-css-jvm/package.json
- kotlin-css/package.json
- kotlin-extensions/package.json
- kotlin-mocha/package.json
- kotlin-react-dom/package.json
- kotlin-react-redux/package.json
- kotlin-react-router-dom/package.json
- kotlin-react/package.json
- kotlin-redux/package.json
- kotlin-styled/package.json
- settings.gradle.kts
Common template - `$id.version`
| Dependency | `id` | Example |
| :--- | :---: | :--- |
|NPM| `$packageName`| `react-dom` | 
|Kotlin| `$projectId`| `kotlinx-html` | 
|Gradle plugin| `$name-plugin`| `bintray-plugin` | 
* [JUnit](https://github.com/junit-team/junit5/blob/master/gradle.properties)
* [JMeter](https://github.com/apache/jmeter/blob/master/gradle.properties)
> Version property unification

- build.gradle.kts
- examples/build.gradle.kts
- kotlin-react-dom/build.gradle.kts
- kotlin-react-redux/build.gradle.kts
- kotlin-react-router-dom/build.gradle.kts
- kotlin-react/build.gradle.kts
- kotlin-redux/build.gradle.kts
- kotlin-styled/build.gradle.kts
No `compile` configuration found in `M2`
> Migrate from 'compile' configuration

- kotlin-css/src/main/kotlin/kotlinx/css/StyleEnums.kt
[`coerceIn`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.ranges/coerce-in.html)
> coerceIn for normalization

- kotlin-css/src/main/kotlin/kotlinx/css/CSSBuilder.kt
- kotlin-css/src/main/kotlin/kotlinx/css/Extensions.kt
- kotlin-extensions/src/main/kotlin/kotlinext/js/Helpers.kt
- kotlin-react/src/main/kotlin/react/RBuilder.kt
- kotlin-react/src/main/kotlin/react/ReactComponent.kt
* Use standard `String.repeat`
> RClass accessor for KClass

- kotlin-redux/src/main/kotlin/redux/Serialization.kt
* Single json serializer/deserializer
* Remove unstable defaults usages
* Remove 'custom' json string constructing
> Redux. Update action serialization logic

- build.gradle.kts
* Enable for `ir` after source maps support
> Compilation. Strict mode

- build.gradle.kts
- buildSrc/src/main/kotlin/Kotlin.kt
- buildSrc/src/main/kotlin/ModuleArtifact.kt
- buildSrc/src/main/kotlin/publishing-conventions.gradle.kts
> Configure module artifact in 'publishing' extension

- buildSrc/src/main/kotlin/PackageJson.kt
- buildSrc/src/main/kotlin/Versions.kt
- buildSrc/src/main/kotlin/npm-publishing-conventions.gradle.kts
- kotlin-css/package.json
- kotlin-extensions/package.json
- kotlin-mocha/package.json
- kotlin-react-dom/package.json
- kotlin-react-redux/package.json
- kotlin-react-router-dom/package.json
- kotlin-react/package.json
- kotlin-redux/package.json
- kotlin-styled/package.json
Part of #201
* Update version source for `kotlin-styled`
* Before - `css.version` (looks like error)
* After - `styled.version`
> Fix package.json constructing

- buildSrc/src/main/kotlin/PackageJson.kt
- kotlin-css/package.json
- kotlin-extensions/package.json
- kotlin-mocha/package.json
- kotlin-react-dom/package.json
- kotlin-react-redux/package.json
- kotlin-react-router-dom/package.json
- kotlin-react/package.json
- kotlin-redux/package.json
- kotlin-styled/package.json
> Automatic* package.json calculation

- buildSrc/src/main/kotlin/PackageJson.kt
- buildSrc/src/main/kotlin/Tasks.kt
- buildSrc/src/main/kotlin/npm-publishing-conventions.gradle.kts
- kotlin-css/package.json
- kotlin-extensions/package.json
- kotlin-mocha/package.json
- kotlin-react-dom/package.json
- kotlin-react-redux/package.json
- kotlin-react-router-dom/package.json
- kotlin-react/package.json
- kotlin-redux/package.json
- kotlin-styled/package.json
> Cleanup NPM dist

- kotlin-css/build.gradle.kts
- kotlin-css/npm-adapter/build.gradle.kts
- settings.gradle.kts
> Add 'kotlin-css' NPM adapter

- build.gradle.kts
- buildSrc/src/main/kotlin/Tasks.kt
- buildSrc/src/main/kotlin/npm-publishing-conventions.gradle.kts
> Output in 'build/js/packages'

- build.gradle.kts
Tested configuration
```
kotlin.version=1.3.72
kotlinx-html.version=0.7.1
kotlinx-coroutines.version=1.3.5
kotlinx-serialization.version=0.20.0
```
> Kotlin 1.3 compat

- buildSrc/src/main/kotlin/PackageJson.kt
- kotlin-css/gradle.properties
- kotlin-css/package.json
- kotlin-extensions/gradle.properties
- kotlin-extensions/package.json
- kotlin-mocha/gradle.properties
- kotlin-mocha/package.json
- kotlin-react-dom/gradle.properties
- kotlin-react-dom/package.json
- kotlin-react-redux/gradle.properties
- kotlin-react-redux/package.json
- kotlin-react-router-dom/gradle.properties
- kotlin-react-router-dom/package.json
- kotlin-react/gradle.properties
- kotlin-react/package.json
- kotlin-redux/gradle.properties
- kotlin-redux/package.json
- kotlin-styled/gradle.properties
- kotlin-styled/package.json
> Description & author in gradle.properties

- buildSrc/build.gradle.kts
- buildSrc/gradle.properties
- buildSrc/src/main/kotlin/PackageJson.kt
- buildSrc/src/main/kotlin/npm-publishing-conventions.gradle.kts
- kotlin-css/package.json
- kotlin-extensions/package.json
- kotlin-mocha/package.json
- kotlin-react-dom/package.json
- kotlin-react-redux/package.json
- kotlin-react-router-dom/package.json
- kotlin-react/package.json
- kotlin-redux/package.json
- kotlin-styled/package.json
> Only 'peerDependencies' in package.json template

- buildSrc/src/main/kotlin/PackageJson.kt
- buildSrc/src/main/kotlin/Projects.kt
- buildSrc/src/main/kotlin/Versions.kt
- kotlin-css/package.json
- kotlin-extensions/package.json
- kotlin-mocha/package.json
- kotlin-react-dom/package.json
- kotlin-react-redux/package.json
- kotlin-react-router-dom/package.json
- kotlin-react/package.json
- kotlin-redux/package.json
- kotlin-styled/package.json
> Remove project dependencies from package.json template

- buildSrc/build.gradle.kts
- buildSrc/gradle.properties
- buildSrc/src/main/kotlin/PackageJson.kt
- buildSrc/src/main/kotlin/Projects.kt
- kotlin-mocha/build.gradle.kts
- kotlin-mocha/package.json
- kotlin-react-dom/build.gradle.kts
- kotlin-react-dom/package.json
- kotlin-react-redux/build.gradle.kts
- kotlin-react-redux/package.json
- kotlin-react-router-dom/build.gradle.kts
- kotlin-react-router-dom/package.json
- kotlin-react/build.gradle.kts
- kotlin-react/package.json
- kotlin-redux/build.gradle.kts
- kotlin-redux/package.json
- kotlin-styled/build.gradle.kts
- kotlin-styled/package.json
> Remove package json templates

- kotlin-extensions/src/main/kotlin/kotlinext/js/Object.kt
Use already declared `Object.getOwnPropertyNames()`
> Use existed method call

- kotlin-styled/src/main/kotlin/styled/InlineStylePrefixer.kt
- kotlin-styled/src/main/kotlin/styled/InlineStyles.kt
> Plain 'inline-style-prefixer' declarations

- kotlin-extensions/src/main/kotlin/kotlinext/js/Object.kt
[Specification](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Object)
> Sync JS Object declaration with specification

- kotlin-react/src/main/kotlin/react/Imports.kt
Details - https://reactjs.org/docs/react-api.html#reactchildren
> Remove Children undocumented method

- kotlin-styled/src/main/kotlin/styled/styled-components.kt
https://styled-components.com/docs/api#isstyledcomponent
> Fix 'isStyledComponent' contract

- buildSrc/src/main/kotlin/PackageJson.kt
- buildSrc/src/main/kotlin/maven-publishing-conventions.gradle.kts
```Kotlin
dependencies {
implementation("org.jetbrains.kotlin-wrappers:kotlin-react:1.0.1-pre.101")
implementation(npm("react", "16.3.1"))
}
```
```Kotlin
dependencies {
// npm 'react' dependency inside
implementation("org.jetbrains.kotlin-wrappers:kotlin-react:1.0.1-pre.101")
}
```
> Declare NPM dependencies in jar file

- buildSrc/src/main/kotlin/Projects.kt
- kotlin-mocha/build.gradle.kts
- kotlin-react-dom/build.gradle.kts
- kotlin-react-redux/build.gradle.kts
- kotlin-react-router-dom/build.gradle.kts
- kotlin-react/build.gradle.kts
- kotlin-redux/build.gradle.kts
- kotlin-styled/build.gradle.kts
> 'api' configuration for non-stdlib dependencies

- kotlin-styled/build.gradle.kts
> Use compatible 'styled-components'

- kotlin-css/src/commonMain/kotlin/kotlinx/css/StyleEnums.kt
- kotlin-css/src/commonMain/kotlin/kotlinx/css/StyledElement.kt
This pull request implements 'resize' css property.
https://developer.mozilla.org/en-US/docs/Web/CSS/resize
> Add 'resize' css property

- kotlin-css/README.md
- kotlin-extensions/README.md
- kotlin-mocha/README.md
- kotlin-react-dom/README.md
- kotlin-react-redux/README.md
- kotlin-react-router-dom/README.md
- kotlin-react/README.md
- kotlin-redux/README.md
- kotlin-styled/README.md
* Clickable shields - links to Bintray
* Shields in top (classic)
> Bintray shield links

- kotlin-styled/src/main/kotlin/styled/StyledComponents.kt
- kotlin-styled/src/main/kotlin/styled/styled-components.kt
- kotlin-styled/src/main/kotlin/styled/styled.kt
Additional:
* Use standard name for default import (like in docs)
> styled-components. Prepare IR support

- kotlin-react-router-dom/src/main/kotlin/react/router/dom/routing.kt
- kotlin-react-router-dom/src/main/kotlin/react/router/dom/routingDsl.kt
> Move HashType declaration to routingDsl.kt

- kotlin-react/src/main/kotlin/react/hooks.kt
First attempt - #299 
`inline` - wa for [custom delegate problem](https://github.com/JetBrains/kotlin-wrappers/pull/299#issuecomment-632757270)
> useState. Avoid additional imports (getValue, setValue)

- buildSrc/src/main/kotlin/Dependencies.kt
- buildSrc/src/main/kotlin/Projects.kt
- kotlin-mocha/build.gradle.kts
- kotlin-react-dom/build.gradle.kts
- kotlin-react-redux/build.gradle.kts
- kotlin-react-router-dom/build.gradle.kts
- kotlin-react/build.gradle.kts
- kotlin-redux/build.gradle.kts
> Automatic NPM dependency version calculation

- README.md
> Update Kotlin version badge

- kotlin-styled/README.md
Link was no longer available. Hopefully this is the same content as before.
> Fix information link about styled components.

- kotlin-extensions/src/main/kotlin/kotlinext/js/Record.kt
- kotlin-react-table/src/main/kotlin/react/table/Expanded.kt
- kotlin-react-table/src/main/kotlin/react/table/GroupBy.kt
- kotlin-react-table/src/main/kotlin/react/table/Table.kt
Original `Record` - https://www.typescriptlang.org/docs/handbook/utility-types.html#recordkeystype
\+ @vlsi
> Move `Record` to base classes

- kotlin-css/src/commonMain/kotlin/kotlinx/css/StyleEnums.kt
- kotlin-css/src/commonMain/kotlin/kotlinx/css/StyledElement.kt
[appearance](https://developer.mozilla.org/en-US/docs/Web/CSS/appearance)
> CSS. Add `appearance` support

- kotlin-react/src/main/kotlin/react/hooks.kt
> `useCallback` with "kotlin" signature

- kotlin-react-table/src/main/kotlin/react/table/Table.kt
Related PR - https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50784
[Test project](https://codesandbox.io/s/exciting-taussig-fhn9o?file=/src/App.js:867-985)
> react-table. Fix `TableToggleCommonProps.onChange` contract

- kotlin-extensions/src/main/kotlin/kotlinext/js/ReadonlyArray.kt
[Name source](https://www.typescriptlang.org/docs/handbook/2/objects.html#the-readonlyarray-type)
> Add `ReadonlyArray` typealias

- README.md
An [example of using react-table](https://github.com/aerialist7/kotlin-react-table-sample) that shows how to use react-table with hooks API
> Add an example of using react-table

- kotlin-react/src/main/kotlin/react/Imports.kt
- kotlin-react/src/main/kotlin/react/ReactComponent.kt
> #366 Fix ref hierarchy

- kotlin-react/src/main/kotlin/react/Imports.kt
[DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a7de57784aa1990d0849db96157acd960b87fa5c/types/react/index.d.ts#L1060)
> Fix "useRef" contract

- kotlin-react-dom/src/main/kotlin/react/dom/RDOMBuilder.kt
> InnerHTML - plain object. Remove redundant anonymous class

- .github/workflows/ci.yml
See: https://github.com/gradle/wrapper-validation-action
> Add Official Gradle Wrapper Validation Action

- gradle.properties
[React 17.0.2](https://github.com/facebook/react/blob/master/CHANGELOG.md#1702-march-22-2021)
> Hot update for `react`. Fix for `SharedArrayBuffer`

- kotlin-react-table/src/main/kotlin/react/table/PluginHook.kt
- kotlin-react-table/src/main/kotlin/react/table/Table.kt
Related issue - [KT-46364](https://youtrack.jetbrains.com/issue/KT-46364)
> react-table. IR compatibility fixes

- gradle.properties
Sync group naming with other JetBrains libraries (Kotlin, Coroutines, Serialization)
cc @ilgonmic, @SebastianAigner, @kalibrov520
> Fix `groupId`

- buildSrc/src/main/kotlin/maven-publishing-conventions.gradle.kts
> Prepare Maven Central publication

- kotlin-react-dom/src/main/kotlin/react/dom/server/Imports.kt
- kotlin-react-dom/src/main/kotlin/react/dom/server/ReactDOMServer.kt
`renderToString` and `renderToStaticMarkup` functions are supported
https://reactjs.org/docs/react-dom-server.html
> `renderToString` and `renderToStaticMarkup` functions are supported

- kotlin-react/src/main/kotlin/react/hooks.kt
Making the problem from #456 easier to resolve, adding kdoc.
> Adding hint for #456

- kotlin-react/src/main/kotlin/react/Imports.kt
- kotlin-react/src/main/kotlin/react/hooks.kt
Remove redundant `useState` wrapping
cc @ilgonmic
> Inline `useState` result operators

- kotlin-css/src/commonMain/kotlin/kotlinx/css/StyleEnums.kt
- kotlin-css/src/commonMain/kotlin/kotlinx/css/StyledElement.kt
Use `LianearDimension` instead
> Remove separate `Gap` type

- kotlin-react/src/main/kotlin/react/RStateDelegate.kt
- kotlin-react/src/main/kotlin/react/hooks.kt
> Separate file for `RStateDelegate`

- kotlin-react/src/main/kotlin/react/RBuilder.kt
[According to TypeScript](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ee41c7775cbef5adac923ce7721e7008a4a6338f/types/react/index.d.ts#L538)
> Create `FC` typealias for `FunctionalComponent`

- kotlin-react/src/main/kotlin/react/RStateDelegate.kt
> Fix `RSetState` contract

- kotlin-react/src/main/kotlin/react/EffectBuilder.kt
> Fix builder name. `REffectBuilder` -> `EffectBuilder`

- kotlin-react-table/src/main/kotlin/react/table/Table.kt
Use [most typical contract](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/51e77dacacf9d22ede03f0c7beeb244dc5346f1a/types/react-table/index.d.ts#L182)
> Fix `PropGetter` contract

- kotlin-react-table/src/main/kotlin/react/table/Table.kt
[As in original](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/51e77dacacf9d22ede03f0c7beeb244dc5346f1a/types/react-table/index.d.ts#L116)
> Mutable `TableCommonProps`

- kotlin-react/src/main/kotlin/react/Imports.kt
- kotlin-react/src/main/kotlin/react/SuspenseConfig.kt
- kotlin-react/src/main/kotlin/react/TransitionInstance.kt
> Declare `SuspenseConfig`

- kotlin-react-router-dom/src/main/kotlin/react/router/dom/hooks.kt
- kotlin-react-router-dom/src/main/kotlin/react/router/dom/imports.kt
> Strict return type for `useParams`

- kotlin-react-router-dom/src/main/kotlin/react/router/dom/routing.kt
- kotlin-react-router-dom/src/main/kotlin/react/router/dom/routingDsl.kt
> Simplify `react-router-dom` declarations

- README.md
- buildSrc/src/main/kotlin/Projects.kt
- gradle.properties
- kotlin-react-table/src/main/kotlin/react/table/GroupBy.kt
- kotlin-ring-ui/README.md
- kotlin-ring-ui/build.gradle.kts
- kotlin-ring-ui/gradle.properties
- kotlin-ring-ui/src/main/kotlin/ringui/Alert.kt
- kotlin-ring-ui/src/main/kotlin/ringui/AlertType.kt
- kotlin-ring-ui/src/main/kotlin/ringui/Button.kt
- kotlin-ring-ui/src/main/kotlin/ringui/Dialog.ext.kt
- kotlin-ring-ui/src/main/kotlin/ringui/Dialog.kt
- kotlin-ring-ui/src/main/kotlin/ringui/Dropdown.ext.kt
- kotlin-ring-ui/src/main/kotlin/ringui/Dropdown.kt
- kotlin-ring-ui/src/main/kotlin/ringui/Grid.kt
- kotlin-ring-ui/src/main/kotlin/ringui/Header.kt
- kotlin-ring-ui/src/main/kotlin/ringui/Icon.kt
- kotlin-ring-ui/src/main/kotlin/ringui/Island.ext.kt
- kotlin-ring-ui/src/main/kotlin/ringui/Island.kt
- kotlin-ring-ui/src/main/kotlin/ringui/Link.kt
- kotlin-ring-ui/src/main/kotlin/ringui/RowPosition.kt
- kotlin-ring-ui/src/main/kotlin/ringui/Tabs.ext.kt
- kotlin-ring-ui/src/main/kotlin/ringui/Tabs.kt
- kotlin-ring-ui/src/main/kotlin/ringui/UserCard.kt
- kotlin-wrappers-bom/build.gradle.kts
- settings.gradle.kts
@ilgonmic, @altavir, @turansky
> Add Ring UI wrappers

- gradle.properties
- kotlin-wrappers-bom/build.gradle.kts
- settings.gradle.kts
> Alphabetic modules sorting

- kotlin-react-query/src/main/kotlin/react/query/MutationStatus.core.kt
- kotlin-react-query/src/main/kotlin/react/query/QueryStatus.core.kt
- kotlin-react-query/src/main/kotlin/react/query/QueryStatusFilter.core.kt
- kotlin-react-query/src/main/kotlin/react/query/types.core.kt
- kotlin-react-query/src/main/kotlin/react/query/utils.core.kt
> Enums instead of unions

- kotlin-react-query/src/main/kotlin/react/query/types.core.kt
> `QueryFunction` & Naming Improvements

- kotlin-react-query/src/main/kotlin/react/query/broadcastQueryClient.kt
> Add `broadcastQueryClient`

- kotlin-react/src/main/kotlin/react/Imports.kt
Single `memo` signature is introduced
> Single `memo` signature

- kotlin-react/src/main/kotlin/react/Children.kt
- kotlin-react/src/main/kotlin/react/Component.kt
- kotlin-react/src/main/kotlin/react/Imports.kt
- kotlin-react/src/main/kotlin/react/Profiler.kt
- kotlin-react/src/main/kotlin/react/PureComponent.kt
- kotlin-react/src/main/kotlin/react/Suspense.kt
- kotlin-react/src/main/kotlin/react/useReducer.kt
- kotlin-react/src/main/kotlin/react/useState.kt
> Kotlin React: `Imports.kt` separation

- kotlin-react/src/main/kotlin/react/Fragment.kt
- kotlin-react/src/main/kotlin/react/Imports.kt
- kotlin-react/src/main/kotlin/react/ReactComponent.kt
- kotlin-react/src/main/kotlin/react/StrictMode.kt
- kotlin-react/src/main/kotlin/react/lazy.kt
- kotlin-react/src/main/kotlin/react/memo.kt
- kotlin-react/src/main/kotlin/react/useDebugValue.kt
- kotlin-react/src/main/kotlin/react/useImperativeHandle.kt
- kotlin-react/src/main/kotlin/react/useTransition.kt
> Separate files for `react` members

- kotlin-react/src/main/kotlin/react/ComponentClass.kt
- kotlin-react/src/main/kotlin/react/RComponent.kt
- kotlin-react/src/main/kotlin/react/RPureComponent.kt
- kotlin-react/src/main/kotlin/react/React.kt
- kotlin-react/src/main/kotlin/react/ReactComponent.kt
> Separate files for abstract components

- kotlin-react/src/main/kotlin/react/Context.kt
- kotlin-react/src/main/kotlin/react/Imports.kt
- kotlin-react/src/main/kotlin/react/ReactComponent.kt
> Separate file for `Context` logic

- kotlin-react/src/main/kotlin/react/Imports.kt
- kotlin-react/src/main/kotlin/react/ReactComponent.kt
- kotlin-react/src/main/kotlin/react/Ref.kt
> Separate file for `Ref` logic

- kotlin-react/src/main/kotlin/react/ComponentClass.kt
- kotlin-react/src/main/kotlin/react/ComponentType.kt
- kotlin-react/src/main/kotlin/react/FunctionComponent.kt
- kotlin-react/src/main/kotlin/react/RBuilder.kt
> Separate file for `FunctionComponent`

- kotlin-css/src/commonMain/kotlin/kotlinx/css/StyleEnums.kt
- kotlin-css/src/commonMain/kotlin/kotlinx/css/StyledElement.kt
https://developer.mozilla.org/en-US/docs/Web/CSS/isolation
cc @turansky
> Kotlin CSS: Declare `isolation` property

- kotlin-react/src/main/kotlin/react/lazy.kt
> Fix `lazy` contract

- kotlin-react/src/main/kotlin/react/RBuilder.kt
> Simplify `renderEach` extensions

- kotlin-react-redux/src/main/kotlin/react/redux/Dsl.kt
- kotlin-react-redux/src/main/kotlin/react/redux/Imports.kt
- kotlin-react/src/main/kotlin/react/ComponentClass.kt
- kotlin-react/src/main/kotlin/react/Context.kt
- kotlin-react/src/main/kotlin/react/Context.legacy.kt
- kotlin-react/src/main/kotlin/react/RBuilder.kt
[Source](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/328064fd432eb99ecc442979b5c4fd5d299d50e6/types/react/index.d.ts#L375)
> Standard naming for `Context` types

- kotlin-react/src/main/kotlin/react/RBuilder.kt
> RBuilder node extensions are deprecated

- kotlin-react/src/main/kotlin/react/Component.kt
- kotlin-react/src/main/kotlin/react/ErrorInfo.kt
> ErrorInfo is renamed and moved to Component

- kotlin-react/src/main/kotlin/react/Imports.kt
- kotlin-react/src/main/kotlin/react/RBuilder.kt
- kotlin-react/src/main/kotlin/react/forwardRef.kt
> forwardRef is extracted

- examples/src/main/kotlin/example/ReactRouterDom.kt
- kotlin-react/README.md
- kotlin-react/src/main/kotlin/react/FunctionComponent.kt
- kotlin-react/src/main/kotlin/react/FunctionalComponent.legacy.kt
- kotlin-react/src/main/kotlin/react/RBuilder.kt
- kotlin-react/src/main/kotlin/react/ReducerInstance.kt
- kotlin-react/src/main/kotlin/react/StateInstance.kt
- kotlin-react/src/main/kotlin/react/useCallback.kt
- kotlin-react/src/main/kotlin/react/useEffect.kt
- kotlin-react/src/main/kotlin/react/useLayoutEffect.kt
- kotlin-react/src/main/kotlin/react/useMemo.kt
- kotlin-styled/src/main/kotlin/styled/StyledComponents.kt
> functionalComponent is deprecated

- kotlin-react/src/main/kotlin/react/Child.kt
- kotlin-react/src/main/kotlin/react/React.kt
> Child is extracted

- kotlin-react/README.md
- kotlin-styled/README.md
1. add a document for "effect hooks with cleanup"
2. add a document for "custom hook"
3. add more content to how to use global CSS
> improve documents

- examples/src/main/kotlin/example/ReactRouterDom.kt
- kotlin-react/README.md
- kotlin-react/src/main/kotlin/react/FunctionComponent.kt
- kotlin-react/src/main/kotlin/react/FunctionalComponent.legacy.kt
- kotlin-react/src/main/kotlin/react/ReducerInstance.kt
- kotlin-react/src/main/kotlin/react/StateInstance.kt
- kotlin-react/src/main/kotlin/react/useCallback.kt
- kotlin-react/src/main/kotlin/react/useEffect.kt
- kotlin-react/src/main/kotlin/react/useLayoutEffect.kt
- kotlin-react/src/main/kotlin/react/useMemo.kt
- kotlin-styled/src/main/kotlin/styled/StyledComponents.kt
> `fc` - default component factory method

- kotlin-react/src/main/kotlin/react/Imports.kt
- kotlin-react/src/main/kotlin/react/React.kt
- kotlin-react/src/main/kotlin/react/ReactElement.kt
> Separate `ReactElement`

- kotlin-react-router-dom/src/main/kotlin/react/router/dom/routingDsl.kt
> No return type for route helpers

- kotlin-react/src/main/kotlin/react/ReactElement.kt
> `props` are optional in `createElement`

- examples/src/main/kotlin/example/ReactRouterDom.kt
- kotlin-react-router-dom/src/main/kotlin/react/router/dom/routing.kt
- kotlin-react-router-dom/src/main/kotlin/react/router/dom/routingDsl.kt
> Fix `Router` signature

- kotlin-ring-ui/src/main/kotlin/ringui/Alert.kt
- kotlin-ring-ui/src/main/kotlin/ringui/Button.kt
- kotlin-ring-ui/src/main/kotlin/ringui/Dialog.kt
- kotlin-ring-ui/src/main/kotlin/ringui/Dropdown.kt
- kotlin-ring-ui/src/main/kotlin/ringui/Grid.kt
- kotlin-ring-ui/src/main/kotlin/ringui/Header.kt
- kotlin-ring-ui/src/main/kotlin/ringui/Icon.kt
- kotlin-ring-ui/src/main/kotlin/ringui/Island.kt
- kotlin-ring-ui/src/main/kotlin/ringui/Link.kt
- kotlin-ring-ui/src/main/kotlin/ringui/Tabs.kt
- kotlin-ring-ui/src/main/kotlin/ringui/UserCard.kt
> Ring UI: `RClass` -> `ComponentClass`

- kotlin-ring-ui/src/main/kotlin/ringui/Dropdown.ext.kt
> Ring UI: Fix `Dropdown` return type

- kotlin-react/src/main/kotlin/react/FunctionComponent.kt
- kotlin-react/src/main/kotlin/react/FunctionalComponent.legacy.kt
> New FC signatures don't receive nullable `displayName`

- kotlin-react-redux/src/main/kotlin/react/redux/Dsl.kt
- kotlin-react-router-dom/src/main/kotlin/react/router/dom/routingDsl.kt
> Idiomatic builder API in redux and router DSL

- README.md
- kotlin-wrappers-bom/README.md
> Kotlin Wrappers BOM: `README.md`

- README.md
> README: Declare "Using in your projects" section

- kotlin-react-query/src/main/kotlin/react/query/mutationCache.core.kt
- kotlin-react-query/src/main/kotlin/react/query/queryCache.core.kt
> React Query: Add `onSuccess` callback

- README.md
> README: Improve "Using in your projects" section

- gradle.properties
> react-query 3.19.0

- README.md
> Pin BOM version in header

- kotlin-react-dom/src/main/kotlin/react/dom/RDOMBuilder.kt
- kotlin-react/src/main/kotlin/react/Props.kt
- kotlin-react/src/main/kotlin/react/RBuilder.kt
- kotlin-react/src/main/kotlin/react/RRef.kt
- kotlin-react/src/main/kotlin/react/Raw.kt
- kotlin-react/src/main/kotlin/react/Ref.kt
- kotlin-react/src/main/kotlin/react/forwardRef.kt
- kotlin-react/src/main/kotlin/react/useImperativeHandle.kt
> `RRef` -> `Ref`

- kotlin-react-dom/src/main/kotlin/react/dom/ReactDOM.kt
- kotlin-react-dom/src/main/kotlin/react/dom/server/ReactDOMServer.kt
- kotlin-react-router-dom/src/main/kotlin/react/router/dom/routingDsl.kt
- kotlin-react/src/main/kotlin/react/RBuilder.kt
- kotlin-react/src/main/kotlin/react/React.kt
> `RRender` -> `Render`

- README.md
- examples/src/main/kotlin/example/AxiosSearch.kt
- examples/src/main/kotlin/example/Product.kt
- examples/src/main/kotlin/example/Quill.kt
- examples/src/main/kotlin/example/TicTacToe.kt
- examples/src/main/kotlin/example/Todo.kt
- gradle.properties
- kotlin-react-dom/src/main/kotlin/react/dom/ReactDOMTags.kt
- kotlin-react/src/main/kotlin/react/RBuilder.kt
- kotlin-styled/src/main/kotlin/styled/StyledComponents.kt
- kotlin-styled/src/main/kotlin/styled/StyledTags.kt
- kotlin-wrappers-bom/README.md
> Kotlin React: No longer return type for `child` function

- kotlin-react/src/main/kotlin/react/RefCallback.kt
> Add `useRefCallback` hook

- kotlin-react/src/main/kotlin/react/EffectBuilder.kt
- kotlin-react/src/main/kotlin/react/useEffect.kt
> `RCleanup` -> `Cleanup`

- kotlin-react-query/src/main/kotlin/react/query/QueryClientProvider.kt
- kotlin-react-query/src/main/kotlin/react/query/QueryErrorResetBoundary.kt
> Use valid component type

- kotlin-react-dom/src/main/kotlin/react/dom/RDOMBuilder.kt
- kotlin-react-table/src/main/kotlin/react/table/Table.kt
- kotlin-react/src/main/kotlin/react/Key.kt
- kotlin-react/src/main/kotlin/react/Props.kt
- kotlin-react/src/main/kotlin/react/RBuilder.kt
> Move `Key` from `react-table` to `react`

- gradle.properties
> `react-query v.3.19.1`

- kotlin-react-table/src/main/kotlin/react/table/ColumnOrder.kt
- kotlin-react-table/src/main/kotlin/react/table/Columns.kt
- kotlin-react-table/src/main/kotlin/react/table/Expanded.kt
- kotlin-react-table/src/main/kotlin/react/table/GroupBy.kt
- kotlin-react-table/src/main/kotlin/react/table/Pagination.kt
- kotlin-react-table/src/main/kotlin/react/table/RowSelect.kt
- kotlin-react-table/src/main/kotlin/react/table/RowState.kt
- kotlin-react-table/src/main/kotlin/react/table/Table.kt
> Use `ReadonlyArray`

- kotlin-css/src/commonMain/kotlin/kotlinx/css/CSSBuilder.kt
- kotlin-css/src/commonMain/kotlin/kotlinx/css/CssDsl.kt
- kotlin-styled-next/src/jsMain/kotlin/styled/StyledComponents.kt
- kotlin-styled/src/main/kotlin/styled/StyledComponents.kt
> Isolation for `css` block (no DOM in `css`)

- kotlin-react/src/main/kotlin/react/Props.kt
- kotlin-react/src/main/kotlin/react/RBuilder.kt
- kotlin-react/src/main/kotlin/react/ReactDsl.kt
> DSL marker for `RProps`

- kotlin-react/src/main/kotlin/react/ComponentClass.kt
- kotlin-react/src/main/kotlin/react/RBuilder.kt
> Fix incorrect `ReplaceWith`s

- kotlin-react-router-dom/src/main/kotlin/react/router/dom/routing.kt
- kotlin-react-router-dom/src/main/kotlin/react/router/dom/routingDsl.kt
> React Router DOM: Standard component naming

- kotlin-react-router-dom/src/main/kotlin/react/router/dom/alias.kt
- kotlin-react-router-dom/src/main/kotlin/react/router/dom/hooks.kt
- kotlin-react-router-dom/src/main/kotlin/react/router/dom/imports.kt
- kotlin-react-router-dom/src/main/kotlin/react/router/dom/routing.kt
- kotlin-react-router-dom/src/main/kotlin/react/router/dom/routingDsl.kt
Closes #99 
cc @turansky @sgrishchenko
> Support history in `RouterProps`

- kotlin-ring-ui/src/main/kotlin/ringui/Button.kt
- kotlin-ring-ui/src/main/kotlin/ringui/ButtonGroup.kt
- kotlin-ring-ui/src/main/kotlin/ringui/Heading.kt
- kotlin-ring-ui/src/main/kotlin/ringui/Input.kt
Added: 
- ButtonGroup
- Heading
- Input
Also added a disabled property to the Button component.
> Added new components to ring-ui

- kotlin-react/src/main/kotlin/react/ComponentType.kt
- kotlin-react/src/main/kotlin/react/ElementType.kt
[DT](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8d4c8f0a784733c050debdaa072920956a42acc4/types/react/index.d.ts#L73)
> Add missed `ElementType`

- kotlin-react/src/main/kotlin/react/RBuilder.kt
- kotlin-react/src/main/kotlin/react/ReactElement.kt
> Common `child` contract

- kotlin-react/src/main/kotlin/react/IntrinsicType.kt
cc @sgrishchenko @aerialist7 
[Examples](https://github.com/turansky/react-types-kotlin/blob/5f064c213b1742a3b79a7a5f7c414d4e866d81a3/react-kotlin/src/main/kotlin/react/IntrinsicTypes.kt)
> Add `IntrinsicType`

- kotlin-react-table/src/main/kotlin/react/table/Table.kt
> `Props` for `react-table`

- kotlin-styled-next/build.gradle.kts
> Remove redundant repositories declaration

- kotlin-react/src/main/kotlin/react/ReactNode.kt
Preparation for strict children type.
cc @turansky @aerialist7
> Safe constructor for `ReactNode` based on `String`

- kotlin-react-dom/src/main/kotlin/react/dom/RDOMBuilder.kt
- kotlin-react/src/main/kotlin/react/RBuilder.kt
- kotlin-react/src/main/kotlin/react/ReactNode.kt
> Strict children

- kotlin-react-dom/src/main/kotlin/react/dom/RDOMBuilder.kt
- kotlin-react/src/main/kotlin/react/RBuilder.kt
- kotlin-react/src/main/kotlin/react/React.kt
- kotlin-react/src/main/kotlin/react/ReactElement.kt
- kotlin-react/src/main/kotlin/react/ReactNode.kt
- kotlin-styled-next/src/jsMain/kotlin/styled/StyledComponents.kt
- kotlin-styled/src/main/kotlin/styled/StyledComponents.kt
> Typesafe `createElement` and `cloneElement`

- kotlin-react/src/main/kotlin/react/ReactNode.kt
> Fix method order

- kotlin-react-router-dom/src/main/kotlin/react/router/dom/routing.kt
- kotlin-react-router-dom/src/main/kotlin/react/router/dom/routingDsl.kt
> Update `Route`, `Link`, `NavLink` contracts

- kotlin-styled-next/build.gradle.kts
Valid hierarchy
cc @sgrishchenko @tretikoff
> Tasks configuration outside `sourceSets`

- examples/build.gradle.kts
> Security update

- kotlin-react-dom/src/main/generated/react/dom/AnimationEvent.kt
- kotlin-react-dom/src/main/generated/react/dom/BaseSyntheticEvent.kt
- kotlin-react-dom/src/main/generated/react/dom/ChangeEvent.kt
- kotlin-react-dom/src/main/generated/react/dom/ClipboardEvent.kt
- kotlin-react-dom/src/main/generated/react/dom/CompositionEvent.kt
- kotlin-react-dom/src/main/generated/react/dom/DragEvent.kt
- kotlin-react-dom/src/main/generated/react/dom/EventHandlers.kt
- kotlin-react-dom/src/main/generated/react/dom/FocusEvent.kt
- kotlin-react-dom/src/main/generated/react/dom/FormEvent.kt
- kotlin-react-dom/src/main/generated/react/dom/InvalidEvent.kt
- kotlin-react-dom/src/main/generated/react/dom/KeyboardEvent.kt
- kotlin-react-dom/src/main/generated/react/dom/MouseEvent.kt
- kotlin-react-dom/src/main/generated/react/dom/NativeEvents.kt
- kotlin-react-dom/src/main/generated/react/dom/PointerEvent.kt
- kotlin-react-dom/src/main/generated/react/dom/SyntheticEvent.kt
- kotlin-react-dom/src/main/generated/react/dom/TouchEvent.kt
- kotlin-react-dom/src/main/generated/react/dom/TransitionEvent.kt
- kotlin-react-dom/src/main/generated/react/dom/UIEvent.kt
- kotlin-react-dom/src/main/generated/react/dom/WheelEvent.kt
> React events [generated]

- kotlin-react-dom/src/main/generated/react/dom/NativeEvents.kt
> Fix native event aliases

- kotlin-react-table/build.gradle.kts
- kotlin-react-table/src/main/kotlin/react/table/Table.kt
> `react-table`. Use valid event handler

- kotlin-react-dom/src/main/generated/react/dom/AriaAttributes.kt
> React `AriaAttributes` [generated]

- gradle.properties
- kotlin-react-query/src/main/generated/react/query/QueryClientProvider.kt
- kotlin-react-query/src/main/generated/react/query/QueryErrorResetBoundary.kt
- kotlin-react-query/src/main/generated/react/query/Tuple.kt
- kotlin-react-query/src/main/generated/react/query/aliases.kt
- kotlin-react-query/src/main/generated/react/query/queryClient.core.kt
- kotlin-react-query/src/main/generated/react/query/useIsMutating.kt
- kotlin-react-query/src/main/generated/react/query/utils.core.kt
> React Query `3.19.6` [generated]

- kotlin-react-dom/src/main/generated/react/dom/PointerEvent.kt
- kotlin-react-dom/src/main/generated/react/dom/PointerType.kt
> React `PointerType` [generated]

- kotlin-styled-next/src/test/kotlin/TestUtils.kt
- kotlin-styled-next/src/test/kotlin/test/AtRulesTest.kt
- kotlin-styled-next/src/test/kotlin/test/ElementTest.kt
- kotlin-styled-next/src/test/kotlin/test/FunctionsTest.kt
- kotlin-styled-next/src/test/kotlin/test/PseudoClassRulesTest.kt
- kotlin-styled-next/src/test/kotlin/test/PseudoElementsTest.kt
- kotlin-styled-next/src/test/kotlin/test/RelativeSelectorsTest.kt
- kotlin-styled-next/src/test/kotlin/test/StyleSheetTest.kt
> `Props` for `styled-next` tests

- kotlin-react/README.md
> `Props` in `react` README

- kotlin-react-dom/src/main/kotlin/react/dom/EventHandlerAdapters.kt
> Add `EventHandler` adapters

- kotlin-react-dom/src/main/generated/react/dom/ButtonHTMLAttributes.kt
- kotlin-react-dom/src/main/generated/react/dom/ButtonType.kt
- kotlin-react-dom/src/main/generated/react/dom/EnterKeyHint.kt
- kotlin-react-dom/src/main/generated/react/dom/HTMLAttributes.kt
- kotlin-react-dom/src/main/generated/react/dom/IframeHTMLAttributes.kt
- kotlin-react-dom/src/main/generated/react/dom/IframeLoading.kt
- kotlin-react-dom/src/main/generated/react/dom/ImgCrossOrigin.kt
- kotlin-react-dom/src/main/generated/react/dom/ImgDecoding.kt
- kotlin-react-dom/src/main/generated/react/dom/ImgHTMLAttributes.kt
- kotlin-react-dom/src/main/generated/react/dom/ImgLoading.kt
- kotlin-react-dom/src/main/generated/react/dom/InputHTMLAttributes.kt
- kotlin-react-dom/src/main/generated/react/dom/InputMode.kt
- kotlin-react-dom/src/main/generated/react/dom/OlHTMLAttributes.kt
- kotlin-react-dom/src/main/generated/react/dom/OlType.kt
- kotlin-react-dom/src/main/generated/react/dom/TdAlign.kt
- kotlin-react-dom/src/main/generated/react/dom/TdHTMLAttributes.kt
- kotlin-react-dom/src/main/generated/react/dom/TdVAlign.kt
- kotlin-react-dom/src/main/generated/react/dom/ThAlign.kt
- kotlin-react-dom/src/main/generated/react/dom/ThHTMLAttributes.kt
- kotlin-react-dom/src/main/generated/react/dom/Translate.kt
- kotlin-react-dom/src/main/generated/react/dom/Unselectable.kt
- kotlin-react-dom/src/main/kotlin/react/dom/ReactDOMTags.kt
`InputType` union isn't declared in React types! :)
> React HTML unions [generated]

- examples/src/main/kotlin/example/AxiosSearch.kt
- examples/src/main/kotlin/example/Product.kt
- examples/src/main/kotlin/example/Quill.kt
- examples/src/main/kotlin/example/ReactRouterDom.kt
- examples/src/main/kotlin/example/TicTacToe.kt
- examples/src/main/kotlin/example/Todo.kt
- examples/src/main/kotlin/example/main.kt
> `RProps` is removed from examples

- kotlin-react-virtual/gradle.properties
> Add React Virtual publish description

- README.md
- kotlin-react-redux/README.md
- kotlin-react-router-dom/README.md
- kotlin-react/README.md
- kotlin-react/src/main/kotlin/react/ComponentClass.kt
> `RProps` and `RState` are removed from MD and comments

- gradle.properties
* Remove redundant comments
* Group properties
> Cleanup `gradle.properties`

- kotlin-react-virtual/src/main/kotlin/react/virtual/RangeExtractor.kt
- kotlin-react-virtual/src/main/kotlin/react/virtual/ScrollOptions.kt
- kotlin-react-virtual/src/main/kotlin/react/virtual/ScrollToOptions.kt
- kotlin-react-virtual/src/main/kotlin/react/virtual/Size.kt
- kotlin-react-virtual/src/main/kotlin/react/virtual/VirtualItem.kt
- kotlin-react-virtual/src/main/kotlin/react/virtual/useVirtual.kt
> Fix React Virtual signatures

- examples/src/main/kotlin/example/main.kt
- kotlin-react-dom/src/main/generated/react/dom/InputHTMLAttributes.kt
- kotlin-react-dom/src/main/generated/react/dom/InputType.kt
- kotlin-react-dom/src/main/kotlin/react/dom/ReactDOMTags.kt
> React `InputType` union [generated]

- gradle.properties
- kotlin-react-query/src/main/generated/react/query/queryClient.core.kt
- kotlin-react-query/src/main/generated/react/query/queryObserver.core.kt
- kotlin-react-query/src/main/generated/react/query/types.core.kt
> React Query 3.21.0

- kotlin-react-dom/src/main/generated/react/dom/ReactHTML.kt
> React HTML intrinsic types [generated]

- README.md
- gradle.properties
> Kotlin `1.5.30`

- README.md
- kotlin-wrappers-bom/README.md
> Correct version in snippets

- kotlin-react/src/main/kotlin/react/Props.kt
- kotlin-react/src/main/kotlin/react/PropsWithChildren.kt
- kotlin-react/src/main/kotlin/react/RProps.kt
> Separate `Props`

- buildSrc/src/main/kotlin/Dependencies.kt
- buildSrc/src/main/kotlin/Projects.kt
- gradle.properties
- kotlin-ring-ui/build.gradle.kts
- kotlin-styled-next/build.gradle.kts
- kotlin-styled/build.gradle.kts
> NPM versions in `gradle.properties`

- kotlin-styled-next/build.gradle.kts
cc @sgrishchenko @aerialist7 @tretikoff
> Standard `dependencies` section

- kotlin-react-dom/src/main/generated/react/dom/AbstractView.kt
- kotlin-react-dom/src/main/generated/react/dom/DOMAttributes.kt
- kotlin-react-dom/src/main/generated/react/dom/DangerouslySetInnerHTML.kt
- kotlin-react-dom/src/main/generated/react/dom/StyleMedia.kt
- kotlin-react-dom/src/main/generated/react/dom/UIEvent.kt
> React `dangerouslySetInnerHTML` [generated]

- kotlin-css/src/commonMain/kotlin/kotlinx/css/StyleEnums.kt
- kotlin-css/src/commonMain/kotlin/kotlinx/css/StyledElement.kt
- kotlin-css/src/commonMain/kotlin/kotlinx/css/properties/Gradient.kt
- kotlin-css/src/commonTest/kotlin/kotlinx/css/TestGradient.kt
- kotlin-css/src/commonTest/kotlin/kotlinx/css/TestRelativePosition.kt
Added DSL for RelativePosition (a.k.a. value for background-position)
Added DSL for linear-gradient, radial-gradient, repeating-linear-gradient, and repeating-radial-gradient
> Gradients support

- kotlin-ring-ui/src/main/kotlin/ringui/Alert.kt
- kotlin-ring-ui/src/main/kotlin/ringui/Button.kt
- kotlin-ring-ui/src/main/kotlin/ringui/ButtonGroup.kt
- kotlin-ring-ui/src/main/kotlin/ringui/Checkbox.kt
- kotlin-ring-ui/src/main/kotlin/ringui/Dialog.kt
- kotlin-ring-ui/src/main/kotlin/ringui/Dropdown.kt
- kotlin-ring-ui/src/main/kotlin/ringui/Footer.kt
- kotlin-ring-ui/src/main/kotlin/ringui/Grid.kt
- kotlin-ring-ui/src/main/kotlin/ringui/Header.kt
- kotlin-ring-ui/src/main/kotlin/ringui/Heading.kt
- kotlin-ring-ui/src/main/kotlin/ringui/Icon.kt
- kotlin-ring-ui/src/main/kotlin/ringui/Input.kt
- kotlin-ring-ui/src/main/kotlin/ringui/Island.kt
- kotlin-ring-ui/src/main/kotlin/ringui/Link.kt
- kotlin-ring-ui/src/main/kotlin/ringui/Tabs.kt
- kotlin-ring-ui/src/main/kotlin/ringui/UserCard.kt
> Ring UI: No more useless `WithClassName`

- examples/src/main/kotlin/example/AxiosSearch.kt
- examples/src/main/kotlin/example/main.kt
- kotlin-extensions/src/main/kotlin/kotlinext/js/Helpers.kt
- kotlin-extensions/src/main/kotlin/kotlinext/js/Record.kt
- kotlin-react-dom/src/main/kotlin/react/dom/RDOMBuilder.kt
- kotlin-react-router-dom/src/main/kotlin/react/router/dom/hooks.kt
- kotlin-react-router-dom/src/main/kotlin/react/router/dom/routingDsl.kt
- kotlin-react-table/src/main/kotlin/react/table/Columns.kt
- kotlin-react-virtual/src/main/kotlin/react/virtual/Size.kt
- kotlin-react/src/main/kotlin/react/RBuilder.kt
- kotlin-react/src/main/kotlin/react/RComponent.kt
- kotlin-react/src/main/kotlin/react/RPureComponent.kt
- kotlin-react/src/main/kotlin/react/React.kt
- kotlin-react/src/main/kotlin/react/SuspenseConfig.kt
- kotlin-styled-next/src/main/kotlin/styled/StyledComponents.kt
- kotlin-styled-next/src/test/kotlin/TestUtils.kt
- kotlin-styled/src/main/kotlin/styled/StyledComponents.kt
> `jsObject` deprecation in favour of `jso`

- kotlin-react-dom/src/main/kotlin/react/dom/RDOMBuilder.kt
- kotlin-ring-ui/src/main/kotlin/ringui/Dropdown.kt
> Sync props order

- examples/src/main/kotlin/example/ReactRouterDom.kt
- kotlin-extensions/src/main/kotlin/kotlinext/js/Record.kt
> `Record` operators inside `Record`

- kotlin-react/src/main/kotlin/react/Raw.kt
> Use `Cleanup`

- kotlin-react-router-dom/src/main/kotlin/react/router/dom/imports.kt
- kotlin-react-router-dom/src/main/kotlin/react/router/dom/matchPath.ext.kt
- kotlin-react-router-dom/src/main/kotlin/react/router/dom/matchPath.kt
- kotlin-react-router-dom/src/main/kotlin/react/router/dom/routingDsl.kt
> React Router DOM: `matchPath` separation

- kotlin-react-router-dom/src/main/kotlin/react/router/dom/HashType.kt
- kotlin-react-router-dom/src/main/kotlin/react/router/dom/routingDsl.kt
> React Router DOM: `HashType` separation

- kotlin-react-router-dom/src/main/kotlin/react/router/dom/RouterProps.kt
> Remove redundant annotations

- kotlin-react-router-dom/src/main/kotlin/react/router/dom/MatchOptions.kt
- kotlin-react-router-dom/src/main/kotlin/react/router/dom/matchPath.ext.kt
- kotlin-react-router-dom/src/main/kotlin/react/router/dom/matchPath.kt
- kotlin-react-router-dom/src/main/kotlin/react/router/dom/useRouteMatch.ext.kt
- kotlin-react-router-dom/src/main/kotlin/react/router/dom/useRouteMatch.kt
> React Router DOM: `MatchOptions`

- kotlin-react-router-dom/src/main/kotlin/react/router/dom/Link.kt
- kotlin-react-router-dom/src/main/kotlin/react/router/dom/Redirect.kt
- kotlin-react-router-dom/src/main/kotlin/react/router/dom/Route.kt
- kotlin-react-router-dom/src/main/kotlin/react/router/dom/StaticContext.kt
- kotlin-react-router-dom/src/main/kotlin/react/router/dom/routingDsl.kt
> React Router DOM: `Props` improvements

- examples/src/main/kotlin/example/ReactRouterDom.kt
- kotlin-react-router-dom/src/main/kotlin/react/router/dom/matchPath.ext.kt
- kotlin-react-router-dom/src/main/kotlin/react/router/dom/matchPath.kt
- kotlin-react-router-dom/src/main/kotlin/react/router/dom/useRouteMatch.ext.kt
- kotlin-react-router-dom/src/main/kotlin/react/router/dom/useRouteMatch.kt
> Router: "raw" prefix is removed for low-level wrappers

- examples/src/main/kotlin/example/ReactRouterDom.kt
- kotlin-react-router-dom/src/main/kotlin/react/router/dom/routingDsl.legacy.kt
> React Router DOM: `routingDsl.kt` -> `routingDsl.legacy.kt`

- kotlin-react-router-dom/src/main/kotlin/react/router/dom/MatchOptions.kt
- kotlin-react-router-dom/src/main/kotlin/react/router/dom/Route.kt
- kotlin-react-router-dom/src/main/kotlin/react/router/dom/matchPath.ext.kt
- kotlin-react-router-dom/src/main/kotlin/react/router/dom/matchPath.kt
- kotlin-react-router-dom/src/main/kotlin/react/router/dom/useRouteMatch.ext.kt
- kotlin-react-router-dom/src/main/kotlin/react/router/dom/useRouteMatch.kt
> Builder pattern is used for `useRouteMatch` and `matchPath`

- kotlin-react-router-dom/src/main/kotlin/react/router/dom/Route.kt
- kotlin-react-router-dom/src/main/kotlin/react/router/dom/routingDsl.legacy.kt
> Children are provided for RouteProps, render prop is deprecated

- kotlin-react/src/main/kotlin/react/FunctionStateInstance.kt
- kotlin-react/src/main/kotlin/react/useFunctionState.kt
[Problem details](https://medium.com/swlh/how-to-store-a-function-with-the-usestate-hook-in-react-8a88dd4eede1)
> Add `useFunctionState` hook

- kotlin-react-dom/src/main/generated/react/dom/AriaAttributes.kt
[Broken `inline` in IR](https://youtrack.jetbrains.com/issue/KT-48154)
> IR workaround for `AriaAttributes` [generated]

- kotlin-react/src/main/kotlin/react/RefCallback.kt
[Related discussion](https://kotlinlang.slack.com/archives/C0B8L3U69/p1630587549109700?thread_ts=1630574954.108000&cid=C0B8L3U69)
> Fix `useRefCallback` type parameter

- kotlin-react/src/main/kotlin/react/useRefState.kt
[Example](https://popper.js.org/react-popper/v2/#example)
> Add `useRefState` hook

- kotlin-react/src/main/kotlin/react/useFunctionState.kt
> Add missed `@JsNonModule`

- kotlin-react/src/main/kotlin/react/CSSProperties.kt
[Original](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/4c9d380e420054c3b862e85b20c68f13fb380b93/types/react/index.d.ts#L1550)
> Add react `CSSProperties`

- kotlin-react/src/main/kotlin/react/RBuilder.kt
> Add void component support

- kotlin-react-redux/src/main/kotlin/react/redux/Dsl.kt
- kotlin-react-redux/src/main/kotlin/react/redux/Imports.kt
> Fix `react-redux` `Provider` declaration

- kotlin-styled-next/src/main/kotlin/styled/StyleSheet.kt
- kotlin-styled-next/src/test/kotlin/test/StyleSheetTest.kt
Fix bug with classname adding in stylesheets and add tests for non-tested functionality found while debugging
> Fix add classname in stylesheet and add some tests

- kotlin-react/build.gradle.kts
- kotlin-react/src/main/kotlin/react/CSSProperties.kt
> React `CSSProperties` - alias

- kotlin-react/src/main/kotlin/react/RBuilder.kt
> Fix void component support

- kotlin-react-dom/src/main/generated/react/dom/HTMLAttributes.kt
> Use `CSSProperties` [generated]

- kotlin-react-table/src/main/kotlin/react/table/Table.kt
> React Table. Use `CSSProperties`

- kotlin-react/src/main/kotlin/react/RBuilder.kt
> `withKey` extension is deprecated

- kotlin-react/src/main/kotlin/react/RBuilder.kt
> `renderEach` extension is deprecated

- kotlin-csstype/src/main/generated/csstype/StandardProperties.kt
- kotlin-csstype/src/main/generated/csstype/StandardShorthandProperties.kt
> CSSType. `StandardShorthandProperties` [generated]

- kotlin-csstype/src/main/generated/csstype/CounterStyle.kt
- kotlin-csstype/src/main/generated/csstype/FontFace.kt
- kotlin-csstype/src/main/generated/csstype/Page.kt
- kotlin-csstype/src/main/generated/csstype/Property.kt
- kotlin-csstype/src/main/generated/csstype/StandardLonghandProperties.kt
- kotlin-csstype/src/main/generated/csstype/StandardShorthandProperties.kt
- kotlin-csstype/src/main/generated/csstype/Viewport.kt
> CSSType. Optional properties [generated]

- kotlin-react-table/src/main/kotlin/react/table/Table.kt
> React Table. Optional `style` for table elements

- buildSrc/src/main/kotlin/Dependencies.kt
- gradle.properties
- kotlin-styled-next/build.gradle.kts
> Coroutines version in `gradle.properties`

- kotlin-css/gradle.properties
- kotlin-csstype/gradle.properties
- kotlin-extensions/gradle.properties
- kotlin-react-dom/gradle.properties
- kotlin-react-popper/gradle.properties
- kotlin-react-query/gradle.properties
- kotlin-react-redux/gradle.properties
- kotlin-react-router-dom/gradle.properties
- kotlin-react-table/gradle.properties
- kotlin-react-virtual/gradle.properties
- kotlin-react/gradle.properties
- kotlin-redux/gradle.properties
- kotlin-ring-ui/gradle.properties
- kotlin-styled-next/gradle.properties
- kotlin-styled/gradle.properties
- kotlin-wrappers-bom/gradle.properties
> Remove unused/invalid `author` property

- kotlin-csstype/src/main/generated/csstype/BackgroundColor.kt
- kotlin-csstype/src/main/generated/csstype/BorderBlockColor.kt
- kotlin-csstype/src/main/generated/csstype/BorderBlockEndColor.kt
- kotlin-csstype/src/main/generated/csstype/BorderBlockStartColor.kt
- kotlin-csstype/src/main/generated/csstype/BorderBottomColor.kt
- kotlin-csstype/src/main/generated/csstype/BorderColor.kt
- kotlin-csstype/src/main/generated/csstype/BorderInlineColor.kt
- kotlin-csstype/src/main/generated/csstype/BorderInlineEndColor.kt
- kotlin-csstype/src/main/generated/csstype/BorderInlineStartColor.kt
- kotlin-csstype/src/main/generated/csstype/BorderLeftColor.kt
- kotlin-csstype/src/main/generated/csstype/BorderRightColor.kt
- kotlin-csstype/src/main/generated/csstype/BorderTopColor.kt
- kotlin-csstype/src/main/generated/csstype/ColorProperty.kt
- kotlin-csstype/src/main/generated/csstype/ColumnRuleColor.kt
- kotlin-csstype/src/main/generated/csstype/StandardLonghandProperties.kt
- kotlin-csstype/src/main/generated/csstype/TextDecorationColor.kt
- kotlin-csstype/src/main/generated/csstype/TextEmphasisColor.kt
cc @aerialist7 
New formatting in `NamedColor` - IDEA 2021.2.2
> CSSType. `Color` -> `ColorProperty` [generated]

- kotlin-ring-ui/README.md
> Ring UI. Known problems section

- kotlin-csstype/src/main/generated/csstype/Paint.kt
> CSSType. Remove `Paint` [generated]

- README.md
- buildSrc/src/main/kotlin/Projects.kt
- gradle.properties
- kotlin-emotion/README.md
- kotlin-emotion/build.gradle.kts
- kotlin-emotion/gradle.properties
- kotlin-emotion/src/main/kotlin/emotion/css/css.kt
- kotlin-wrappers-bom/README.md
- kotlin-wrappers-bom/build.gradle.kts
- settings.gradle.kts
> `kotlin-emotion` library is wrapped

- kotlin-react-dom/src/main/generated/react/dom/DOMAttributes.kt
- kotlin-react-dom/src/main/generated/react/dom/HTMLAttributes.kt
> `PropsWithClassName` is supported in `DOMAttributes`

- kotlin-csstype/src/main/kotlin/csstype/Padding.ext.kt
> CSSType. `padding` extensions

- kotlin-csstype/src/main/kotlin/csstype/Margin.ext.kt
> CSSType. `margin` extensions

- kotlin-react-dom/src/main/generated/react/dom/AllHTMLAttributes.kt
- kotlin-react-dom/src/main/generated/react/dom/Capture.kt
- kotlin-react-dom/src/main/generated/react/dom/InputHTMLAttributes.kt
> React. `Capture` [generated]

- kotlin-csstype/src/main/generated/csstype/Border.kt
- kotlin-csstype/src/main/generated/csstype/ColorProperty.kt
- kotlin-csstype/src/main/generated/csstype/LineStyleProperty.kt
- kotlin-csstype/src/main/generated/csstype/LineWidthProperty.kt
> CSSType. `Border` child types [generated]

- kotlin-react-css/build.gradle.kts
> React CSS. Fix dependency configuration

- kotlin-react-dom/src/main/kotlin/react/dom/ReactDOM.kt
- kotlin-react-dom/src/main/kotlin/react/dom/server/ReactDOMServer.kt
- kotlin-react/src/main/kotlin/react/Context.kt
- kotlin-react/src/main/kotlin/react/FunctionComponent.kt
- kotlin-react/src/main/kotlin/react/HOC.kt
- kotlin-react/src/main/kotlin/react/RBuilder.kt
- kotlin-react/src/main/kotlin/react/RComponent.kt
- kotlin-react/src/main/kotlin/react/RPureComponent.kt
- kotlin-react/src/main/kotlin/react/React.kt
- kotlin-react/src/main/kotlin/react/ReactElement.ext.kt
- kotlin-react/src/main/kotlin/react/forwardRef.kt
New signature of `createElement` is introduced, deprecation for old implementation is added.
cc @turansky @aerialist7
> New signature of `createElement` is introduced

- gradle.properties
> MUI `5.0.6`

- kotlin-csstype/src/main/kotlin/csstype/Length.ext.kt
> CSSType. `Length` extensions

- kotlin-react/src/main/kotlin/react/RBuilder.kt
> React. Inline private `child` method

- gradle.properties
> Emotion CSS `11.5.0`

- kotlin-react-dom/src/main/kotlin/react/dom/RDOMBuilder.kt
- kotlin-react-dom/src/main/kotlin/react/dom/html/HTMLAttributes.ext.kt
- kotlin-react/src/main/kotlin/react/Props.kt
- kotlin-react/src/main/kotlin/react/RBuilder.kt
> React. Optional `key`and `ref`

- kotlin-mui/src/main/generated/mui/material/Stubs.kt
- kotlin-mui/src/main/generated/mui/material/TablePaginationActions.kt
> MUI. `TablePaginationActions` [generated]

- kotlin-csstype/src/main/kotlin/csstype/Border.ext.kt
> CSSType. `Border` factory methods

- kotlin-react/src/main/kotlin/react/Context.legacy.kt
> Remove empty file

- kotlin-popper/src/main/kotlin/popper/core/Modifier.kt
- kotlin-popper/src/main/kotlin/popper/core/Placement.kt
- kotlin-popper/src/main/kotlin/popper/core/PopperOptions.kt
- kotlin-popper/src/main/kotlin/popper/core/PositioningStrategy.kt
- kotlin-popper/src/main/kotlin/popper/core/State.kt
- kotlin-popper/src/main/kotlin/popper/core/Update.kt
- kotlin-react-popper/src/main/kotlin/react/popper/Popper.kt
- kotlin-react-popper/src/main/kotlin/react/popper/PopperInstance.kt
- kotlin-react-popper/src/main/kotlin/react/popper/usePopper.kt
> Popper. Default package - `popper.core`

- kotlin-popper/src/main/generated/popper/core/Instance.kt
- kotlin-popper/src/main/generated/popper/core/OffsetData.kt
- kotlin-popper/src/main/generated/popper/core/Options.kt
- kotlin-popper/src/main/generated/popper/core/OptionsGeneric.kt
- kotlin-popper/src/main/generated/popper/core/Padding.kt
- kotlin-popper/src/main/generated/popper/core/SetAction.kt
- kotlin-popper/src/main/generated/popper/core/State.kt
- kotlin-popper/src/main/generated/popper/core/UpdateCallback.kt
- kotlin-popper/src/main/generated/popper/core/VisualViewport.kt
> Popper. Base types [generated]

- examples/src/main/kotlin/example/ForwardingRefs.kt
- kotlin-react/src/main/kotlin/react/Raw.kt
- kotlin-react/src/main/kotlin/react/forwardRef.kt
- kotlin-react/src/main/kotlin/react/useImperativeHandle.kt
> `useImperativeHandle` hook is refactored

- kotlin-popper/src/main/generated/popper/core/Name.kt
- kotlin-popper/src/main/generated/popper/core/Popper.kt
- kotlin-popper/src/main/generated/popper/core/modifiers/ApplyStyles.kt
- kotlin-popper/src/main/generated/popper/core/modifiers/Arrow.kt
- kotlin-popper/src/main/generated/popper/core/modifiers/ComputeStyles.kt
- kotlin-popper/src/main/generated/popper/core/modifiers/EventListeners.kt
- kotlin-popper/src/main/generated/popper/core/modifiers/Flip.kt
- kotlin-popper/src/main/generated/popper/core/modifiers/Hide.kt
- kotlin-popper/src/main/generated/popper/core/modifiers/Offset.kt
- kotlin-popper/src/main/generated/popper/core/modifiers/PopperOffsets.kt
- kotlin-popper/src/main/generated/popper/core/modifiers/PreventOverflow.kt
- kotlin-react-popper/src/main/kotlin/react/popper/PopperInstance.kt
> Popper. Standard modifiers [generated]

- kotlin-react/src/main/kotlin/react/Context.kt
- kotlin-react/src/main/kotlin/react/Fragment.kt
- kotlin-react/src/main/kotlin/react/Profiler.kt
- kotlin-react/src/main/kotlin/react/StrictMode.kt
- kotlin-react/src/main/kotlin/react/Suspense.kt
> Reduce usages of `ComponentClass` in react core

- kotlin-react/src/main/kotlin/react/ReactElement.kt
[Source](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8c1be4ffc05700080f82109a62909a44ab2ed5b3/types/react/index.d.ts#L146)
> React. Add missed `ReactElement` properties

- kotlin-react-dom/src/main/kotlin/react/dom/ReactDOM.kt
- kotlin-react-dom/src/main/kotlin/react/dom/createRoot.kt
[Example](https://codesandbox.io/s/stupefied-bohr-gye80?file=/src/index.js)
> React DOM. Sync `createRoot` naming/contract

- kotlin-react-dom/src/main/kotlin/react/dom/ReactDOM.kt
- kotlin-react-dom/src/main/kotlin/react/dom/createPortal.kt
- kotlin-react-dom/src/main/kotlin/react/dom/hydrate.kt
- kotlin-react-dom/src/main/kotlin/react/dom/render.kt
[Test](https://codesandbox.io/s/sharp-babbage-hb865?file=/src/index.js)
> React DOM. Required container (fix contract)

- kotlin-react-dom/src/main/kotlin/react/dom/ReactDOM.kt
- kotlin-react-dom/src/main/kotlin/react/dom/createPortal.kt
- kotlin-react/src/main/kotlin/react/ReactPortal.kt
[Source](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f9851f4dc4184a861df363e0e84082199dbb17df/types/react/index.d.ts#L190)
> React. Add missed `ReactPortal`

- kotlin-react-dom/src/main/kotlin/react/dom/Root.kt
- kotlin-react-dom/src/main/kotlin/react/dom/createRoot.kt
> React DOM. `Root` - common interface

- kotlin-react/src/main/kotlin/react/FunctionComponent.kt
[Details](https://kotlinlang.slack.com/archives/C5ZTZ6ER0/p1637961054032000)
Related - #969
> Non-sealed `FC`

- gradle.properties
> Parallel Gradle build

- kotlin-react-dom/src/main/kotlin/react/dom/createPortal.ext.kt
- kotlin-react-dom/src/main/kotlin/react/dom/createPortal.kt
[Source](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ec0baa41fdb27cd0e50c4d6e995bad81ea7ad96b/types/react-dom/index.d.ts#L32)
> React DOM. Strict `createPortal` signature

- kotlin-extensions/src/main/kotlin/kotlinext/js/Helpers.kt
- kotlin-extensions/src/main/kotlin/kotlinext/js/jsObject.kt
> Deprecate `jsObject`

- gradle.properties
- kotlin-mui/src/main/generated/mui/material/CssBaseline.kt
- kotlin-mui/src/main/generated/mui/material/MenuList.kt
- kotlin-mui/src/main/generated/mui/material/ScopedCssBaseline.kt
- kotlin-mui/src/main/generated/mui/material/Snackbar.ext.kt
- kotlin-mui/src/main/generated/mui/material/Snackbar.kt
> MUI `5.2.2` [generated]

- gradle.properties
- kotlin-react-query/src/main/generated/react/query/mutation.core.kt
- kotlin-react-query/src/main/generated/react/query/queryObserver.core.kt
- kotlin-react-query/src/main/generated/react/query/retryer.core.kt
- kotlin-react-query/src/main/generated/react/query/types.core.kt
- kotlin-react-query/src/main/generated/react/query/types.kt
> React Query `3.33.7` [generated]

- gradle.properties
- kotlin-react-query/src/main/generated/react/query/mutationCache.core.kt
> React Query `3.34.0` [generated]

- examples/src/main/kotlin/example/ForwardingRefs.kt
- kotlin-react/src/main/kotlin/react/PropsWithRef.kt
- kotlin-react/src/main/kotlin/react/Raw.kt
- kotlin-react/src/main/kotlin/react/forwardRef.kt
- kotlin-styled-next/src/main/kotlin/styled/StyledComponents.kt
cc @turansky @aerialist7 @tretikoff
> `PropsWithRef` is introduced and is used for more strict ref forwarding

- kotlin-mui/src/main/generated/mui/material/Fade.kt
- kotlin-mui/src/main/generated/mui/material/Grow.kt
- kotlin-mui/src/main/generated/mui/material/Slide.kt
- kotlin-mui/src/main/generated/mui/material/TextField.kt
- kotlin-mui/src/main/generated/mui/material/Zoom.kt
> MUI. `TextFieldProps` - typealias [generated]

- kotlin-react/src/main/kotlin/react/Ref.kt
- kotlin-react/src/main/kotlin/react/RefCallback.kt
- kotlin-react/src/main/kotlin/react/useRef.kt
> React. Covariance for `RefObject`

- kotlin-mui/src/main/generated/mui/lab/LoadingButton.kt
> MUI. Fix `LoadingButtonProps` parent type [generated]

- kotlin-mui/src/main/generated/mui/base/useAutocomplete.ext.kt
- kotlin-mui/src/main/generated/mui/base/useAutocomplete.kt
> MUI. `useAutocomplete` types [generated]

- kotlin-mui/src/main/generated/mui/base/ClickAwayListener.kt
- kotlin-mui/src/main/generated/mui/base/useAutocomplete.kt
- kotlin-mui/src/main/generated/mui/lab/ClockPicker.kt
- kotlin-mui/src/main/generated/mui/material/Autocomplete.kt
- kotlin-mui/src/main/generated/mui/material/Pagination.kt
- kotlin-mui/src/main/generated/mui/material/Snackbar.kt
- kotlin-mui/src/main/generated/mui/material/TablePagination.kt
- kotlin-mui/src/main/generated/mui/material/TablePaginationActions.kt
> MUI. Function types [generated]

- kotlin-react-dom/src/main/generated/react/dom/DOMAttributes.kt
- kotlin-react-dom/src/main/generated/react/dom/html/InputHTMLAttributes.kt
- kotlin-react-dom/src/main/generated/react/dom/html/SelectHTMLAttributes.kt
- kotlin-react-dom/src/main/generated/react/dom/html/TextareaHTMLAttributes.kt
Related - #985 
cc @aerialist7
> React. `DOMAttributes.onChange` - extension [generated]

- kotlin-react-dom/src/main/generated/react/dom/svg/ReactSVG.kt
> React. Missed SVG types [generated]

- kotlin-react-dom/src/main/generated/react/dom/events/AnimationEvent.kt
- kotlin-react-dom/src/main/generated/react/dom/events/BaseSyntheticEvent.kt
- kotlin-react-dom/src/main/generated/react/dom/events/ChangeEvent.kt
- kotlin-react-dom/src/main/generated/react/dom/events/ClipboardEvent.kt
- kotlin-react-dom/src/main/generated/react/dom/events/CompositionEvent.kt
- kotlin-react-dom/src/main/generated/react/dom/events/DragEvent.kt
- kotlin-react-dom/src/main/generated/react/dom/events/FocusEvent.kt
- kotlin-react-dom/src/main/generated/react/dom/events/FormEvent.kt
- kotlin-react-dom/src/main/generated/react/dom/events/InvalidEvent.kt
- kotlin-react-dom/src/main/generated/react/dom/events/KeyboardEvent.kt
- kotlin-react-dom/src/main/generated/react/dom/events/MouseEvent.kt
- kotlin-react-dom/src/main/generated/react/dom/events/PointerEvent.kt
- kotlin-react-dom/src/main/generated/react/dom/events/SyntheticEvent.kt
- kotlin-react-dom/src/main/generated/react/dom/events/TouchEvent.kt
- kotlin-react-dom/src/main/generated/react/dom/events/TransitionEvent.kt
- kotlin-react-dom/src/main/generated/react/dom/events/UIEvent.kt
- kotlin-react-dom/src/main/generated/react/dom/events/WheelEvent.kt
> React. Strict `Event` type parameters [generated]

- examples/src/main/kotlin/example/ForwardingRefs.kt
- kotlin-css/src/commonMain/kotlin/kotlinx/css/CssBuilder.kt
- kotlin-react/src/main/kotlin/react/useImperativeHandle.kt
- kotlin-ring-ui/src/main/kotlin/ringui/AlertService.kt
- kotlin-styled-next/src/main/kotlin/styled/StructEffects.kt
- kotlin-styled-next/src/main/kotlin/styled/StyleSheet.kt
- kotlin-styled-next/src/main/kotlin/styled/StyledComponents.kt
- kotlin-styled-next/src/main/kotlin/styled/StyledTags.kt
- kotlin-styled-next/src/main/kotlin/styled/sheets/CSSOMSheet.kt
- kotlin-styled-next/src/test/kotlin/benchmark/BenchmarkBase.kt
- kotlin-styled-next/src/test/kotlin/test/TestBase.kt
> Fix formatting

- kotlin-mui/src/main/generated/mui/system/Breakpoint.kt
- kotlin-mui/src/main/generated/mui/system/Stubs.kt
- kotlin-mui/src/main/generated/mui/system/createBreakpoints.kt
- kotlin-mui/src/main/generated/mui/system/createSpacing.kt
- kotlin-mui/src/main/generated/mui/system/createTheme.ext.kt
- kotlin-mui/src/main/generated/mui/system/createTheme.kt
- kotlin-mui/src/main/generated/mui/system/shape.kt
> MUI. `Theme` [generated]

- gradle.properties
- kotlin-mui/src/main/generated/mui/lab/StaticDatePicker.kt
- kotlin-mui/src/main/generated/mui/lab/StaticDateRangePicker.kt
- kotlin-mui/src/main/generated/mui/lab/StaticDateTimePicker.kt
- kotlin-mui/src/main/generated/mui/lab/StaticTimePicker.kt
- kotlin-mui/src/main/generated/mui/lab/TreeItem.kt
- kotlin-mui/src/main/generated/mui/material/Accordion.kt
- kotlin-mui/src/main/generated/mui/material/AvatarGroup.kt
- kotlin-mui/src/main/generated/mui/material/ButtonBase.kt
- kotlin-mui/src/main/generated/mui/material/Collapse.kt
- kotlin-mui/src/main/generated/mui/material/Dialog.kt
- kotlin-mui/src/main/generated/mui/material/Fade.kt
- kotlin-mui/src/main/generated/mui/material/Grow.kt
- kotlin-mui/src/main/generated/mui/material/Menu.kt
- kotlin-mui/src/main/generated/mui/material/Popover.kt
- kotlin-mui/src/main/generated/mui/material/Slide.kt
- kotlin-mui/src/main/generated/mui/material/Snackbar.kt
- kotlin-mui/src/main/generated/mui/material/SpeedDial.kt
- kotlin-mui/src/main/generated/mui/material/StepContent.kt
- kotlin-mui/src/main/generated/mui/material/Tooltip.kt
- kotlin-mui/src/main/generated/mui/material/Zoom.kt
> MUI `5.2.3` [generated]

- kotlin-react/src/main/kotlin/react/Component.kt
> `dynamic` is removed from `Component`

- kotlin-react/src/main/kotlin/react/React.kt
- kotlin-react/src/main/kotlin/react/Suspense.ext.kt
- kotlin-react/src/main/kotlin/react/Suspense.kt
> `SuspenseProps` extension is moved to separate file

- kotlin-react/src/main/kotlin/react/RBuilder.kt
> `buildElement` is deprecated

- kotlin-react/src/main/kotlin/react/ChildrenBuilder.kt
- kotlin-react/src/main/kotlin/react/FC.ext.kt
- kotlin-react/src/main/kotlin/react/create.kt
- kotlin-react/src/main/kotlin/react/createElementOrNull.kt
Related - #1000
cc @aerialist7
> React. `ChildrenBuilder`

- kotlin-mui/src/main/generated/mui/material/Autocomplete.kt
- kotlin-mui/src/main/generated/mui/material/Pagination.kt
> MUI. `Params` like `Props` [generated]

- gradle.properties
- kotlin-react-router-dom/src/main/generated/react/router/Navigator.kt
- kotlin-react-router-dom/src/main/generated/react/router/OutletProps.kt
- kotlin-react-router-dom/src/main/generated/react/router/dom/HistoryRouter.kt
- kotlin-react-router-dom/src/main/generated/react/router/dom/HistoryRouterProps.kt
- kotlin-react-router-dom/src/main/generated/react/router/matchPath.kt
- kotlin-react-router-dom/src/main/generated/react/router/useMatch.kt
- kotlin-react-router-dom/src/main/generated/react/router/useOutlet.kt
- kotlin-react-router-dom/src/main/generated/react/router/useOutletContext.kt
> React Router `6.1.0` [generated]

- gradle.properties
- kotlin-react-router-dom/src/main/generated/react/router/dom/BrowserRouter.kt
- kotlin-react-router-dom/src/main/generated/react/router/dom/HashRouter.kt
- kotlin-react-router-dom/src/main/generated/react/router/dom/HistoryRouter.kt
> React Router `6.1.1` [generated]

- kotlin-mui/src/main/generated/mui/material/styles/ThemeProvider.kt
- kotlin-mui/src/main/generated/mui/material/styles/createTheme.kt
- kotlin-mui/src/main/generated/mui/material/styles/zIndex.kt
> MUI. `ThemeProvider` [generated]

- kotlin-react-core/src/main/kotlin/react/useDeferredValue.kt
[Typings](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/46d4de0aeadaa63c82c069bbf6a8049bb0cd9968/types/react/next.d.ts#L71)
> React. `useDeferredValue`

- kotlin-react-core/src/main/kotlin/react/useSyncExternalStore.kt
[Typings](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/46d4de0aeadaa63c82c069bbf6a8049bb0cd9968/types/react/next.d.ts#L135)
> React. `useSyncExternalStore`

- CHANGELOG.md
> CHANGELOG.md is added

- gradle.properties
- kotlin-mui/src/main/generated/mui/material/GlobalStyles.kt
- kotlin-mui/src/main/generated/mui/material/InputBase.kt
- kotlin-mui/src/main/generated/mui/system/createBreakpoints.kt
> MUI `5.2.4` [generated]

- gradle.properties
- kotlin-mui/src/main/generated/mui/lab/ClockPicker.kt
- kotlin-mui/src/main/generated/mui/lab/LoadingButton.kt
> MUI `5.2.5` [generated]

- kotlin-extensions/src/main/kotlin/kotlinext/js/Symbol.kt
> Symbol declarations are upgraded

- gradle.properties
- kotlin-mui/src/main/generated/mui/material/Badge.kt
- kotlin-mui/src/main/generated/mui/material/Slider.kt
> MUI `5.2.6` [generated]

- kotlin-mui/src/main/generated/mui/material/Autocomplete.kt
- kotlin-mui/src/main/generated/mui/material/Button.kt
- kotlin-mui/src/main/generated/mui/material/ButtonGroup.kt
- kotlin-mui/src/main/generated/mui/material/Checkbox.kt
- kotlin-mui/src/main/generated/mui/material/Chip.kt
- kotlin-mui/src/main/generated/mui/material/Fab.kt
- kotlin-mui/src/main/generated/mui/material/FormControl.kt
- kotlin-mui/src/main/generated/mui/material/IconButton.kt
- kotlin-mui/src/main/generated/mui/material/InputBase.kt
- kotlin-mui/src/main/generated/mui/material/Pagination.kt
- kotlin-mui/src/main/generated/mui/material/PaginationItem.kt
- kotlin-mui/src/main/generated/mui/material/Radio.kt
- kotlin-mui/src/main/generated/mui/material/Rating.kt
- kotlin-mui/src/main/generated/mui/material/Size.kt
- kotlin-mui/src/main/generated/mui/material/Slider.kt
- kotlin-mui/src/main/generated/mui/material/Switch.kt
- kotlin-mui/src/main/generated/mui/material/Table.kt
- kotlin-mui/src/main/generated/mui/material/TableCell.kt
- kotlin-mui/src/main/generated/mui/material/TextField.kt
- kotlin-mui/src/main/generated/mui/material/ToggleButton.kt
- kotlin-mui/src/main/generated/mui/material/ToggleButtonGroup.kt
> MUI. `Size` [generated]

- kotlin-mui/src/main/generated/mui/material/Alert.kt
> MUI. Use `AlertColor` [generated]

- kotlin-mui/src/main/generated/mui/material/AppBar.kt
- kotlin-mui/src/main/generated/mui/material/Fab.kt
> MUI. CSS `Color` [generated]

- kotlin-mui/src/main/generated/mui/material/Icon.ext.kt
- kotlin-mui/src/main/generated/mui/material/Icon.kt
- kotlin-mui/src/main/generated/mui/material/SvgIcon.ext.kt
- kotlin-mui/src/main/generated/mui/material/SvgIcon.kt
> MUI. Icon size unions [generated]

- kotlin-mui/src/main/generated/mui/material/Divider.ext.kt
- kotlin-mui/src/main/generated/mui/material/Divider.kt
- kotlin-mui/src/main/generated/mui/material/FormControl.ext.kt
- kotlin-mui/src/main/generated/mui/material/FormControl.kt
- kotlin-mui/src/main/generated/mui/material/FormHelperText.ext.kt
- kotlin-mui/src/main/generated/mui/material/FormHelperText.kt
- kotlin-mui/src/main/generated/mui/material/InputBase.ext.kt
- kotlin-mui/src/main/generated/mui/material/InputBase.kt
- kotlin-mui/src/main/generated/mui/material/InputLabel.ext.kt
- kotlin-mui/src/main/generated/mui/material/InputLabel.kt
- kotlin-mui/src/main/generated/mui/material/ListItem.ext.kt
- kotlin-mui/src/main/generated/mui/material/ListItem.kt
- kotlin-mui/src/main/generated/mui/material/ListItemButton.ext.kt
- kotlin-mui/src/main/generated/mui/material/ListItemButton.kt
- kotlin-mui/src/main/generated/mui/material/Table.ext.kt
- kotlin-mui/src/main/generated/mui/material/Table.kt
- kotlin-mui/src/main/generated/mui/material/TableCell.ext.kt
- kotlin-mui/src/main/generated/mui/material/TableCell.kt
> MUI. CSS-like unions [generated]

- kotlin-mui/src/main/generated/mui/material/AppBar.ext.kt
- kotlin-mui/src/main/generated/mui/material/AppBar.kt
- kotlin-mui/src/main/generated/mui/material/Fab.ext.kt
- kotlin-mui/src/main/generated/mui/material/Fab.kt
> MUI. Strict color types [generated]

- kotlin-mui/src/main/generated/mui/base/useAutocomplete.ext.kt
- kotlin-mui/src/main/generated/mui/base/useAutocomplete.kt
- kotlin-mui/src/main/generated/mui/material/IconButton.ext.kt
- kotlin-mui/src/main/generated/mui/material/IconButton.kt
- kotlin-mui/src/main/generated/mui/material/Skeleton.ext.kt
- kotlin-mui/src/main/generated/mui/material/Skeleton.kt
- kotlin-mui/src/main/generated/mui/material/Snackbar.ext.kt
- kotlin-mui/src/main/generated/mui/material/Snackbar.kt
- kotlin-mui/src/main/generated/mui/material/SwitchBase.ext.kt
- kotlin-mui/src/main/generated/mui/material/SwitchBase.kt
- kotlin-mui/src/main/generated/mui/material/Tabs.ext.kt
- kotlin-mui/src/main/generated/mui/material/Tabs.kt
> MUI. Unions [generated]

- kotlin-mui/src/main/generated/mui/material/TableCell.ext.kt
- kotlin-mui/src/main/generated/mui/material/TableCell.kt
> MUI. `SortDirection` [generated]

- kotlin-mui/src/main/generated/mui/material/styles/createMixins.kt
- kotlin-mui/src/main/generated/mui/material/styles/createPalette.kt
- kotlin-mui/src/main/generated/mui/material/styles/createStyles.kt
- kotlin-mui/src/main/generated/mui/material/styles/createTheme.kt
- kotlin-mui/src/main/generated/mui/system/createBreakpoints.kt
- kotlin-mui/src/main/generated/mui/system/createSpacing.ext.kt
- kotlin-mui/src/main/generated/mui/system/createSpacing.kt
- kotlin-mui/src/main/generated/mui/system/createTheme.kt
> MUI. Theme `create` methods [generated]

- kotlin-mui/src/main/generated/mui/material/styles/useTheme.kt
- kotlin-mui/src/main/generated/mui/system/useTheme.kt
> MUI. `useTheme` hook [generated]

- kotlin-mui/src/main/generated/mui/material/usePagination.ext.kt
- kotlin-mui/src/main/generated/mui/material/usePagination.kt
> MUI. `usePagination` hook [generated]

- kotlin-mui/src/main/generated/mui/material/useMediaQuery.kt
> MUI. `useMediaQuery` hook [generated]

- examples/src/main/kotlin/example/Product.kt
> Examples. Product: Strict Props

- examples/src/main/kotlin/example/AxiosSearch.kt
- examples/src/main/kotlin/example/Product.kt
- examples/src/main/kotlin/example/Quill.kt
- examples/src/main/kotlin/example/TicTacToe.kt
> Examples Simplification

- examples/src/main/kotlin/example/Product.kt
> Examples: Remove redundant

- gradle.properties
- kotlin-mui/src/main/generated/mui/material/SvgIcon.kt
> MUI `5.2.7` [generated]

- kotlin-mui/src/main/generated/mui/base/BackdropUnstyled.classes.kt
- kotlin-mui/src/main/generated/mui/base/BackdropUnstyled.kt
- kotlin-mui/src/main/generated/mui/base/BadgeUnstyled.classes.kt
- kotlin-mui/src/main/generated/mui/base/BadgeUnstyled.kt
- kotlin-mui/src/main/generated/mui/base/BadgeUnstyledProps.ext.kt
- kotlin-mui/src/main/generated/mui/base/BadgeUnstyledProps.kt
- kotlin-mui/src/main/generated/mui/base/InputUnstyled.classes.kt
- kotlin-mui/src/main/generated/mui/base/InputUnstyled.kt
- kotlin-mui/src/main/generated/mui/base/InputUnstyledProps.kt
- kotlin-mui/src/main/generated/mui/base/SwitchUnstyled.classes.kt
- kotlin-mui/src/main/generated/mui/base/SwitchUnstyled.kt
- kotlin-mui/src/main/generated/mui/base/TabPanelUnstyled.classes.kt
- kotlin-mui/src/main/generated/mui/base/TabPanelUnstyled.kt
- kotlin-mui/src/main/generated/mui/base/TabPanelUnstyledProps.kt
- kotlin-mui/src/main/generated/mui/base/TablePaginationUnstyled.classes.kt
- kotlin-mui/src/main/generated/mui/base/TablePaginationUnstyled.kt
- kotlin-mui/src/main/generated/mui/base/TablePaginationUnstyledProps.ext.kt
- kotlin-mui/src/main/generated/mui/base/TablePaginationUnstyledProps.kt
- kotlin-mui/src/main/generated/mui/base/TabsListUnstyled.classes.kt
- kotlin-mui/src/main/generated/mui/base/TabsListUnstyled.kt
- kotlin-mui/src/main/generated/mui/base/TabsListUnstyledProps.kt
> MUI. Unstyled [generated]

- kotlin-mui/src/main/generated/mui/base/ButtonUnstyled.classes.kt
- kotlin-mui/src/main/generated/mui/base/ButtonUnstyled.kt
- kotlin-mui/src/main/generated/mui/base/ButtonUnstyledProps.kt
- kotlin-mui/src/main/generated/mui/base/TabUnstyled.classes.kt
- kotlin-mui/src/main/generated/mui/base/TabUnstyled.kt
- kotlin-mui/src/main/generated/mui/base/TabUnstyledProps.kt
- kotlin-mui/src/main/generated/mui/base/TabsUnstyled.classes.kt
- kotlin-mui/src/main/generated/mui/base/TabsUnstyled.kt
- kotlin-mui/src/main/generated/mui/base/TabsUnstyledProps.ext.kt
- kotlin-mui/src/main/generated/mui/base/TabsUnstyledProps.kt
- kotlin-mui/src/main/generated/mui/base/UseButtonProps.kt
> MUI. `ButtonUnstyled` [generated]

- kotlin-mui/src/main/generated/mui/base/useAutocomplete.kt
- kotlin-mui/src/main/generated/mui/lab/CalendarPicker.kt
- kotlin-mui/src/main/generated/mui/lab/ClockPicker.kt
- kotlin-mui/src/main/generated/mui/lab/DateRangePickerDay.kt
- kotlin-mui/src/main/generated/mui/lab/MonthPicker.kt
- kotlin-mui/src/main/generated/mui/lab/PickersDay.kt
- kotlin-mui/src/main/generated/mui/lab/TreeItemContent.kt
- kotlin-mui/src/main/generated/mui/material/GlobalStyles.kt
- kotlin-mui/src/main/generated/mui/material/styles/createTransitions.kt
- kotlin-mui/src/main/generated/mui/material/styles/zIndex.kt
> MUI. Remove redundant module declaration [generated]

- kotlin-mui/src/main/generated/mui/material/ButtonGroup.kt
- kotlin-mui/src/main/generated/mui/material/Collapse.kt
- kotlin-mui/src/main/generated/mui/material/Divider.kt
- kotlin-mui/src/main/generated/mui/material/TabScrollButton.kt
- kotlin-mui/src/main/generated/mui/material/Tabs.kt
- kotlin-mui/src/main/generated/mui/material/ToggleButtonGroup.kt
> MUI. Full `Orientation` declaration [generated]

- kotlin-mui/src/main/generated/mui/base/SliderUnstyled.classes.kt
- kotlin-mui/src/main/generated/mui/base/SliderUnstyled.kt
- kotlin-mui/src/main/generated/mui/material/SwitchBase.kt
> MUI. `SliderUnstyled` [generated]

- kotlin-mui/src/main/generated/mui/material/Stubs.kt
- kotlin-mui/src/main/generated/mui/material/TableCell.ext.kt
- kotlin-mui/src/main/generated/mui/material/TableCell.kt
Fix - #1101 
Related - #1103
cc @aerialist7
> MUI. Fix `TableCellBaseProps` alias [generated]

- kotlin-mui/src/main/generated/mui/lab/CalendarPicker.kt
- kotlin-mui/src/main/generated/mui/lab/ClockPicker.kt
- kotlin-mui/src/main/generated/mui/lab/DateRangePickerDay.kt
- kotlin-mui/src/main/generated/mui/lab/MonthPicker.kt
- kotlin-mui/src/main/generated/mui/lab/PickersDay.kt
> MUI. Pickers [generated]

- kotlin-mui/src/main/generated/mui/system/ResponsiveStyleValue.kt
- kotlin-mui/src/main/generated/mui/system/StandardProps.kt
- kotlin-mui/src/main/generated/mui/system/SxProps.kt
> MUI. Factory method for `ResponsiveStyleValue` [generated]

- kotlin-mui/src/main/generated/mui/base/FormControlUnstyled.classes.kt
- kotlin-mui/src/main/generated/mui/base/FormControlUnstyled.kt
- kotlin-mui/src/main/generated/mui/base/FormControlUnstyledProps.ext.kt
- kotlin-mui/src/main/generated/mui/base/FormControlUnstyledProps.kt
> MUI. `FormControlUnstyled` [generated]

- kotlin-mui/build.gradle.kts
- kotlin-mui/src/main/generated/mui/base/PopperUnstyled.ext.kt
- kotlin-mui/src/main/generated/mui/base/PopperUnstyled.kt
- kotlin-mui/src/main/generated/mui/base/Portal.kt
> MUI. `PopperUnstyled` [generated]

- kotlin-mui/src/main/generated/mui/base/ModalUnstyled.classes.kt
- kotlin-mui/src/main/generated/mui/base/ModalUnstyled.kt
> MUI. `ModalUnstyled` [generated]

- kotlin-mui/src/main/generated/mui/material/Backdrop.kt
- kotlin-mui/src/main/generated/mui/material/Badge.kt
- kotlin-mui/src/main/generated/mui/material/Dialog.kt
- kotlin-mui/src/main/generated/mui/material/Drawer.kt
- kotlin-mui/src/main/generated/mui/material/Modal.kt
- kotlin-mui/src/main/generated/mui/material/Popover.kt
- kotlin-mui/src/main/generated/mui/material/Slider.kt
- kotlin-mui/src/main/generated/mui/material/SwipeableDrawer.kt
> MUI. Inherit unstyled props [generated]

- README.md
Kotlin/JS is awesome, I've been developing an MMORPG game with Kotlin/JS for over a year. I'd like to add it as a "real-world example" to the list.
https://bytelegend.com/
> Add ByteLegend to examples

- kotlin-mui/src/main/generated/mui/material/TableCell.kt
> MUI. Common `TableCell.component` type [generated]

- kotlin-mui/src/main/generated/mui/material/Popper.ext.kt
- kotlin-mui/src/main/generated/mui/material/Popper.kt
> MUI. `PopperProps` [generated]

- kotlin-mui/src/main/generated/mui/material/ListItemButton.kt
> MUI. `ListItemButtonProps` [generated]

- kotlin-mui/src/main/generated/mui/base/InputUnstyledProps.kt
- kotlin-mui/src/main/generated/mui/base/SwitchUnstyled.kt
- kotlin-mui/src/main/generated/mui/base/useSwitch.kt
- kotlin-mui/src/main/generated/mui/material/Pagination.kt
- kotlin-mui/src/main/generated/mui/material/Rating.kt
- kotlin-mui/src/main/generated/mui/material/TablePaginationActions.kt
- kotlin-mui/src/main/generated/mui/material/usePagination.kt
> MUI. Props parent types [generated]

- kotlin-mui/src/main/generated/mui/base/useAutocomplete.ext.kt
- kotlin-mui/src/main/generated/mui/material/IconButton.ext.kt
- kotlin-mui/src/main/generated/mui/material/Skeleton.ext.kt
- kotlin-mui/src/main/generated/mui/material/SwitchBase.ext.kt
- kotlin-mui/src/main/generated/mui/material/TableCell.ext.kt
- kotlin-mui/src/main/generated/mui/material/Tabs.ext.kt
> MUI. `Boolean` union values [generated]

- kotlin-mui/src/main/generated/mui/material/Stack.ext.kt
- kotlin-mui/src/main/generated/mui/material/Stack.kt
> MUI. Strict `Stack.direction` [generated]

- gradle.properties
- kotlin-mui/src/main/generated/mui/material/TextField.kt
> MUI `5.2.8` [generated]

- kotlin-mui/src/main/generated/mui/base/ButtonUnstyledProps.kt
- kotlin-mui/src/main/generated/mui/material/ButtonBase.kt
- kotlin-mui/src/main/generated/mui/material/Popover.kt
- kotlin-mui/src/main/generated/mui/material/Tabs.kt
> MUI. Actions [generated]

- gradle.properties
> TypeScript `4.5.5`

- kotlin-typescript/src/main/generated/typescript/ConfigProvider.kt
- kotlin-typescript/src/main/generated/typescript/OptionsProvider.kt
- kotlin-typescript/src/main/generated/typescript/convertCompilerOptionsFromJson.kt
- kotlin-typescript/src/main/generated/typescript/convertTypeAcquisitionFromJson.kt
- kotlin-typescript/src/main/generated/typescript/createIncrementalProgram.kt
- kotlin-typescript/src/main/generated/typescript/parseConfigFileTextToJson.kt
- kotlin-typescript/src/main/generated/typescript/readConfigFile.kt
Related  - #1137 
cc @aerialist7
> TypeScript. Synthetic providers [generated]

- kotlin-typescript/src/main/generated/typescript/BinaryOperator.kt
- kotlin-typescript/src/main/generated/typescript/BinaryOperatorToken.kt
- kotlin-typescript/src/main/generated/typescript/Modifier.kt
- kotlin-typescript/src/main/generated/typescript/ModifiersArray.kt
Related  - #1137 
cc @aerialist7
> TypeScript. Strict aliases [generated]

- README.md
> Update `dependencies` example

- kotlin-typescript/src/main/generated/typescript/isCallOrNewExpression.kt
- kotlin-typescript/src/main/generated/typescript/isClassOrTypeElement.kt
- kotlin-typescript/src/main/generated/typescript/isFunctionOrConstructorTypeNode.kt
- kotlin-typescript/src/main/generated/typescript/isImportOrExportSpecifier.kt
- kotlin-typescript/src/main/generated/typescript/isJSDocLinkLike.kt
- kotlin-typescript/src/main/generated/typescript/isOptionalChain.kt
- kotlin-typescript/src/main/generated/typescript/isPropertyAccessOrQualifiedName.kt
- kotlin-typescript/src/main/generated/typescript/isStringTextContainingNode.kt
- kotlin-typescript/src/main/generated/typescript/isTemplateMiddleOrTemplateTail.kt
Related - #1137 
cc @aerialist7
> TypeScript. Fix type guard return type [generated]

- kotlin-typescript/src/main/generated/typescript/LanguageServiceHost.kt
- kotlin-typescript/src/main/generated/typescript/ModeAwareCache.kt
- kotlin-typescript/src/main/generated/typescript/NodeFormat.kt
- kotlin-typescript/src/main/generated/typescript/NonRelativeModuleNameResolutionCache.kt
- kotlin-typescript/src/main/generated/typescript/ResolutionMode.kt
- kotlin-typescript/src/main/generated/typescript/SourceFile.kt
- kotlin-typescript/src/main/generated/typescript/getImpliedNodeFormatForFile.kt
- kotlin-typescript/src/main/generated/typescript/resolveModuleName.kt
- kotlin-typescript/src/main/generated/typescript/resolveModuleNameFromCache.kt
Related  - #1137
cc @aerialist7
> TypeScript. `ModuleKind` aliases [generated]

- kotlin-typescript/src/main/generated/typescript/ImportModuleSpecifierEnding.kt
- kotlin-typescript/src/main/generated/typescript/ImportModuleSpecifierPreference.kt
- kotlin-typescript/src/main/generated/typescript/IncludeInlayParameterNameHints.kt
- kotlin-typescript/src/main/generated/typescript/IncludePackageJsonAutoImports.kt
- kotlin-typescript/src/main/generated/typescript/InlayHintsOptions.kt
- kotlin-typescript/src/main/generated/typescript/JsxAttributeCompletionStyle.kt
- kotlin-typescript/src/main/generated/typescript/MatchKind.kt
- kotlin-typescript/src/main/generated/typescript/NavigateToItem.kt
- kotlin-typescript/src/main/generated/typescript/PerformanceEvent.kt
- kotlin-typescript/src/main/generated/typescript/PerformanceEventKind.kt
- kotlin-typescript/src/main/generated/typescript/QuotePreference.kt
- kotlin-typescript/src/main/generated/typescript/SourceFileType.kt
- kotlin-typescript/src/main/generated/typescript/UserPreferences.kt
- kotlin-typescript/src/main/generated/typescript/createUnparsedSourceFile.kt
Related  - #1137
cc @aerialist7
> TypeScript. String unions [generated]

- gradle.properties
- kotlin-mui-icons/src/main/generated/mui/icons/material/EighteenMp.kt
- kotlin-mui-icons/src/main/generated/mui/icons/material/EighteenMpOutlined.kt
- kotlin-mui-icons/src/main/generated/mui/icons/material/EighteenMpRounded.kt
- kotlin-mui-icons/src/main/generated/mui/icons/material/EighteenMpSharp.kt
- kotlin-mui-icons/src/main/generated/mui/icons/material/EighteenMpTwoTone.kt
- kotlin-mui-icons/src/main/generated/mui/icons/material/FifteenMp.kt
- kotlin-mui-icons/src/main/generated/mui/icons/material/FifteenMpOutlined.kt
- kotlin-mui-icons/src/main/generated/mui/icons/material/FifteenMpRounded.kt
- kotlin-mui-icons/src/main/generated/mui/icons/material/FifteenMpSharp.kt
- kotlin-mui-icons/src/main/generated/mui/icons/material/FifteenMpTwoTone.kt
- kotlin-mui/src/main/generated/mui/base/useAutocomplete.kt
- kotlin-mui/src/main/generated/mui/material/Button.classes.kt
> MUI `5.3.1` [generated]

- kotlin-typescript/src/main/generated/typescript/Identifier.kt
- kotlin-typescript/src/main/generated/typescript/Node.kt
- kotlin-typescript/src/main/generated/typescript/PrivateIdentifier.kt
- kotlin-typescript/src/main/generated/typescript/Signature.kt
- kotlin-typescript/src/main/generated/typescript/SourceFile.kt
- kotlin-typescript/src/main/generated/typescript/SourceMapSource.kt
- kotlin-typescript/src/main/generated/typescript/Symbol.kt
- kotlin-typescript/src/main/generated/typescript/Type.kt
- kotlin-typescript/src/main/generated/typescript/TypeReference.kt
> TypeScript. Merge interfaces [generated]

- kotlin-typescript/src/main/generated/typescript/AffectedFileResult.kt
- kotlin-typescript/src/main/generated/typescript/ArrayBindingOrAssignmentElement.kt
- kotlin-typescript/src/main/generated/typescript/CompilerOptionsValue.kt
- kotlin-typescript/src/main/generated/typescript/CompletionsTriggerCharacter.kt
- kotlin-typescript/src/main/generated/typescript/DocumentRegistryBucketKey.kt
- kotlin-typescript/src/main/generated/typescript/EndOfFileToken.kt
- kotlin-typescript/src/main/generated/typescript/InvalidatedProject.kt
- kotlin-typescript/src/main/generated/typescript/ParameterPropertyDeclaration.kt
- kotlin-typescript/src/main/generated/typescript/Path.kt
- kotlin-typescript/src/main/generated/typescript/ResolvedConfigFileName.kt
- kotlin-typescript/src/main/generated/typescript/SignatureHelpTriggerCharacter.kt
- kotlin-typescript/src/main/generated/typescript/TypeOnlyAliasDeclaration.kt
- kotlin-typescript/src/main/generated/typescript/WithMetadata.kt
- kotlin-typescript/src/main/generated/typescript/__String.kt
> TypeScript. Interface types [generated]

- kotlin-typescript/src/main/generated/typescript/JsIterator.kt
- kotlin-typescript/src/main/generated/typescript/NodeArray.kt
- kotlin-typescript/src/main/generated/typescript/ReadonlyArrayAdapter.kt
- kotlin-typescript/src/main/generated/typescript/SortedArray.kt
- kotlin-typescript/src/main/generated/typescript/SortedReadonlyArray.kt
> TypeScript. `Array` children [generated]

- kotlin-mui/src/main/generated/mui/base/ButtonUnstyled.kt
- kotlin-mui/src/main/generated/mui/base/InputUnstyledProps.kt
- kotlin-mui/src/main/generated/mui/material/styles/createTheme.kt
> MUI. `Theme` parent type [generated]

- gradle.properties
- kotlin-mui/src/main/generated/mui/base/MultiSelectUnstyled.kt
- kotlin-mui/src/main/generated/mui/base/MultiSelectUnstyledProps.kt
- kotlin-mui/src/main/generated/mui/base/OptionGroupUnstyled.classes.kt
- kotlin-mui/src/main/generated/mui/base/OptionGroupUnstyled.kt
- kotlin-mui/src/main/generated/mui/base/OptionGroupUnstyledProps.kt
- kotlin-mui/src/main/generated/mui/base/OptionUnstyled.classes.kt
- kotlin-mui/src/main/generated/mui/base/OptionUnstyled.kt
- kotlin-mui/src/main/generated/mui/base/OptionUnstyledProps.kt
- kotlin-mui/src/main/generated/mui/base/SelectUnstyled.classes.kt
- kotlin-mui/src/main/generated/mui/base/SelectUnstyled.kt
- kotlin-mui/src/main/generated/mui/base/SelectUnstyledProps.kt
- kotlin-mui/src/main/generated/mui/base/UseButtonProps.kt
- kotlin-mui/src/main/generated/mui/base/UseSelectProps.kt
- kotlin-mui/src/main/generated/mui/lab/TreeView.kt
- kotlin-mui/src/main/generated/mui/material/Autocomplete.kt
- kotlin-mui/src/main/generated/mui/material/FormControlLabel.classes.kt
- kotlin-mui/src/main/generated/mui/material/FormGroup.classes.kt
- kotlin-mui/src/main/generated/mui/material/styles/ThemeProvider.kt
- kotlin-mui/src/main/generated/mui/material/useMediaQuery.kt
- kotlin-mui/src/main/generated/mui/system/ThemeProvider.kt
> MUI `5.4.0` [generated]

- kotlin-webrtc/src/main/generated/webrtc/DataChannelEventHandler.kt
- kotlin-webrtc/src/main/generated/webrtc/DtlsTransportEventHandler.kt
- kotlin-webrtc/src/main/generated/webrtc/IceTransportEventHandler.kt
- kotlin-webrtc/src/main/generated/webrtc/PeerConnectionEventHandler.kt
- kotlin-webrtc/src/main/generated/webrtc/RTCDataChannel.kt
- kotlin-webrtc/src/main/generated/webrtc/RTCDtlsTransport.kt
- kotlin-webrtc/src/main/generated/webrtc/RTCDtlsTransportEventMap.kt
- kotlin-webrtc/src/main/generated/webrtc/RTCError.kt
- kotlin-webrtc/src/main/generated/webrtc/RTCIceTransport.kt
- kotlin-webrtc/src/main/generated/webrtc/RTCIceTransportEventMap.kt
- kotlin-webrtc/src/main/generated/webrtc/RTCPeerConnection.kt
- kotlin-webrtc/src/main/generated/webrtc/RTCPeerConnectionConfig.kt
- kotlin-webrtc/src/main/generated/webrtc/RTCPeerConnectionErrorCallback.kt
- kotlin-webrtc/src/main/generated/webrtc/RTCPeerConnectionStatic.kt
- kotlin-webrtc/src/main/generated/webrtc/RTCSessionDescription.kt
- kotlin-webrtc/src/main/generated/webrtc/RTCSessionDescriptionCallback.kt
- kotlin-webrtc/src/main/generated/webrtc/RTCSessionDescriptionInit.kt
- kotlin-webrtc/src/main/generated/webrtc/RTCStatsReport.kt
[Related issue](https://youtrack.jetbrains.com/issue/KT-50893)
Previous - #1166
> WebRTC. `RTCPeerConnection` [generated]

- kotlin-node/build.gradle.kts
- kotlin-node/src/main/generated/node/path/FormatInputPathObject.kt
- kotlin-node/src/main/generated/node/path/ParsedPath.kt
- kotlin-node/src/main/generated/node/path/PlatformPath.kt
> Node. `path` [generated]

- kotlin-mui/src/main/generated/mui/base/BadgeUnstyledProps.kt
- kotlin-mui/src/main/generated/mui/base/ModalUnstyled.kt
- kotlin-mui/src/main/generated/mui/material/AvatarGroup.kt
- kotlin-mui/src/main/generated/mui/material/ButtonBase.kt
- kotlin-mui/src/main/generated/mui/material/Fab.ext.kt
- kotlin-mui/src/main/generated/mui/material/TouchRipple.classes.kt
- kotlin-mui/src/main/generated/mui/material/TouchRipple.ext.kt
- kotlin-mui/src/main/generated/mui/material/TouchRipple.kt
> MUI `5.4.1` [generated]

- gradle.properties
> MUI. Fix versions

- kotlin-browser/build.gradle.kts
- kotlin-browser/src/main/kotlin/org/w3c/dom/IntersectionObserver.kt
- kotlin-browser/src/main/kotlin/org/w3c/dom/ResizeObserver.kt
> Browser. Observers

- kotlin-browser/src/main/kotlin/org/w3c/fetch/AbortController.kt
- kotlin-browser/src/main/kotlin/org/w3c/fetch/AbortSignal.kt
- kotlin-browser/src/main/kotlin/org/w3c/fetch/RequestInit.kt
- kotlin-react-query/build.gradle.kts
- kotlin-react-query/src/main/generated/react/query/types.core.kt
- kotlin-react-query/src/main/generated/react/query/utils.core.kt
> Browser. `AbortController`

- examples/src/main/kotlin/example/AxiosSearch.kt
- examples/src/main/kotlin/example/Main.kt
- kotlin-extensions/src/main/kotlin/kotlinext/js/Helpers.kt
- kotlin-extensions/src/main/kotlin/kotlinx/js/Record.kt
- kotlin-extensions/src/main/kotlin/kotlinx/js/jso.kt
- kotlin-popper/src/main/generated/popper/core/ModifierName.kt
- kotlin-react-css/src/main/kotlin/react/css/css.kt
- kotlin-react-dom-legacy/src/main/kotlin/react/dom/RDOMBuilder.kt
- kotlin-react-legacy/src/main/kotlin/react/RBuilder.kt
- kotlin-react-legacy/src/main/kotlin/react/RComponent.kt
- kotlin-react-legacy/src/main/kotlin/react/RPureComponent.kt
- kotlin-react-legacy/src/main/kotlin/react/ReactElement.ext.kt
- kotlin-react-router-dom/src/main/generated/react/router/dom/SearchParamsInstance.kt
- kotlin-react-table/src/main/kotlin/react/table/Columns.kt
- kotlin-react-virtual/src/main/kotlin/react/virtual/Size.kt
- kotlin-ring-ui/src/main/kotlin/ringui/Color.kt
- kotlin-styled-next/src/main/kotlin/styled/CssAccess.kt
- kotlin-styled-next/src/main/kotlin/styled/StyledComponents.kt
- kotlin-styled-next/src/test/kotlin/TestUtils.kt
- kotlin-styled/src/main/kotlin/styled/StyledComponents.kt
> Extensions. Update `jso` package

- kotlin-extensions/src/main/kotlin/kotlinx/js/JsIterator.kt
- kotlin-typescript/src/main/generated/typescript/ReadonlyCollection.kt
- kotlin-typescript/src/main/generated/typescript/ReadonlyESMap.kt
- kotlin-typescript/src/main/generated/typescript/ReadonlySet.kt
Related - #1044
cc @aerialist7
> Extensions. `JsIterator`

- kotlin-csstype/src/main/generated/csstype/Angle.kt
> CSSType. `Angle` [generated]

- kotlin-csstype/src/main/generated/csstype/FilterFunction.kt
> CSSType. Strict `drop-shadow` [generated]

- kotlin-csstype/src/main/generated/csstype/AutoRepeat.kt
For [`repeat`](https://developer.mozilla.org/en-US/docs/Web/CSS/repeat())
> CSSType. `AutoRepeat` [generated]

- kotlin-extensions/src/main/kotlin/kotlinx/js/JsSet.kt
> Added JsSet (#1044)

- kotlin-csstype/src/main/generated/csstype/FilterFunction.kt
- kotlin-csstype/src/main/generated/csstype/Percent.kt
- kotlin-csstype/src/main/generated/csstype/Percentage.kt
[MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/percentage)
> CSSType. `Percent` -> `Percentage` [generated]

- kotlin-csstype/src/main/generated/csstype/Url.kt
[url()](https://developer.mozilla.org/ru/docs/Web/CSS/url()) result type
> CSSType. `Url` [generated]

- kotlin-csstype/src/main/generated/csstype/Reference.functions.kt
[MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Functions#reference_functions)
> CSSType. `attr` and `url` [generated]

- kotlin-browser/src/main/kotlin/org/w3c/fetch/AbortSignal.kt
[Related message](https://kotlinlang.slack.com/archives/C0B8L3U69/p1644958488822439?thread_ts=1644913190.128429&cid=C0B8L3U69)
> Mutable `AbortSignal.onabort`

- kotlin-browser/src/main/kotlin/org/w3c/dom/Document.kt
- kotlin-browser/src/main/kotlin/org/w3c/dom/FontFaceSet.kt
[MDN](https://developer.mozilla.org/en-US/docs/Web/API/FontFaceSet)
> Browser. Add `FontFaceSet`

- kotlin-csstype/src/main/generated/csstype/AutoType.kt
- kotlin-csstype/src/main/generated/csstype/Length.kt
- kotlin-csstype/src/main/generated/csstype/NoneType.kt
> CSSType. Remove `Length.auto` and `Length.none` [generated]

- kotlin-csstype/src/main/generated/csstype/Grid.functions.kt
> CSSType. `fit-content` [generated]

- examples/src/main/kotlin/example/Main.kt
- kotlin-extensions/src/main/kotlin/kotlinext/js/Helpers.kt
- kotlin-extensions/src/main/kotlin/kotlinext/js/Object.kt
- kotlin-extensions/src/main/kotlin/kotlinx/js/Object.kt
- kotlin-extensions/src/main/kotlin/kotlinx/js/PropertyDescriptor.kt
- kotlin-react/src/main/kotlin/react/ChildrenBuilder.kt
- kotlin-redux/src/main/kotlin/redux/Helpers.kt
- kotlin-styled-next/src/main/kotlin/styled/InlineStyles.kt
- kotlin-styled/src/main/kotlin/styled/InlineStyles.kt
> Extensions. `Object` & `Property Descriptor`

- kotlin-extensions/src/main/kotlin/kotlinx/js/WeakMap.kt
- kotlin-extensions/src/main/kotlin/kotlinx/js/WeakSet.kt
> `WeakMap` and `WeakSet`

- kotlin-extensions/src/main/kotlin/kotlinx/js/JsNumber.kt
> `JsNumber`

- gradle.properties
- kotlin-mui/src/main/generated/mui/material/ButtonBase.kt
- kotlin-mui/src/main/generated/mui/material/Dialog.kt
- kotlin-mui/src/main/generated/mui/material/Drawer.kt
- kotlin-mui/src/main/generated/mui/material/Fade.kt
- kotlin-mui/src/main/generated/mui/material/Slide.kt
- kotlin-mui/src/main/generated/mui/material/Snackbar.kt
- kotlin-mui/src/main/generated/mui/material/SpeedDial.kt
- kotlin-mui/src/main/generated/mui/material/Zoom.kt
> MUI `5.4.3` [generated]

- kotlin-csstype/src/main/generated/csstype/Grid.functions.kt
- kotlin-csstype/src/main/generated/csstype/GridAutoTracks.kt
> CSSType. `minmax` [generated]

- kotlin-csstype/src/main/generated/csstype/Math.functions.kt
> CSSType. Math functions [generated]

- kotlin-csstype/src/main/generated/csstype/ColumnCount.kt
- kotlin-csstype/src/main/generated/csstype/FlexGrow.kt
- kotlin-csstype/src/main/generated/csstype/FlexShrink.kt
- kotlin-csstype/src/main/generated/csstype/FontWeight.kt
- kotlin-csstype/src/main/generated/csstype/Integer.kt
- kotlin-csstype/src/main/generated/csstype/LineClamp.kt
- kotlin-csstype/src/main/generated/csstype/MaxLines.kt
- kotlin-csstype/src/main/generated/csstype/Number.kt
- kotlin-csstype/src/main/generated/csstype/Opacity.kt
- kotlin-csstype/src/main/generated/csstype/Order.kt
- kotlin-csstype/src/main/generated/csstype/Orphans.kt
- kotlin-csstype/src/main/generated/csstype/Scale.kt
- kotlin-csstype/src/main/generated/csstype/Widows.kt
- kotlin-csstype/src/main/generated/csstype/ZIndex.kt
- kotlin-csstype/src/main/generated/csstype/Zoom.kt
> CSSType. `number` and `integer` factories [generated]

- kotlin-extensions/src/main/kotlin/kotlinx/js/Object.kt
> `Object` - sort methods

- kotlin-extensions/src/main/kotlin/kotlinx/js/Object.kt
> `Object.entries` and `Object.values`

- kotlin-react-query/src/main/generated/react/query/hydration.core.kt
- kotlin-react-query/src/main/generated/react/query/infiniteQueryBehavior.core.kt
- kotlin-react-query/src/main/generated/react/query/infiniteQueryObserver.core.kt
- kotlin-react-query/src/main/generated/react/query/mutation.core.kt
- kotlin-react-query/src/main/generated/react/query/mutationCache.core.kt
- kotlin-react-query/src/main/generated/react/query/mutationObserver.core.kt
- kotlin-react-query/src/main/generated/react/query/queriesObserver.core.kt
- kotlin-react-query/src/main/generated/react/query/query.core.kt
- kotlin-react-query/src/main/generated/react/query/queryCache.core.kt
- kotlin-react-query/src/main/generated/react/query/queryClient.core.kt
- kotlin-react-query/src/main/generated/react/query/queryObserver.core.kt
- kotlin-react-query/src/main/generated/react/query/retryer.core.kt
- kotlin-react-query/src/main/generated/react/query/subscribable.core.kt
- kotlin-react-query/src/main/generated/react/query/types.core.kt
- kotlin-react-query/src/main/generated/react/query/types.kt
- kotlin-react-query/src/main/generated/react/query/useQueries.kt
- kotlin-react-query/src/main/generated/react/query/utils.core.kt
> React Query. Imports [generated]

- kotlin-react-core/src/main/kotlin/react/VFC.kt
- kotlin-react/src/main/kotlin/react/VFC.kt
[Original](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/45437334b53ce6497e12eaef0ed98a31024101cc/types/react/index.d.ts#L557)
cc @aerialist7
> React. `VFC`

- gradle.properties
- kotlin-react-query/src/main/generated/react/query/focusManager.core.kt
- kotlin-react-query/src/main/generated/react/query/onlineManager.core.kt
- kotlin-react-query/src/main/generated/react/query/queryClient.core.kt
- kotlin-react-query/src/main/generated/react/query/types.core.kt
- kotlin-react-query/src/main/generated/react/query/types.kt
- kotlin-react-query/src/main/generated/react/query/useIsMutating.kt
- kotlin-react-query/src/main/generated/react/query/useQueries.kt
> React Query `3.34.15` [generated]

- kotlin-react/src/main/kotlin/react/ChildrenBuilder.kt
- kotlin-react/src/main/kotlin/react/createElementOrNull.kt
> React. Support `null` child

- kotlin-react-core/src/main/kotlin/react/ReactElement.kt
[Source](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/3ff310ff320c1bc77bd45e51591a1136e035bc26/types/react/index.d.ts#L389)
> React. Fix `isValidElement` contract

- kotlin-react-core/src/main/kotlin/react/ReactPortal.kt
- kotlin-react-dom-legacy/src/main/kotlin/react/dom/createPortal.ext.kt
- kotlin-react-dom/src/main/kotlin/react/dom/createPortal.kt
> React. Fix `ReactPortal` contract

- examples/src/main/kotlin/example/ForwardingRefs.kt
> Forwarding Refs example is updated, mutability is fixed

- gradle.properties
- kotlin-mui/src/main/generated/mui/base/ButtonUnstyled.types.kt
- kotlin-mui/src/main/generated/mui/base/MultiSelectUnstyled.types.kt
- kotlin-mui/src/main/generated/mui/base/SelectUnstyled.types.kt
- kotlin-mui/src/main/generated/mui/base/useButton.types.kt
- kotlin-mui/src/main/generated/mui/base/useSelect.types.kt
> MUI `5.4.4` [generated]

- kotlin-mui/src/main/generated/mui/material/ListItem.kt
- kotlin-mui/src/main/generated/mui/material/ListItemButton.kt
> MUI. Fix `List*` component props [generated]

- gradle.properties
- kotlin-cesium/src/main/generated/cesium/AxisAlignedBoundingBox.kt
- kotlin-cesium/src/main/generated/cesium/BoundingSphere.kt
- kotlin-cesium/src/main/generated/cesium/Camera.kt
- kotlin-cesium/src/main/generated/cesium/Cartesian2.kt
- kotlin-cesium/src/main/generated/cesium/Cartesian4.kt
- kotlin-cesium/src/main/generated/cesium/Cesium3DTileset.kt
- kotlin-cesium/src/main/generated/cesium/CesiumWidget.kt
- kotlin-cesium/src/main/generated/cesium/Credit.kt
- kotlin-cesium/src/main/generated/cesium/CustomShader.kt
- kotlin-cesium/src/main/generated/cesium/GpxDataSource.kt
- kotlin-cesium/src/main/generated/cesium/Matrix2.kt
- kotlin-cesium/src/main/generated/cesium/Matrix3.kt
- kotlin-cesium/src/main/generated/cesium/Matrix4.kt
- kotlin-cesium/src/main/generated/cesium/Model.kt
- kotlin-cesium/src/main/generated/cesium/ModelExperimental.kt
- kotlin-cesium/src/main/generated/cesium/OrientedBoundingBox.kt
- kotlin-cesium/src/main/generated/cesium/Rectangle.kt
- kotlin-cesium/src/main/generated/cesium/Scene.kt
- kotlin-cesium/src/main/generated/cesium/Viewer.kt
- kotlin-cesium/src/main/generated/cesium/getImagePixels.kt
> Cesium `1.91.0` [generated]

- kotlin-extensions/src/main/kotlin/kotlinext/js/Helpers.kt
- kotlin-extensions/src/main/kotlin/kotlinx/js/delete.kt
- kotlin-styled-next/src/main/kotlin/styled/StyledComponents.kt
> Extensions. Update `delete` package

- kotlin-react-dom-legacy/src/main/kotlin/react/dom/render.ext.kt
- kotlin-react-dom/src/main/kotlin/react/dom/client/Root.kt
- kotlin-react-dom/src/main/kotlin/react/dom/client/createRoot.kt
[Source](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/70994deac06e5a0a7df1da77803127d5b1f7bf3d/types/react-dom/client.d.ts)
cc @aerialist7 @stefanthaler
> React `18.0.0-rc.1` support

- kotlin-react-core/src/main/kotlin/react/ComponentType.kt
- kotlin-react-core/src/main/kotlin/react/Context.kt
- kotlin-react-core/src/main/kotlin/react/ExoticComponent.kt
- kotlin-react-core/src/main/kotlin/react/ForwardRefExoticComponent.kt
- kotlin-react-core/src/main/kotlin/react/Fragment.kt
- kotlin-react-core/src/main/kotlin/react/NamedExoticComponent.kt
- kotlin-react-core/src/main/kotlin/react/Profiler.kt
- kotlin-react-core/src/main/kotlin/react/Raw.kt
- kotlin-react-core/src/main/kotlin/react/StrictMode.kt
- kotlin-react-core/src/main/kotlin/react/Suspense.kt
- kotlin-react-core/src/main/kotlin/react/lazy.kt
- kotlin-react-core/src/main/kotlin/react/memo.kt
- kotlin-react-legacy/src/main/kotlin/react/forwardRef.kt
- kotlin-styled-next/src/main/kotlin/styled/StyledComponents.kt
[Source](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts)
cc @aerialist7 @stefanthaler
> React. Exotic components

- kotlin-csstype/src/main/generated/csstype/AutoType.kt
- kotlin-csstype/src/main/generated/csstype/LineStyleProperty.kt
- kotlin-csstype/src/main/generated/csstype/OutlineStyle.kt
> CSSType. `OutlineStyle` [generated]

- kotlin-react-dom/src/main/kotlin/react/dom/client/Root.kt
- kotlin-react-dom/src/main/kotlin/react/dom/client/RootOptions.kt
- kotlin-react-dom/src/main/kotlin/react/dom/client/createRoot.kt
[Source](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/9ed456704eae9073f90b5763ffc2f911032bb13e/types/react-dom/client.d.ts)
> React `18.0.0-rc.1`. Support new `createRoot` contract

- kotlin-react-css/src/main/kotlin/react/css/css.kt
> React CSS. Strict DSL

- kotlin-extensions/src/main/kotlin/kotlinx/js/timers/immediate.kt
- kotlin-extensions/src/main/kotlin/kotlinx/js/timers/interval.kt
- kotlin-extensions/src/main/kotlin/kotlinx/js/timers/queueMicrotask.kt
- kotlin-extensions/src/main/kotlin/kotlinx/js/timers/timeout.kt
Fix #1224
[Related issue](https://youtrack.jetbrains.com/issue/KT-46315)
cc @aerialist7 @stefanthaler
> JS. Timers

- kotlin-extensions/src/main/kotlin/kotlinx/js/timers/interval.kt
- kotlin-extensions/src/main/kotlin/kotlinx/js/timers/timeout.kt
> JS. Timer extensions

- kotlin-mui/src/main/generated/mui/base/ButtonUnstyled.types.kt
- kotlin-mui/src/main/generated/mui/base/FormControlUnstyledProps.kt
- kotlin-mui/src/main/generated/mui/base/InputUnstyledProps.kt
- kotlin-mui/src/main/generated/mui/base/OptionGroupUnstyledProps.kt
- kotlin-mui/src/main/generated/mui/base/OptionUnstyledProps.kt
- kotlin-mui/src/main/generated/mui/base/SelectUnstyled.types.kt
- kotlin-mui/src/main/generated/mui/base/SwitchUnstyled.kt
- kotlin-mui/src/main/generated/mui/base/TabPanelUnstyledProps.kt
- kotlin-mui/src/main/generated/mui/base/TabsListUnstyledProps.kt
- kotlin-mui/src/main/generated/mui/base/TabsUnstyledProps.kt
- kotlin-mui/src/main/generated/mui/lab/CalendarPicker.kt
- kotlin-mui/src/main/generated/mui/lab/MonthPicker.kt
- kotlin-mui/src/main/generated/mui/lab/TreeItemContent.kt
- kotlin-mui/src/main/generated/mui/material/Collapse.kt
> MUI. Use `PropsWithClassName` interface [generated]

- kotlin-emotion/src/main/kotlin/emotion/react/Theme.kt
- kotlin-emotion/src/main/kotlin/emotion/react/ThemeProvider.kt
- kotlin-emotion/src/main/kotlin/emotion/react/useTheme.kt
> Emotion. Theming is introduced

- kotlin-emotion/src/main/kotlin/emotion/react/CacheProvider.kt
> Emotion. CacheProvider is introduced

- kotlin-emotion/src/main/kotlin/emotion/react/Global.ext.kt
- kotlin-emotion/src/main/kotlin/emotion/react/Global.kt
> Emotion. Global is introduced

- kotlin-csstype/src/main/generated/csstype/RuleBuilder.kt
- kotlin-csstype/src/main/generated/csstype/Rules.kt
- kotlin-csstype/src/main/generated/csstype/Selector.kt
> CSSType. `Rules` [generated]

- kotlin-emotion/src/main/kotlin/emotion/css/keyframes.ext.kt
- kotlin-emotion/src/main/kotlin/emotion/css/keyframes.kt
> Emotion. Keyframes helper is introduced

- kotlin-emotion/src/main/kotlin/emotion/react/Global.ext.kt
- kotlin-emotion/src/main/kotlin/emotion/react/Global.kt
> Emotion. Global API is fixed

- kotlin-emotion/src/main/kotlin/emotion/css/keyframes.ext.kt
> Emotion. Fix `KeyframesBuilder`

- buildSrc/src/main/kotlin/Projects.kt
- gradle.properties
- kotlin-emotion/build.gradle.kts
> Emotion. Add `@emotion/react` missed dependency

- kotlin-csstype/src/main/generated/csstype/AdvancedPseudosRuleBuilder.kt
> CSSType. Strict pseudo selectors [generated]

- kotlin-extensions/src/main/kotlin/kotlinx/js/Record.kt
> Extensions. Add empty `Record`

- buildSrc/src/main/kotlin/Projects.kt
- gradle.properties
- kotlin-emotion/build.gradle.kts
- kotlin-emotion/src/main/kotlin/emotion/styled/StyledOptions.kt
- kotlin-emotion/src/main/kotlin/emotion/styled/styled.ext.kt
- kotlin-emotion/src/main/kotlin/emotion/styled/styled.kt
cc @turansky @aerialist7 @stefanthaler
> Emotion. Styled API is added

- kotlin-emotion/src/main/kotlin/emotion/css/keyframes.ext.kt
> Emotion. Fix DCE in `KeyframeBuilder`

- kotlin-emotion/src/main/kotlin/emotion/styled/StyledOptions.kt
- kotlin-emotion/src/main/kotlin/emotion/styled/styled.ext.kt
- kotlin-emotion/src/main/kotlin/emotion/styled/styled.kt
cc @turansky @aerialist7 @stefanthaler
> Emotion. `StyledOptions` are introduced

- kotlin-csstype/src/main/generated/csstype/AdvancedPseudosRuleBuilder.kt
> CSSType. Advanced pseudo selectors [generated]

- kotlin-csstype/src/main/generated/csstype/SimplePseudosRuleBuilder.kt
> CSSType. Selector factories [generated]

- kotlin-mui/src/main/generated/mui/material/styles/createTheme.kt
- kotlin-mui/src/main/generated/mui/system/createTheme.kt
> MUI. Fix `Theme` hierarchy [generated]

- README.md
- examples/build.gradle.kts
- examples/src/main/kotlin/example/AxiosSearch.kt
- examples/src/main/kotlin/example/Main.kt
- examples/src/main/kotlin/example/Product.kt
- kotlin-react-css/build.gradle.kts
- kotlin-react-css/src/main/kotlin/react/css/css.kt
> React CSS. Deprecated

- kotlin-csstype/src/main/generated/csstype/SimplePseudosRuleBuilder.kt
Reverts JetBrains/kotlin-wrappers#1319
> Revert "CSSType. Selector factories [generated]"

- kotlin-csstype/src/main/generated/csstype/AdvancedPseudosRuleBuilder.kt
Reverts JetBrains/kotlin-wrappers#1318
> Revert "CSSType. Advanced pseudo selectors [generated]"

- kotlin-mui/src/main/generated/mui/material/AppBar.kt
- kotlin-mui/src/main/generated/mui/material/Card.kt
> MUI. Fix `AppBar` and `Card` props [generated]

- examples/src/main/kotlin/example/TicTacToe.kt
- kotlin-csstype/src/main/generated/csstype/ClassName.kt
- kotlin-emotion/src/main/kotlin/emotion/css/css.kt
- kotlin-emotion/src/main/kotlin/emotion/css/cx.kt
- kotlin-emotion/src/main/kotlin/emotion/css/getRegisteredStyles.kt
- kotlin-emotion/src/main/kotlin/emotion/css/merge.kt
- kotlin-emotion/src/main/kotlin/emotion/react/css.kt
- kotlin-mui/src/main/generated/mui/base/ButtonUnstyled.types.kt
- kotlin-mui/src/main/generated/mui/base/FormControlUnstyledProps.kt
- kotlin-mui/src/main/generated/mui/base/InputUnstyledProps.kt
- kotlin-mui/src/main/generated/mui/base/MenuItemUnstyled.types.kt
- kotlin-mui/src/main/generated/mui/base/MenuUnstyled.types.kt
- kotlin-mui/src/main/generated/mui/base/OptionGroupUnstyledProps.kt
- kotlin-mui/src/main/generated/mui/base/OptionUnstyledProps.kt
- kotlin-mui/src/main/generated/mui/base/SelectUnstyled.types.kt
- kotlin-mui/src/main/generated/mui/base/SwitchUnstyled.kt
- kotlin-mui/src/main/generated/mui/base/TabPanelUnstyledProps.kt
- kotlin-mui/src/main/generated/mui/base/TabsListUnstyledProps.kt
- kotlin-mui/src/main/generated/mui/base/TabsUnstyledProps.kt
- kotlin-mui/src/main/generated/mui/lab/CalendarPicker.kt
- kotlin-mui/src/main/generated/mui/lab/MonthPicker.kt
- kotlin-mui/src/main/generated/mui/lab/TreeItemContent.kt
- kotlin-mui/src/main/generated/mui/material/Collapse.kt
- kotlin-react-core/src/main/kotlin/react/PropsWithClassName.kt
> CSS. Add `ClassName` type

- kotlin-csstype/src/main/generated/csstype/RuleBuilder.kt
> CSSType. Rule for `ClassName`

- gradle.properties
- kotlin-mui/src/main/generated/mui/base/ButtonUnstyled.kt
- kotlin-mui/src/main/generated/mui/base/MenuItemUnstyled.kt
- kotlin-mui/src/main/generated/mui/base/MenuUnstyled.kt
- kotlin-mui/src/main/generated/mui/material/InputBase.kt
- kotlin-mui/src/main/generated/mui/material/styles/zIndex.kt
- kotlin-mui/src/main/generated/mui/material/usePagination.kt
> MUI `5.5.1`

- kotlin-csstype/src/main/generated/csstype/StandardLonghandProperties.kt
> CSSType. `appearance` vendor aliases [generated]

- kotlin-mui/src/main/generated/mui/system/createSpacing.ext.kt
- kotlin-mui/src/main/generated/mui/system/createSpacing.kt
> MUI. `Spacing` [generated]

- gradle.properties
> TypeScript. Fix version

- kotlin-csstype/src/main/generated/csstype/AnimationIterationCount.kt
- kotlin-csstype/src/main/generated/csstype/GlobalsType.kt
- kotlin-csstype/src/main/generated/csstype/Number.kt
> CSSType. `AnimationIterationCount` [generated]

- kotlin-react-dom/src/main/generated/react/dom/html/ReactHTML.kt
> React Types `17.0.43` [generated]

- kotlin-mui/src/main/generated/mui/material/styles/createPalette.kt
- kotlin-mui/src/main/generated/mui/system/createSpacing.ext.kt
> MUI. Use `Color` type [generated]

- gradle.properties
> React Query `3.34.19`

- kotlin-extensions/src/main/kotlin/kotlinx/js/Performance.kt
Fix #1370
cc @stefanthaler @aerialist7
> JS. `Performance`

- kotlin-extensions/src/main/kotlin/kotlinext/js/Helpers.kt
- kotlin-extensions/src/main/kotlin/kotlinext/js/Object.kt
- kotlin-extensions/src/main/kotlin/kotlinext/js/ReadonlyArray.kt
> Regular cleanup

- kotlin-mui/src/main/generated/mui/material/PaletteMode.kt
- kotlin-mui/src/main/generated/mui/material/styles/createPalette.kt
> MUI. Strict `Palette` interfaces [generated]

- kotlin-react-dom/src/main/kotlin/react/dom/client/Root.kt
> React. Fix `Root` contract [generated]

- gradle.properties
- kotlin-styled-next/build.gradle.kts
- kotlin-typescript/build.gradle.kts
> Kotlin `1.6.20`. Preparing

- kotlin-browser/src/main/kotlin/org/w3c/dom/IntersectionObserver.kt
- kotlin-extensions/src/main/kotlin/kotlinx/js/Performance.kt
- kotlin-extensions/src/main/kotlin/kotlinx/js/TimeStamp.kt
[Documentation](https://developer.mozilla.org/en-US/docs/Web/API/DOMHighResTimeStamp)
cc @sgrishchenko @stefanthaler @aerialist7
> JS. `HighResTimeStamp`

- kotlin-extensions/src/main/kotlin/kotlinx/js/TimeStamp.kt
> JS. `HighResTimeStamp` docs

- kotlin-extensions/src/main/kotlin/kotlinx/js/TimeStamp.kt
> JS. Correct `TimeStamp`

- kotlin-mui/src/main/generated/mui/material/NativeSelect.kt
- kotlin-mui/src/main/generated/mui/material/PaginationItem.kt
- kotlin-mui/src/main/generated/mui/material/Select.kt
- kotlin-mui/src/main/generated/mui/material/SpeedDialAction.kt
- kotlin-mui/src/main/generated/mui/material/TextField.kt
> MUI. Strict handlers [generated]

- kotlin-mui/src/main/generated/mui/material/styles/createPalette.kt
- kotlin-mui/src/main/generated/mui/material/styles/createTransitions.kt
> MUI. Strict transition interfaces [generated]

- examples/src/main/kotlin/example/ForwardingRefs.kt
- examples/src/main/kotlin/example/Quill.kt
- examples/src/main/kotlin/example/ReactRouterDom.kt
- examples/src/main/kotlin/example/Todo.kt
> Examples. Use `VFC`

- kotlin-popper/src/main/generated/popper/core/modifiers/Arrow.kt
- kotlin-popper/src/main/generated/popper/core/modifiers/Offset.kt
- kotlin-popper/src/main/generated/popper/core/modifiers/PreventOverflow.kt
- kotlin-popper/src/main/kotlin/popper/core/modifiers/Arrow.ext.kt
- kotlin-popper/src/main/kotlin/popper/core/modifiers/Offset.ext.kt
- kotlin-popper/src/main/kotlin/popper/core/modifiers/OffsetsFunctionOptions.kt
- kotlin-popper/src/main/kotlin/popper/core/modifiers/PreventOverflow.ext.kt
- kotlin-popper/src/main/kotlin/popper/core/modifiers/Provider.kt
> Popper. Strict `PaddingType`, `OffsetType`, `TetherOffsetType` + factories

- kotlin-mui/src/main/generated/mui/material/Select.kt
> MUI. Fix `Select.onChange` type [generated]

- kotlin-styled-next/src/main/kotlin/styled/StructEffects.kt
- kotlin-styled-next/src/main/kotlin/styled/StyledComponents.kt
> Styled. Remove `useInsertionEffect` workaround

- kotlin-popper/src/main/kotlin/popper/core/modifiers/Arrow.ext.kt
- kotlin-popper/src/main/kotlin/popper/core/modifiers/Offset.ext.kt
- kotlin-popper/src/main/kotlin/popper/core/modifiers/PreventOverflow.ext.kt
> Popper. Rename provider factory methods

- gradle.properties
> Emotion `11.9.0`

- kotlin-react-query/src/main/kotlin/react/query/QueryKey.ext.kt
> React-Query. Add safe `QueryKey` factories

- kotlin-react-query/src/main/generated/react/query/types.core.kt
- kotlin-react-query/src/main/kotlin/react/query/QueryKey.ext.kt
> react-query. `QueryKey` -> interface [generated]

- kotlin-mui/src/main/generated/mui/material/styles/createTransitions.kt
- kotlin-mui/src/main/kotlin/mui/material/styles/createTransitions.ext.kt
> MUI. `Transition` factory

- gradle.properties
- kotlin-webrtc/src/main/generated/webrtc/RTCDtlsTransport.kt
- kotlin-webrtc/src/main/generated/webrtc/RTCDtlsTransportEventMap.kt
- kotlin-webrtc/src/main/generated/webrtc/RTCErrorDetailType.kt
> WebRTC `0.0.32` [generated]

- kotlin-mui/src/main/generated/mui/base/BadgeUnstyledProps.kt
- kotlin-mui/src/main/generated/mui/base/ButtonUnstyled.types.kt
- kotlin-mui/src/main/generated/mui/base/FormControlUnstyledProps.kt
- kotlin-mui/src/main/generated/mui/base/InputUnstyledProps.kt
- kotlin-mui/src/main/generated/mui/base/MenuItemUnstyled.types.kt
- kotlin-mui/src/main/generated/mui/base/MenuUnstyled.types.kt
- kotlin-mui/src/main/generated/mui/base/ModalUnstyled.kt
- kotlin-mui/src/main/generated/mui/base/MultiSelectUnstyled.types.kt
- kotlin-mui/src/main/generated/mui/base/OptionGroupUnstyledProps.kt
- kotlin-mui/src/main/generated/mui/base/OptionUnstyledProps.kt
- kotlin-mui/src/main/generated/mui/base/SelectUnstyled.types.kt
- kotlin-mui/src/main/generated/mui/base/SliderUnstyledProps.kt
- kotlin-mui/src/main/generated/mui/base/SwitchUnstyled.kt
- kotlin-mui/src/main/generated/mui/base/TabPanelUnstyledProps.kt
- kotlin-mui/src/main/generated/mui/base/TabUnstyledProps.kt
- kotlin-mui/src/main/generated/mui/base/TablePaginationUnstyledProps.kt
- kotlin-mui/src/main/generated/mui/base/TabsListUnstyledProps.kt
- kotlin-mui/src/main/generated/mui/base/TabsUnstyledProps.kt
- kotlin-mui/src/main/generated/mui/material/Autocomplete.kt
- kotlin-mui/src/main/generated/mui/material/AvatarGroup.kt
- kotlin-mui/src/main/generated/mui/material/Backdrop.kt
- kotlin-mui/src/main/generated/mui/material/InputBase.kt
- kotlin-mui/src/main/generated/mui/material/ListItem.kt
- kotlin-mui/src/main/generated/mui/material/PaginationItem.kt
- kotlin-mui/src/main/generated/mui/material/Tooltip.kt
- kotlin-mui/src/main/generated/muix/pickers/ClockPicker.kt
> MUI. `Components` and `ComponentProps` interfaces [generated]

- kotlin-browser/src/main/generated/org/w3c/dom/events/MouseEvent.types.kt
> Browser. Fix event type [generated]

- kotlin-history/src/main/generated/history/History.kt
- kotlin-history/src/main/generated/history/MemoryHistoryOptions.kt
- kotlin-history/src/main/generated/history/Update.kt
- kotlin-history/src/main/generated/history/createPath.kt
- kotlin-history/src/main/generated/history/parsePath.kt
> History. Cleanup [generated]

- kotlin-react-dom/build.gradle.kts
- kotlin-react-dom/src/main/generated/react/dom/events/NativeEvents.kt
> React DOM. Strict native events [generated]

- kotlin-mui/src/main/generated/mui/base/ButtonUnstyled.kt
- kotlin-mui/src/main/generated/mui/material/ButtonGroup.kt
- kotlin-mui/src/main/generated/mui/material/Collapse.kt
- kotlin-mui/src/main/generated/mui/material/Divider.kt
- kotlin-mui/src/main/generated/mui/material/TabScrollButton.kt
- kotlin-mui/src/main/generated/mui/material/Tabs.kt
- kotlin-mui/src/main/generated/mui/material/ToggleButtonGroup.kt
- kotlin-mui/src/main/generated/mui/system/Box.kt
> MUI. Cleanup [generated]

- kotlin-mui/src/main/generated/mui/material/Typography.kt
- kotlin-mui/src/main/generated/mui/material/styles/createTypography.ext.kt
> MUI. `TypographyVariant` [generated]

- kotlin-mui/src/main/generated/mui/system/ThemeProvider.kt
- kotlin-mui/src/main/generated/mui/system/createBreakpoints.kt
> MUI. Update [generated]

- kotlin-browser/src/main/generated/org/w3c/dom/events/Event.types.kt
> Browser. Strict `webkitfullscreenchange` event type [generated]

- kotlin-browser/src/main/kotlin/org/w3c/dom/events/EventTarget.kt
> Browser. Strict event handling

- gradle.properties
> React Query `3.34.20`

- kotlin-browser/src/main/kotlin/org/w3c/dom/events/CustomEvent.kt
> Browser. Strict `CustomEvent` factory method

- gradle.properties
- kotlin-react-query/src/main/generated/react/query/Hydrate.kt
- kotlin-react-query/src/main/generated/react/query/QueryClientProvider.kt
> React Query `3.35.0` [generated]

- kotlin-csstype/src/main/kotlin/csstype/many.kt
> CSSType. `many` helper [generated]

- kotlin-csstype/src/main/generated/csstype/TextShadow.kt
> CSSType. `TextShadow` factories [generated]

- gradle.properties
> Kotlin `1.6.21`

- kotlin-mui/src/main/generated/mui/system/ResponsiveStyleValue.kt
> MUI. `responsive` helper [generated]

- kotlin-styled-next/build.gradle.kts
> Gradle. Use strict DSL

- gradle.properties
> React Query `3.37.0`

- gradle.properties
- kotlin-react-query/src/main/generated/react/query/types.core.kt
> React Query `3.38.0` [generated]

- kotlin-extensions/src/main/kotlin/kotlinx/js/Symbol.kt
[MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol)
[Related discussion](https://kotlinlang.slack.com/archives/C0B8L3U69/p1650608714364029)
> `Symbol` static properties

- kotlin-extensions/src/main/kotlin/kotlinx/js/AsyncIterator.kt
- kotlin-extensions/src/main/kotlin/kotlinx/js/JsIterator.kt
> JS. `AsyncIterator`

- gradle.properties
- kotlin-mui/src/main/generated/mui/material/Box.kt
- kotlin-mui/src/main/generated/mui/material/DialogTitle.kt
- kotlin-mui/src/main/generated/mui/material/StepContent.kt
- kotlin-mui/src/main/generated/mui/system/Box.kt
- kotlin-mui/src/main/generated/mui/system/ThemeProvider.kt
> MUI `5.6.3` [generated]

- kotlin-react-dom/src/main/generated/react/dom/html/LinkHTMLAttributes.kt
> React Types `18.0.8` [generated]

- buildSrc/src/main/kotlin/Projects.kt
> Remove Kotlin version suffix

- kotlin-browser/src/main/kotlin/org/w3c/dom/clipboard/Clipboard.kt
- kotlin-browser/src/main/kotlin/org/w3c/dom/clipboard/ClipboardItem.kt
- kotlin-browser/src/main/kotlin/org/w3c/dom/clipboard/ClipboardItemDataType.kt
- kotlin-browser/src/main/kotlin/org/w3c/dom/clipboard/ClipboardItems.kt
- kotlin-browser/src/main/kotlin/org/w3c/dom/clipboard/PresentationStyle.kt
[Related issue](https://youtrack.jetbrains.com/issue/KT-52211)
cc @aerialist7
> Browser. Actualize `Clipboard` API

- gradle.properties
- kotlin-mui/src/main/generated/mui/base/FormControlUnstyled.kt
- kotlin-mui/src/main/generated/mui/material/Tabs.kt
> MUI `5.6.4` [generated]

- kotlin-mui/src/main/generated/muix/pickers/CalendarPicker.kt
- kotlin-mui/src/main/generated/muix/pickers/CalendarPickerSkeleton.kt
- kotlin-mui/src/main/generated/muix/pickers/ClockPicker.kt
- kotlin-mui/src/main/generated/muix/pickers/DatePicker.kt
- kotlin-mui/src/main/generated/muix/pickers/DateTimePicker.kt
- kotlin-mui/src/main/generated/muix/pickers/DesktopDatePicker.kt
- kotlin-mui/src/main/generated/muix/pickers/DesktopDateTimePicker.kt
- kotlin-mui/src/main/generated/muix/pickers/DesktopTimePicker.kt
- kotlin-mui/src/main/generated/muix/pickers/LocalizationProvider.kt
- kotlin-mui/src/main/generated/muix/pickers/MobileDatePicker.kt
- kotlin-mui/src/main/generated/muix/pickers/MobileDateTimePicker.kt
- kotlin-mui/src/main/generated/muix/pickers/MobileTimePicker.kt
- kotlin-mui/src/main/generated/muix/pickers/MonthPicker.kt
- kotlin-mui/src/main/generated/muix/pickers/PickersDay.kt
- kotlin-mui/src/main/generated/muix/pickers/StaticDatePicker.kt
- kotlin-mui/src/main/generated/muix/pickers/StaticDateTimePicker.kt
- kotlin-mui/src/main/generated/muix/pickers/StaticTimePicker.kt
- kotlin-mui/src/main/generated/muix/pickers/TimePicker.kt
- kotlin-mui/src/main/generated/muix/pickers/YearPicker.kt
> MUI. Fix 'picker' components resolving [generated]

- kotlin-react-dom/src/main/generated/react/dom/html/DialogHTMLAttributes.kt
> React Types `18.0.9` [generated]

- kotlin-cesium/src/main/generated/cesium/Camera.kt
- kotlin-cesium/src/main/generated/cesium/CameraOrientation.kt
- kotlin-cesium/src/main/generated/cesium/DirectionUp.kt
- kotlin-cesium/src/main/generated/cesium/HeadingPitchRollValues.kt
> Cesium. Restore `CameraOrientation` [generated]

- gradle.properties
> React Query `3.39.0`

- gradle.properties
> BOM `1.0.0`

- kotlin-react/src/main/kotlin/react/ChildrenBuilder.kt
> React. Short `Provider` configuration

- kotlin-react-core/src/main/kotlin/react/Context.kt
[Source](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/001590985667e962603b9d10a6d119f4d8597add/types/react/index.d.ts#L371)
> React. Add `Context.displayName`

- kotlin-mui/src/main/generated/muix/pickers/AdapterDateFns.kt
- kotlin-mui/src/main/generated/muix/pickers/AdapterDayjs.kt
- kotlin-mui/src/main/generated/muix/pickers/AdapterLuxon.kt
- kotlin-mui/src/main/generated/muix/pickers/AdapterMoment.kt
- kotlin-mui/src/main/generated/muix/pickers/DateAdapter.kt
- kotlin-mui/src/main/generated/muix/pickers/LocalizationProvider.kt
> MUI. Date Adapters [generated]

- gradle.properties
> React Table `7.8.0`

- gradle.properties
- kotlin-react-query/src/main/generated/react/query/types.core.kt
> React Query `3.39.1` [generated]

- kotlin-react-core/src/main/kotlin/react/memo.kt
> React. Fix `memo` signature

- kotlin-react-core/src/main/kotlin/react/memo.kt
> React. Fix `memo` return type

- kotlin-emotion/src/main/kotlin/emotion/css/ClassName.kt
- kotlin-emotion/src/main/kotlin/emotion/react/css.kt
> Emotion. `ClassName` factories

- kotlin-csstype/src/main/generated/csstype/CssDsl.kt
- kotlin-extensions/src/main/kotlin/kotlinx/js/JsoDsl.kt
- kotlin-extensions/src/main/kotlin/kotlinx/js/jso.kt
- kotlin-react-core/src/main/kotlin/react/ReactDsl.kt
> `JsoDsl` - common DSL annotation

- kotlin-react-router-dom/src/main/generated/react/router/LocationContext.kt
- kotlin-react-router-dom/src/main/generated/react/router/NavigationContext.kt
- kotlin-react-router-dom/src/main/generated/react/router/Navigator.kt
- kotlin-react-router-dom/src/main/generated/react/router/RouteContext.kt
- kotlin-react-router-dom/src/main/generated/react/router/RouteContextObject.kt
- kotlin-react-router-dom/src/main/generated/react/router/matchPath.kt
- kotlin-react-router-dom/src/main/generated/react/router/matchRoutes.kt
- kotlin-react-router-dom/src/main/generated/react/router/renderMatches.kt
- kotlin-react-router-dom/src/main/generated/react/router/stripBasename.kt
- kotlin-react-router-dom/src/main/generated/react/router/useMatch.kt
- kotlin-react-router-dom/src/main/generated/react/router/useOutlet.kt
- kotlin-react-router-dom/src/main/generated/react/router/useRoutes.kt
> React Router. Fix imports and nullability

- kotlin-history/src/main/generated/history/Location.kt
- kotlin-history/src/main/generated/history/State.kt
- kotlin-react-router-dom/src/main/generated/react/router/NavigateOptions.kt
- kotlin-react-router-dom/src/main/generated/react/router/NavigateProps.kt
- kotlin-react-router-dom/src/main/generated/react/router/dom/LinkProps.kt
- kotlin-react-router-dom/src/main/generated/react/router/dom/useLinkClickHandler.kt
> React Router. `LocationState` [generated]

- README.md
- gradle.properties
- kotlin-css/src/commonMain/kotlin/kotlinx/css/Rule.kt
- kotlin-styled-next/src/main/kotlin/styled/StyledCss.kt
> Kotlin `1.7.0`

- gradle.properties
- kotlin-mui/src/main/generated/mui/material/InputLabel.kt
- kotlin-mui/src/main/generated/mui/material/MenuList.kt
- kotlin-mui/src/main/generated/mui/material/Size.kt
> MUI. 5.8.2 [generated]

- gradle.properties
> Emotion `11.9.3`

- kotlin-react-core/src/main/kotlin/react/Context.kt
> Non-nullable context can't be created without default value

- kotlin-react-core/src/main/kotlin/react/useRequiredContext.kt
Related - #1526
сс @Leonya @aerialist7
> React. Add `useRequiredContext` hook

- gradle.properties
> MUI `5.8.3`

- kotlin-react-core/src/main/kotlin/react/Context.kt
- kotlin-react-core/src/main/kotlin/react/useRequiredContext.kt
> React. Restore strict provider behaviour

- gradle.properties
> React `18.2.0`

- kotlin-extensions/src/main/kotlin/kotlinx/js/Object.kt
> `Object.is()`

- kotlin-react-core/src/main/kotlin/react/Dependencies.kt
- kotlin-react-core/src/main/kotlin/react/RefCallback.kt
- kotlin-react-core/src/main/kotlin/react/useCallback.kt
- kotlin-react-core/src/main/kotlin/react/useEffect.kt
- kotlin-react-core/src/main/kotlin/react/useImperativeHandle.kt
- kotlin-react-core/src/main/kotlin/react/useInsertionEffect.kt
- kotlin-react-core/src/main/kotlin/react/useLayoutEffect.kt
- kotlin-react-core/src/main/kotlin/react/useMemo.kt
- kotlin-styled-next/src/main/kotlin/styled/StructEffects.kt
> Strict `dependencies` contract

- buildSrc/src/main/kotlin/publish-conventions.gradle.kts
> Use valid source task

- kotlin-mui/src/main/generated/muix/pickers/LocalizationProvider.kt
> MUI. Restore `LocalizationProvider` [generated]

- kotlin-js/src/main/kotlin/kotlinx/js/Module.kt
- kotlin-js/src/main/kotlin/kotlinx/js/import.kt
- kotlin-react-core/src/main/kotlin/react/ComponentModule.kt
- kotlin-react-core/src/main/kotlin/react/lazy.kt
Unlocked in [Kotlin 1.7.0](https://kotlinlang.org/docs/whatsnew17.html#dynamically-load-javascript-modules-from-js-expressions)
> JS `import`

- kotlin-js/src/main/kotlin/kotlinx/js/JsClass.kt
> `JsClass.newInstance()`

- gradle.properties
> MUIX Date Pickers `5.0.0-alpha.7`

- kotlin-browser/src/main/kotlin/org/w3c/dom/HTML.kt
- kotlin-browser/src/main/kotlin/org/w3c/dom/TagName.kt
> Browser. `TagName`

- kotlin-browser/src/main/kotlin/org/w3c/dom/Document.kt
> Strict `Document.createElement(tagName)`

- kotlin-csstype/src/main/generated/csstype/RuleBuilder.kt
> CSSType. Add `RuleBuilder.and` function

- kotlin-mui/src/main/generated/mui/base/BadgeUnstyled.types.kt
- kotlin-mui/src/main/generated/mui/base/ButtonUnstyled.types.kt
- kotlin-mui/src/main/generated/mui/base/FormControlUnstyled.types.kt
- kotlin-mui/src/main/generated/mui/base/InputUnstyled.types.kt
- kotlin-mui/src/main/generated/mui/base/SliderUnstyled.types.kt
- kotlin-mui/src/main/generated/mui/base/TabPanelUnstyled.types.kt
- kotlin-mui/src/main/generated/mui/base/TabUnstyled.types.kt
- kotlin-mui/src/main/generated/mui/base/TabsListUnstyled.types.kt
- kotlin-mui/src/main/generated/mui/base/TabsUnstyled.types.kt
- kotlin-mui/src/main/generated/mui/material/Grid.kt
- kotlin-mui/src/main/generated/mui/system/createSpacing.ext.kt
> MUI. Restore `Props` hierarchy

- kotlin-react-core/src/main/kotlin/react/Context.kt
- kotlin-react-core/src/main/kotlin/react/FC.kt
- kotlin-react-core/src/main/kotlin/react/NamedExoticComponent.kt
- kotlin-react-core/src/main/kotlin/react/displayName.kt
> React. `displayName` - write-only extension property

- kotlin-react-core/src/main/kotlin/react/displayName.kt
> React. `displayName` - regular extension property

- kotlin-js/src/main/kotlin/kotlinx/js/import.kt
> JS. `import.meta` declarations

- gradle.properties
> Fix versions

- kotlin-mui/src/main/generated/dateio/core/IUtils.kt
- kotlin-mui/src/main/generated/muix/pickers/DateAdapter.kt
> MUI. `DateAdapter` [generated]

- gradle.properties
- kotlin-mui/src/main/generated/mui/base/TablePaginationUnstyled.types.kt
- kotlin-mui/src/main/generated/mui/base/useAutocomplete.kt
- kotlin-mui/src/main/generated/mui/material/Autocomplete.kt
- kotlin-mui/src/main/generated/mui/material/Select.kt
> MUI `5.8.7` [generated]

- kotlin-tanstack-react-virtual/build.gradle.kts
- kotlin-tanstack-react-virtual/src/main/kotlin/tanstack/react/virtual/useVirtualizer.kt
- kotlin-tanstack-react-virtual/src/main/kotlin/tanstack/react/virtual/useWindowVirtualizer.kt
> React Virtual. Hooks [generated]

- README.md
- gradle.properties
> Kotlin `1.7.10`

- gradle.properties
> MUI Pickers `5.0.0-beta.0`

- kotlin-tanstack-react-table/src/main/generated/tanstack/table/core/TableOptions.kt
> React Table. `TableOptions` [generated]

- kotlin-tanstack-react-table/src/main/generated/tanstack/table/core/ColumnPinningPosition.kt
- kotlin-tanstack-react-table/src/main/generated/tanstack/table/core/GroupingColumnMode.kt
- kotlin-tanstack-react-table/src/main/generated/tanstack/table/core/GroupingOptions.kt
> React Table. Unions [generated]

- kotlin-popper/src/main/generated/popper/core/State.kt
> Popper. State [generated]

- kotlin-popper/src/main/generated/popper/core/VirtualElement.kt
- kotlin-popper/src/main/kotlin/popper/core/ReferenceElement.kt
- kotlin-react-popper/src/main/kotlin/react/popper/Popper.kt
- kotlin-react-popper/src/main/kotlin/react/popper/Reference.kt
- kotlin-react-popper/src/main/kotlin/react/popper/ReferenceElement.kt
- kotlin-react-popper/src/main/kotlin/react/popper/usePopper.kt
> Popper. `ReferenceElement`

- kotlin-tanstack-react-table/src/main/generated/tanstack/table/core/CoreColumnDef.kt
- kotlin-tanstack-react-table/src/main/generated/tanstack/table/core/CoreColumnDefAccessorKey.kt
- kotlin-tanstack-react-table/src/main/generated/tanstack/table/core/CoreColumnDefDisplayWithStringHeader.kt
> React Table. `CoreColumnDef` [generated]

- gradle.properties
> React Table `8.2.3`

- kotlin-tanstack-react-table/src/main/generated/tanstack/table/core/RowData.kt
> React Table. Fix `RowData` [generated]

- kotlin-tanstack-react-table/src/main/kotlin/tanstack/react/table/flexRender.kt
> React Table. Fix `flexRender` signature

- kotlin-tanstack-react-table/src/main/kotlin/tanstack/react/table/ColumnDefTemplate.kt
> React Table. Add `ColumnDefTemplate` react adapter

- kotlin-tanstack-react-table/src/main/generated/tanstack/table/core/CoreColumnDefBase.kt
- kotlin-tanstack-react-table/src/main/generated/tanstack/table/core/GroupingColumnDef.kt
- kotlin-tanstack-react-table/src/main/kotlin/tanstack/react/table/ColumnDefTemplate.kt
cc @stefanthaler @sgrishchenko
> React Table. Fix `ColumnDefTemplate` usage

- gradle.properties
> React Table `8.2.4`

- gradle.properties
- kotlin-mui/src/main/generated/mui/base/ModalUnstyled.types.kt
- kotlin-mui/src/main/generated/mui/base/MultiSelectUnstyled.types.kt
- kotlin-mui/src/main/generated/mui/base/OptionGroupUnstyled.types.kt
- kotlin-mui/src/main/generated/mui/base/OptionUnstyled.types.kt
- kotlin-mui/src/main/generated/mui/base/SelectUnstyled.types.kt
- kotlin-mui/src/main/generated/mui/base/TabPanelUnstyled.types.kt
- kotlin-mui/src/main/generated/mui/base/TabUnstyled.types.kt
- kotlin-mui/src/main/generated/mui/base/TabsListUnstyled.types.kt
- kotlin-mui/src/main/generated/mui/base/TabsUnstyled.types.kt
- kotlin-mui/src/main/generated/mui/material/ScopedCssBaseline.kt
> MUI `5.9.0` [generated]

- gradle.properties
- kotlin-react-dom-legacy/src/main/kotlin/react/dom/EventHandlerAdapters.kt
- kotlin-react-dom-legacy/src/main/kotlin/react/dom/RDOMBuilder.kt
> kotlinx.html `0.8.0`

- kotlin-tanstack-react-table/src/main/generated/tanstack/table/core/ExpandedOptions.kt
- kotlin-tanstack-react-table/src/main/generated/tanstack/table/core/FiltersOptions.kt
- kotlin-tanstack-react-table/src/main/generated/tanstack/table/core/GroupingOptions.kt
- kotlin-tanstack-react-table/src/main/generated/tanstack/table/core/PaginationOptions.kt
- kotlin-tanstack-react-table/src/main/generated/tanstack/table/core/SortingOptions.kt
- kotlin-tanstack-react-table/src/main/generated/tanstack/table/core/TableOptionsResolved.kt
> React Table. Strict options [generated]

- gradle.properties
> MUI Pickers `5.0.0-beta.1`

- kotlin-csstype/src/main/kotlin/csstype/PropertiesBuilder.kt
cc @stefanthaler @sgrishchenko
> CSSType. `+Properties` support for `PropertiesBuilder`

- kotlin-mui/src/main/generated/muix/pickers/DateAdapter.kt
> MUI. Fix `DateAdapter` signature [generated]

- gradle.properties
- kotlin-tanstack-react-virtual/build.gradle.kts
> React Virtual `3.0.0-beta.12`

- gradle.properties
- kotlin-mui/src/main/generated/mui/base/useButton.types.kt
- kotlin-mui/src/main/generated/mui/base/useInput.types.kt
> MUI `5.9.1` [generated]

- gradle.properties
> React Table `8.3.1`

- gradle.properties
- kotlin-tanstack-react-table/src/main/generated/tanstack/table/core/ColumnMeta.kt
- kotlin-tanstack-react-table/src/main/generated/tanstack/table/core/CoreColumnDefBase.kt
> React Table `8.3.2` [generated]

- gradle.properties
> React Table `8.3.3`

- gradle.properties
> MUI Pickers `5.0.0-beta.2`

- kotlin-csstype/src/main/generated/csstype/Ident.kt
- kotlin-csstype/src/main/generated/csstype/Transition.kt
> CSSType. `Transition` factories [generated]

- kotlin-csstype/src/main/generated/csstype/Animation.kt
> CSSType. `Animation` factories [generated]

- kotlin-tanstack-table-core/src/main/generated/tanstack/table/core/AggregationFnOption.kt
- kotlin-tanstack-table-core/src/main/generated/tanstack/table/core/AggregationFns.type.kt
- kotlin-tanstack-table-core/src/main/generated/tanstack/table/core/FilterFnOption.kt
- kotlin-tanstack-table-core/src/main/generated/tanstack/table/core/FilterFns.type.kt
- kotlin-tanstack-table-core/src/main/generated/tanstack/table/core/SortingFnOption.kt
- kotlin-tanstack-table-core/src/main/generated/tanstack/table/core/SortingFns.type.kt
> React Table `8.5.2` [generated]

- gradle.properties
Beta channel must be used
cc @aerialist7
> Fix `@tanstack/virtual-core` version

- gradle.properties
> MUI Lab `5.0.0-alpha.92`, MUI Pickers `5.0.0-beta.3`

- examples/src/main/kotlin/example/AxiosSearch.kt
- examples/src/main/kotlin/example/TicTacToe.kt
- kotlin-mui/src/main/generated/mui/material/Autocomplete.kt
- kotlin-react-core/src/main/kotlin/react/Props.kt
- kotlin-react-table/src/main/kotlin/react/table/Table.kt
> React. `key` - regular `Props` property

- gradle.properties
> Emotion `11.10.0`

- kotlin-react-core/src/main/kotlin/react/Props.kt
- kotlin-react-legacy/src/main/kotlin/react/Props.ext.kt
> React. `Props.ref` extension - legacy

- gradle.properties
- kotlin-cesium/src/main/generated/cesium/Cesium3DTileset.kt
- kotlin-cesium/src/main/generated/cesium/CesiumWidget.kt
- kotlin-cesium/src/main/generated/cesium/Model.kt
- kotlin-cesium/src/main/generated/cesium/ModelExperimental.kt
- kotlin-cesium/src/main/generated/cesium/ModelExperimentalNode.kt
- kotlin-cesium/src/main/generated/cesium/TileProviderError.kt
- kotlin-cesium/src/main/generated/cesium/Viewer.kt
- kotlin-cesium/src/main/generated/cesium/createOsmBuildings.kt
> Cesium `1.96.0` [generated]

- gradle.properties
- kotlin-tanstack-table-core/src/main/generated/tanstack/table/core/AccessorColumnDef.kt
- kotlin-tanstack-table-core/src/main/generated/tanstack/table/core/AccessorFnColumnDef.kt
- kotlin-tanstack-table-core/src/main/generated/tanstack/table/core/AccessorKeyColumnDef.kt
- kotlin-tanstack-table-core/src/main/generated/tanstack/table/core/ColumnDef.kt
- kotlin-tanstack-table-core/src/main/generated/tanstack/table/core/ColumnDefBase.kt
- kotlin-tanstack-table-core/src/main/generated/tanstack/table/core/ColumnDefResolved.kt
- kotlin-tanstack-table-core/src/main/generated/tanstack/table/core/ColumnIdentifiers.kt
- kotlin-tanstack-table-core/src/main/generated/tanstack/table/core/CoreColumnDef.kt
- kotlin-tanstack-table-core/src/main/generated/tanstack/table/core/CoreColumnDefAccessorFn.kt
- kotlin-tanstack-table-core/src/main/generated/tanstack/table/core/CoreColumnDefAccessorKey.kt
- kotlin-tanstack-table-core/src/main/generated/tanstack/table/core/CoreColumnDefDisplay.kt
- kotlin-tanstack-table-core/src/main/generated/tanstack/table/core/CoreColumnDefDisplayWithStringHeader.kt
- kotlin-tanstack-table-core/src/main/generated/tanstack/table/core/CoreColumnDefResolved.kt
- kotlin-tanstack-table-core/src/main/generated/tanstack/table/core/DisplayColumnDef.kt
- kotlin-tanstack-table-core/src/main/generated/tanstack/table/core/GroupColumnDef.kt
- kotlin-tanstack-table-core/src/main/generated/tanstack/table/core/IdIdentifier.kt
- kotlin-tanstack-table-core/src/main/generated/tanstack/table/core/IdentifiedColumnDef.kt
- kotlin-tanstack-table-core/src/main/generated/tanstack/table/core/StringHeaderIdentifier.kt
- kotlin-tanstack-table-core/src/main/generated/tanstack/table/core/StringOrTemplateHeader.kt
> React Table `8.5.5` [generated]

- kotlin-react-dom/src/main/generated/react/dom/svg/ReactSVG.kt
> React. Use `IntrinsicType` factory [generated]

- gradle.properties
- kotlin-tanstack-virtual-core/src/main/generated/tanstack/virtual/core/ScrollToOptions.kt
> Tanstack Virtual `3.0.0-beta.17` [generated]

- gradle.properties
- kotlin-tanstack-table-core/src/main/generated/tanstack/table/core/AccessorColumnDef.kt
- kotlin-tanstack-table-core/src/main/generated/tanstack/table/core/AccessorKeyColumnDef.kt
- kotlin-tanstack-table-core/src/main/generated/tanstack/table/core/ColumnDef.kt
- kotlin-tanstack-table-core/src/main/generated/tanstack/table/core/ColumnIdentifiers.kt
> Tanstack Table. Restore `ColumnDef` [generated]

- kotlin-csstype/src/main/generated/csstype/Font.kt
cc @sgrishchenko @aerialist7 @stefanthaler
> CSSType. `Font` factories [generated]

- kotlin-tanstack-react-table/src/main/kotlin/tanstack/react/table/flexRender.kt
> Tanstack Table. Missed `flexRender` declaration

- kotlin-tanstack-react-table/src/main/kotlin/tanstack/react/table/render.kt
> Tanstack Table. Render methods

- gradle.properties
- kotlin-tanstack-table-core/src/main/generated/tanstack/table/core/expandRows.kt
> Tanstack Table `8.5.10` [generated]

- kotlin-browser/src/main/kotlin/org/w3c/fetch/AbortController.kt
- kotlin-browser/src/main/kotlin/org/w3c/fetch/AbortSignal.kt
- kotlin-js/src/main/kotlin/kotlinx/js/AbortController.kt
- kotlin-js/src/main/kotlin/kotlinx/js/AbortSignal.kt
- kotlin-node/src/main/kotlin/node/AbortController.kt
- kotlin-node/src/main/kotlin/node/AbortSignal.kt
Related - #1644
cc @sgrishchenko @vlsi @aerialist7
> JS. Common `AbortController` and `AbortSignal`

- gradle.properties
- kotlin-tanstack-table-core/src/main/generated/tanstack/table/core/AccessorKeyColumnDef.kt
> Tanstack Table `8.5.11` [generated]

- kotlin-browser/src/main/generated/org/w3c/dom/events/Event.types.kt
> Browser. Events [generated]

- kotlin-mui/src/main/generated/mui/material/Autocomplete.kt
- kotlin-mui/src/main/generated/mui/material/Popover.kt
- kotlin-mui/src/main/generated/mui/material/Slide.kt
> MUI. Correct `anchor` type [generated]

- kotlin-react-dom/src/main/generated/react/dom/html/FormHTMLAttributes.kt
> React Types `18.0.16` [generated]

- gradle.properties
> MUI Lab `5.0.0-alpha.93`, MUI Pickers `5.0.0-beta.4`

- kotlin-node/src/main/generated/node/fs/CreateReadStreamOptions.kt
- kotlin-node/src/main/generated/node/fs/CreateWriteStreamOptions.kt
- kotlin-node/src/main/generated/node/fs/FileChangeInfo.kt
- kotlin-node/src/main/generated/node/fs/FileReadOptions.kt
- kotlin-node/src/main/generated/node/fs/FileReadResult.kt
- kotlin-node/src/main/generated/node/fs/FlagAndOpenMode.kt
- kotlin-node/src/main/generated/node/fs/WatchEventType.kt
> Node. `fs/promises` interfaces [generated]

- kotlin-node/src/main/generated/node/fs/BigIntOptions.kt
- kotlin-node/src/main/generated/node/fs/BigIntStats.kt
- kotlin-node/src/main/generated/node/fs/FileHandle.kt
- kotlin-node/src/main/generated/node/fs/FileReadOptions.kt
- kotlin-node/src/main/generated/node/fs/FileReadResult.kt
- kotlin-node/src/main/generated/node/fs/ReadAsyncOptions.kt
- kotlin-node/src/main/generated/node/fs/ReadStream.kt
- kotlin-node/src/main/generated/node/fs/ReadVResult.kt
- kotlin-node/src/main/generated/node/fs/WriteStream.kt
- kotlin-node/src/main/generated/node/fs/WriteVResult.kt
- kotlin-node/src/main/generated/node/fs/readSync.kt
- kotlin-node/src/main/generated/node/fs/readvSync.kt
- kotlin-node/src/main/generated/node/fs/writevSync.kt
- kotlin-node/src/main/generated/node/stream/ReadableStream.kt
> Node. `FileHandle` [generated]

- kotlin-node/build.gradle.kts
> Node. Add `coroutines` dependency

- kotlin-node/src/main/generated/node/fs/BufferEncodingOption.kt
- kotlin-node/src/main/generated/node/fs/FileHandle.kt
- kotlin-node/src/main/generated/node/fs/lutimes.kt
- kotlin-node/src/main/generated/node/fs/lutimesAsync.kt
- kotlin-node/src/main/generated/node/fs/utimes.kt
- kotlin-node/src/main/generated/node/fs/utimesAsync.kt
> Node. Use `TimeLike` alias [generated]

- kotlin-js/src/main/kotlin/kotlinx/js/PromiseResult.kt
> JS. Add `PromiseResult` interface

- kotlin-js/src/main/kotlin/kotlinx/js/Promise.kt
> JS. Void `Promise.resolve()`

- kotlin-node/src/main/generated/node/buffer/Buffer.kt
> Node. `Buffer` [generated]

- kotlin-node/src/main/generated/node/fs/createReadStream.kt
- kotlin-node/src/main/generated/node/fs/createWriteStream.kt
> Node. `fs` stream factory methods [generated]

- kotlin-node/src/main/generated/node/os/CpuInfo.kt
- kotlin-node/src/main/generated/node/os/NetworkInterfaceBase.kt
- kotlin-node/src/main/generated/node/os/NetworkInterfaceInfo.kt
- kotlin-node/src/main/generated/node/os/NetworkInterfaceInfoIPv4.kt
- kotlin-node/src/main/generated/node/os/NetworkInterfaceInfoIPv6.kt
- kotlin-node/src/main/generated/node/os/UserInfo.kt
- kotlin-node/src/main/generated/node/os/arch.kt
- kotlin-node/src/main/generated/node/os/cpus.kt
- kotlin-node/src/main/generated/node/os/endianness.kt
- kotlin-node/src/main/generated/node/os/freemem.kt
- kotlin-node/src/main/generated/node/os/getPriority.kt
- kotlin-node/src/main/generated/node/os/homedir.kt
- kotlin-node/src/main/generated/node/os/hostname.kt
- kotlin-node/src/main/generated/node/os/loadavg.kt
- kotlin-node/src/main/generated/node/os/networkInterfaces.kt
- kotlin-node/src/main/generated/node/os/platform.kt
- kotlin-node/src/main/generated/node/os/release.kt
- kotlin-node/src/main/generated/node/os/setPriority.kt
- kotlin-node/src/main/generated/node/os/tmpdir.kt
- kotlin-node/src/main/generated/node/os/totalmem.kt
- kotlin-node/src/main/generated/node/os/type.kt
- kotlin-node/src/main/generated/node/os/uptime.kt
- kotlin-node/src/main/generated/node/os/version.kt
- kotlin-node/src/main/generated/node/process/Platform.kt
> Node. `os` [generated]

- kotlin-node/src/main/generated/node/Dict.kt
- kotlin-node/src/main/generated/node/ReadOnlyDict.kt
- kotlin-node/src/main/generated/node/os/networkInterfaces.kt
> Node. `Dict` & `ReadOnlyDict` [generated]

- kotlin-node/src/main/generated/node/url/URL.alias.kt
- kotlin-node/src/main/generated/node/url/URLFormatOptions.kt
- kotlin-node/src/main/generated/node/url/URLSearchParams.alias.kt
- kotlin-node/src/main/generated/node/url/Url.kt
- kotlin-node/src/main/generated/node/url/UrlObject.kt
- kotlin-node/src/main/generated/node/url/domainToASCII.kt
- kotlin-node/src/main/generated/node/url/domainToUnicode.kt
- kotlin-node/src/main/generated/node/url/fileURLToPath.kt
- kotlin-node/src/main/generated/node/url/format.kt
- kotlin-node/src/main/generated/node/url/parse.kt
- kotlin-node/src/main/generated/node/url/pathToFileURL.kt
- kotlin-node/src/main/generated/node/url/resolve.kt
- kotlin-node/src/main/generated/node/url/urlToHttpOptions.kt
> Node. `url` [generated]

- kotlin-node/src/main/generated/node/AbortController.kt
- kotlin-node/src/main/generated/node/AbortSignal.kt
> Node. `AbortController` & `AbortSignal` [generated]

- examples/src/main/kotlin/example/ReactRouterDom.kt
- kotlin-csstype/src/main/generated/csstype/RuleBuilder.kt
- kotlin-emotion/src/main/kotlin/emotion/css/keyframes.ext.kt
- kotlin-js/src/main/kotlin/kotlinx/js/Record.kt
- kotlin-mui/src/main/generated/mui/system/ResponsiveStyleValue.kt
> JS. Open external `Record`

- kotlin-node/src/main/generated/node/events/DOMEventTarget.kt
- kotlin-node/src/main/generated/node/events/EventEmitterOptions.kt
- kotlin-node/src/main/generated/node/events/IEventEmitter.kt
- kotlin-node/src/main/generated/node/events/NodeEventTarget.kt
- kotlin-node/src/main/generated/node/events/StaticEventEmitterOptions.kt
> Node. `events` interface [generated]

- kotlin-node/src/main/generated/node/events/EventEmitter.kt
- kotlin-node/src/main/generated/node/events/IEventEmitter.kt
- kotlin-node/src/main/generated/node/process/Process.kt
> Node. `EventEmitter` [generated]

- kotlin-browser/src/main/kotlin/org/w3c/fetch/RequestInit.kt
- kotlin-js/src/main/kotlin/kotlinx/js/Request.kt
- kotlin-js/src/main/kotlin/kotlinx/js/RequestInit.kt
- kotlin-js/src/main/kotlin/kotlinx/js/fetchAsync.kt
> JS. `fetchAsync`

- kotlin-js/build.gradle.kts
- kotlin-js/src/main/kotlin/kotlinx/js/fetch.kt
- kotlin-js/src/main/kotlin/kotlinx/js/fetchAsync.kt
> JS. Suspend `fetch`

- kotlin-js/src/main/kotlin/kotlinx/js/Request.kt
- kotlin-js/src/main/kotlin/kotlinx/js/fetch.kt
> JS. Fix `Request.signal` contract

- kotlin-node/src/main/generated/node/events/Event.kt
> Node. `Event` [generated]

- kotlin-node/src/main/generated/node/events/IEventEmitter.kt
- kotlin-node/src/main/generated/node/events/NodeEventTarget.kt
- kotlin-node/src/main/generated/node/process/BeforeExitListener.kt
- kotlin-node/src/main/generated/node/process/DisconnectListener.kt
- kotlin-node/src/main/generated/node/process/ExitListener.kt
- kotlin-node/src/main/generated/node/process/MessageListener.kt
- kotlin-node/src/main/generated/node/process/MultipleResolveListener.kt
- kotlin-node/src/main/generated/node/process/Process.kt
- kotlin-node/src/main/generated/node/process/RejectionHandledListener.kt
- kotlin-node/src/main/generated/node/process/SignalsListener.kt
- kotlin-node/src/main/generated/node/process/UncaughtExceptionListener.kt
- kotlin-node/src/main/generated/node/process/UnhandledRejectionListener.kt
- kotlin-node/src/main/generated/node/process/WarningListener.kt
- kotlin-node/src/main/generated/node/process/WorkerListener.kt
> Node. Fix `Process` [generated]

- kotlin-js/src/main/kotlin/kotlinx/js/FetchException.kt
- kotlin-js/src/main/kotlin/kotlinx/js/fetch.kt
> JS. `FetchException` - specific exception for `fetch`

- kotlin-node/src/main/generated/node/fs/FileHandle.kt
- kotlin-node/src/main/generated/node/fs/appendFile.kt
- kotlin-node/src/main/generated/node/fs/appendFileAsync.kt
- kotlin-node/src/main/generated/node/fs/readFile.kt
- kotlin-node/src/main/generated/node/fs/readFileAsync.kt
- kotlin-node/src/main/generated/node/fs/watch.kt
- kotlin-node/src/main/generated/node/fs/writeFile.kt
- kotlin-node/src/main/generated/node/fs/writeFileAsync.kt
> Node. `readFile` & `writeFile` [generated]

- kotlin-node/src/main/generated/node/CallSite.kt
- kotlin-node/src/main/generated/node/ErrnoException.kt
- kotlin-node/src/main/generated/node/Module.kt
- kotlin-node/src/main/generated/node/ReadWriteStream.kt
- kotlin-node/src/main/generated/node/ReadableStream.kt
- kotlin-node/src/main/generated/node/RefCounted.kt
- kotlin-node/src/main/generated/node/RequireResolve.kt
- kotlin-node/src/main/generated/node/WritableStream.kt
- kotlin-node/src/main/generated/node/process/Process.kt
> Node. `globals` interfaces [generated]

- kotlin-node/src/main/generated/node/events/Event.kt
- kotlin-node/src/main/generated/node/inspector/ConsoleEvent.kt
- kotlin-node/src/main/generated/node/inspector/DebuggerEvent.kt
- kotlin-node/src/main/generated/node/inspector/HeapProfilerEvent.kt
- kotlin-node/src/main/generated/node/inspector/NodeRuntimeEvent.kt
- kotlin-node/src/main/generated/node/inspector/NodeTracingEvent.kt
- kotlin-node/src/main/generated/node/inspector/NodeWorkerEvent.kt
- kotlin-node/src/main/generated/node/inspector/ProfilerEvent.kt
- kotlin-node/src/main/generated/node/inspector/RuntimeEvent.kt
> Node. Separate `inspector` events [generated]

- kotlin-js/src/main/kotlin/kotlinx/js/Symbol.kt
> JS. Unique symbols

- kotlin-node/src/main/generated/node/events/EventEmitter.kt
> Node. Non-abstract `EventEmitter` [generated]

- kotlin-node/src/main/generated/node/ReadableStream.kt
- kotlin-node/src/main/generated/node/WritableStream.kt
- kotlin-node/src/main/generated/node/events/Abortable.kt
- kotlin-node/src/main/generated/node/fs/CopyOptions.kt
- kotlin-node/src/main/generated/node/fs/CopySyncOptions.kt
- kotlin-node/src/main/generated/node/process/Process.kt
- kotlin-node/src/main/generated/node/stream/Duplex.kt
- kotlin-node/src/main/generated/node/stream/DuplexOptions.kt
- kotlin-node/src/main/generated/node/stream/FinishedOptions.kt
- kotlin-node/src/main/generated/node/stream/LegacyStream.kt
- kotlin-node/src/main/generated/node/stream/PassThrough.kt
- kotlin-node/src/main/generated/node/stream/Pipe.kt
- kotlin-node/src/main/generated/node/stream/PipelineOptions.kt
- kotlin-node/src/main/generated/node/stream/Readable.kt
- kotlin-node/src/main/generated/node/stream/ReadableOptions.kt
- kotlin-node/src/main/generated/node/stream/Stream.kt
- kotlin-node/src/main/generated/node/stream/StreamOptions.kt
- kotlin-node/src/main/generated/node/stream/Transform.kt
- kotlin-node/src/main/generated/node/stream/TransformCallback.kt
- kotlin-node/src/main/generated/node/stream/TransformOptions.kt
- kotlin-node/src/main/generated/node/stream/Writable.kt
- kotlin-node/src/main/generated/node/stream/WritableOptions.kt
- kotlin-node/src/main/generated/node/stream/WritableStream.kt
> Node. `stream` [generated]

- kotlin-node/src/main/generated/node/net/AddressInfo.kt
- kotlin-node/src/main/generated/node/net/ConnectOpts.kt
- kotlin-node/src/main/generated/node/net/IPVersion.kt
- kotlin-node/src/main/generated/node/net/IpcNetConnectOpts.kt
- kotlin-node/src/main/generated/node/net/IpcSocketConnectOpts.kt
- kotlin-node/src/main/generated/node/net/ListenOptions.kt
- kotlin-node/src/main/generated/node/net/LookupFunction.kt
- kotlin-node/src/main/generated/node/net/OnReadOpts.kt
- kotlin-node/src/main/generated/node/net/ServerOpts.kt
- kotlin-node/src/main/generated/node/net/SocketAddressInitOptions.kt
- kotlin-node/src/main/generated/node/net/SocketConstructorOpts.kt
- kotlin-node/src/main/generated/node/net/SocketReadyState.kt
- kotlin-node/src/main/generated/node/net/TcpNetConnectOpts.kt
- kotlin-node/src/main/generated/node/net/TcpSocketConnectOpts.kt
> Node. `net` interfaces [generated]

- kotlin-node/src/main/generated/node/WritableStream.kt
- kotlin-node/src/main/generated/node/net/BlockList.kt
- kotlin-node/src/main/generated/node/net/LookupFunction.kt
- kotlin-node/src/main/generated/node/net/NetConnectOpts.kt
- kotlin-node/src/main/generated/node/net/Server.kt
- kotlin-node/src/main/generated/node/net/Socket.kt
- kotlin-node/src/main/generated/node/net/SocketAddress.kt
- kotlin-node/src/main/generated/node/net/SocketConnectOpts.kt
- kotlin-node/src/main/generated/node/net/connect.kt
- kotlin-node/src/main/generated/node/net/createConnection.kt
- kotlin-node/src/main/generated/node/net/createServer.kt
- kotlin-node/src/main/generated/node/net/isIP.kt
- kotlin-node/src/main/generated/node/net/isIPv4.kt
- kotlin-node/src/main/generated/node/net/isIPv6.kt
- kotlin-node/src/main/generated/node/process/Process.kt
- kotlin-node/src/main/generated/node/process/ProcessReport.kt
- kotlin-node/src/main/generated/node/stream/Duplex.kt
- kotlin-node/src/main/generated/node/stream/Readable.kt
- kotlin-node/src/main/generated/node/stream/Writable.kt
> Node. `net` classes & functions [generated]

- kotlin-node/src/main/generated/node/net/Socket.kt
- kotlin-node/src/main/generated/node/tty/Direction.kt
- kotlin-node/src/main/generated/node/tty/ReadStream.kt
- kotlin-node/src/main/generated/node/tty/WriteStream.kt
- kotlin-node/src/main/generated/node/tty/isatty.kt
> Node. `tty` [generated]

- kotlin-node/src/main/generated/node/ReadWriteStream.kt
- kotlin-node/src/main/generated/node/process/Socket.kt
> Node. Non-sealed `ReadWriteStream` [generated]

- kotlin-node/src/main/generated/node/RefCounted.kt
- kotlin-node/src/main/generated/node/process/WorkerListener.kt
- kotlin-node/src/main/generated/node/worker/BroadcastChannel.kt
- kotlin-node/src/main/generated/node/worker/IBroadcastChannel.kt
- kotlin-node/src/main/generated/node/worker/MessageChannel.kt
- kotlin-node/src/main/generated/node/worker/MessagePort.kt
- kotlin-node/src/main/generated/node/worker/ResourceLimits.kt
- kotlin-node/src/main/generated/node/worker/Serializable.kt
- kotlin-node/src/main/generated/node/worker/TransferListItem.kt
- kotlin-node/src/main/generated/node/worker/Worker.kt
- kotlin-node/src/main/generated/node/worker/WorkerOptions.kt
- kotlin-node/src/main/generated/node/worker/WorkerPerformance.kt
- kotlin-node/src/main/generated/node/worker/getEnvironmentData.kt
- kotlin-node/src/main/generated/node/worker/markAsUntransferable.kt
- kotlin-node/src/main/generated/node/worker/moveMessagePortToContext.kt
- kotlin-node/src/main/generated/node/worker/setEnvironmentData.kt
> Node. `worker_threads` [generated]

- kotlin-node/src/main/generated/node/net/Server.kt
- kotlin-node/src/main/generated/node/net/Socket.kt
- kotlin-node/src/main/generated/node/stream/Duplex.kt
- kotlin-node/src/main/generated/node/stream/PassThrough.kt
- kotlin-node/src/main/generated/node/stream/Readable.kt
- kotlin-node/src/main/generated/node/stream/Transform.kt
- kotlin-node/src/main/generated/node/stream/Writable.kt
> Node. Open members in open classes [generated]

- kotlin-node/src/main/generated/node/http/Agent.kt
- kotlin-node/src/main/generated/node/http/AgentOptions.kt
- kotlin-node/src/main/generated/node/http/ClientRequest.kt
- kotlin-node/src/main/generated/node/http/ClientRequestArgs.kt
- kotlin-node/src/main/generated/node/http/IncomingHttpHeaders.kt
- kotlin-node/src/main/generated/node/http/IncomingMessage.kt
- kotlin-node/src/main/generated/node/http/InformationEvent.kt
- kotlin-node/src/main/generated/node/http/OutgoingHttpHeaders.kt
- kotlin-node/src/main/generated/node/http/OutgoingMessage.kt
- kotlin-node/src/main/generated/node/http/RequestListener.kt
- kotlin-node/src/main/generated/node/http/RequestOptions.kt
- kotlin-node/src/main/generated/node/http/Server.kt
- kotlin-node/src/main/generated/node/http/ServerOptions.kt
- kotlin-node/src/main/generated/node/http/ServerResponse.kt
- kotlin-node/src/main/generated/node/http/createServer.kt
- kotlin-node/src/main/generated/node/http/get.kt
- kotlin-node/src/main/generated/node/http/request.kt
- kotlin-node/src/main/generated/node/net/TcpSocketConnectOpts.kt
> Node. `http` [generated]

- kotlin-node/src/main/generated/node/ReadableStream.kt
- kotlin-node/src/main/generated/node/stream/LegacyStream.kt
> Node. `pipe` method [generated]

- kotlin-node/src/main/generated/node/http/ClientRequestArgs.kt
> Node. Fix `ClientRequestArgs.createConnection` comment [generated]

- kotlin-react-query/src/main/kotlin/react/query/QueryKey.ext.kt
> React Query. Fix `QueryKey` factory

- kotlin-node/src/main/generated/node/os/CpuInfo.kt
- kotlin-node/src/main/generated/node/process/Process.kt
- kotlin-node/src/main/generated/node/process/ProcessConfig.kt
- kotlin-node/src/main/generated/node/stream/LegacyStream.kt
- kotlin-node/src/main/generated/node/url/urlToHttpOptions.kt
- kotlin-node/src/main/generated/node/vm/BaseOptions.kt
- kotlin-node/src/main/generated/node/vm/CompileFunctionOptions.kt
- kotlin-node/src/main/generated/node/vm/Context.kt
- kotlin-node/src/main/generated/node/vm/CreateContextOptions.kt
- kotlin-node/src/main/generated/node/vm/MeasureMemoryMode.kt
- kotlin-node/src/main/generated/node/vm/MeasureMemoryOptions.kt
- kotlin-node/src/main/generated/node/vm/MemoryMeasurement.kt
- kotlin-node/src/main/generated/node/vm/RunningScriptOptions.kt
- kotlin-node/src/main/generated/node/vm/Script.kt
- kotlin-node/src/main/generated/node/vm/ScriptOptions.kt
- kotlin-node/src/main/generated/node/vm/compileFunction.kt
- kotlin-node/src/main/generated/node/vm/createContext.kt
- kotlin-node/src/main/generated/node/vm/isContext.kt
- kotlin-node/src/main/generated/node/vm/measureMemory.kt
- kotlin-node/src/main/generated/node/vm/measureMemoryAsync.kt
- kotlin-node/src/main/generated/node/vm/runInContext.kt
- kotlin-node/src/main/generated/node/vm/runInNewContext.kt
- kotlin-node/src/main/generated/node/vm/runInThisContext.kt
- kotlin-node/src/main/generated/node/worker/moveMessagePortToContext.kt
> Node. `vm` [generated]

- kotlin-node/src/main/generated/node/process/WorkerListener.kt
- kotlin-node/src/main/generated/node/workerThreads/BroadcastChannel.kt
- kotlin-node/src/main/generated/node/workerThreads/IBroadcastChannel.kt
- kotlin-node/src/main/generated/node/workerThreads/MessageChannel.kt
- kotlin-node/src/main/generated/node/workerThreads/MessagePort.kt
- kotlin-node/src/main/generated/node/workerThreads/ResourceLimits.kt
- kotlin-node/src/main/generated/node/workerThreads/Serializable.kt
- kotlin-node/src/main/generated/node/workerThreads/TransferListItem.kt
- kotlin-node/src/main/generated/node/workerThreads/Worker.kt
- kotlin-node/src/main/generated/node/workerThreads/WorkerOptions.kt
- kotlin-node/src/main/generated/node/workerThreads/WorkerPerformance.kt
- kotlin-node/src/main/generated/node/workerThreads/getEnvironmentData.kt
- kotlin-node/src/main/generated/node/workerThreads/markAsUntransferable.kt
- kotlin-node/src/main/generated/node/workerThreads/moveMessagePortToContext.kt
- kotlin-node/src/main/generated/node/workerThreads/setEnvironmentData.kt
> Node. `worker_threads` - package name by style guide [generated]

- kotlin-node/src/main/generated/node/asyncHooks/AsyncHook.kt
- kotlin-node/src/main/generated/node/asyncHooks/AsyncLocalStorage.kt
- kotlin-node/src/main/generated/node/asyncHooks/AsyncResource.kt
- kotlin-node/src/main/generated/node/asyncHooks/AsyncResourceOptions.kt
- kotlin-node/src/main/generated/node/asyncHooks/HookCallbacks.kt
- kotlin-node/src/main/generated/node/asyncHooks/createHook.kt
- kotlin-node/src/main/generated/node/asyncHooks/executionAsyncId.kt
- kotlin-node/src/main/generated/node/asyncHooks/executionAsyncResource.kt
- kotlin-node/src/main/generated/node/asyncHooks/triggerAsyncId.kt
> Node. `async_hooks` [generated]

- kotlin-node/src/main/generated/node/asyncHooks/AsyncLocalStorage.kt
- kotlin-node/src/main/generated/node/asyncHooks/AsyncResource.kt
- kotlin-node/src/main/generated/node/buffer/Buffer.kt
- kotlin-node/src/main/generated/node/events/EventEmitter.kt
- kotlin-node/src/main/generated/node/events/IEventEmitter.kt
- kotlin-node/src/main/generated/node/http/Server.kt
- kotlin-node/src/main/generated/node/net/Server.kt
- kotlin-node/src/main/generated/node/net/Socket.kt
- kotlin-node/src/main/generated/node/path/PlatformPath.kt
- kotlin-node/src/main/generated/node/process/Process.kt
- kotlin-node/src/main/generated/node/stream/Readable.kt
- kotlin-node/src/main/generated/node/stream/Writable.kt
- kotlin-node/src/main/generated/node/tty/WriteStream.kt
- kotlin-node/src/main/generated/node/workerThreads/MessagePort.kt
- kotlin-node/src/main/generated/node/workerThreads/Worker.kt
> Node. Fix vararg conversion [generated]

- kotlin-node/src/main/generated/node/buffer/TranscodeEncoding.kt
- kotlin-node/src/main/generated/node/fs/Dir.kt
- kotlin-node/src/main/generated/node/fs/Dirent.kt
- kotlin-node/src/main/generated/node/fs/IStats.kt
- kotlin-node/src/main/generated/node/fs/NoParamCallback.kt
- kotlin-node/src/main/generated/node/fs/ReadStream.kt
- kotlin-node/src/main/generated/node/fs/Stats.kt
- kotlin-node/src/main/generated/node/fs/WriteStream.kt
> Node. `fs` classes [generated]

- kotlin-node/src/main/generated/node/PipeOptions.kt
- kotlin-node/src/main/generated/node/ReadableStream.kt
- kotlin-node/src/main/generated/node/stream/LegacyStream.kt
> Node. `PipeOptions` [generated]

- kotlin-node/src/main/generated/node/fs/Dir.kt
> Node. Fix `Dir` hierarchy [generated]

- kotlin-node/src/main/generated/node/childProcess/ExecException.kt
- kotlin-node/src/main/generated/node/childProcess/ProcessEnvOptions.kt
- kotlin-node/src/main/generated/node/childProcess/SpawnSyncReturns.kt
- kotlin-node/src/main/generated/node/childProcess/execFileSync.kt
- kotlin-node/src/main/generated/node/childProcess/execSync.kt
- kotlin-node/src/main/generated/node/fs/ReadStream.kt
- kotlin-node/src/main/generated/node/fs/WriteStream.kt
- kotlin-node/src/main/generated/node/fs/mkdtemp.kt
- kotlin-node/src/main/generated/node/fs/mkdtempAsync.kt
- kotlin-node/src/main/generated/node/fs/mkdtempSync.kt
- kotlin-node/src/main/generated/node/fs/readFile.kt
- kotlin-node/src/main/generated/node/fs/readFileAsync.kt
- kotlin-node/src/main/generated/node/fs/readlink.kt
- kotlin-node/src/main/generated/node/fs/readlinkAsync.kt
- kotlin-node/src/main/generated/node/fs/readlinkSync.kt
- kotlin-node/src/main/generated/node/fs/realpath.kt
- kotlin-node/src/main/generated/node/fs/realpathAsync.kt
- kotlin-node/src/main/generated/node/fs/realpathSync.kt
- kotlin-node/src/main/generated/node/process/Process.kt
- kotlin-node/src/main/generated/node/vm/CompileFunctionOptions.kt
- kotlin-node/src/main/generated/node/vm/Script.kt
- kotlin-node/src/main/generated/node/vm/ScriptOptions.kt
> Node. Function types [generated]

- kotlin-js/src/main/kotlin/kotlinx/js/globalThis.kt
> JS. `globalThis`

- kotlin-node/src/main/generated/node/fs/access.kt
- kotlin-node/src/main/generated/node/fs/appendFile.kt
- kotlin-node/src/main/generated/node/fs/copyFile.kt
- kotlin-node/src/main/generated/node/fs/cp.kt
- kotlin-node/src/main/generated/node/fs/lstat.kt
- kotlin-node/src/main/generated/node/fs/mkdir.kt
- kotlin-node/src/main/generated/node/fs/mkdtemp.kt
- kotlin-node/src/main/generated/node/fs/open.kt
- kotlin-node/src/main/generated/node/fs/opendir.kt
- kotlin-node/src/main/generated/node/fs/readFile.kt
- kotlin-node/src/main/generated/node/fs/readlink.kt
- kotlin-node/src/main/generated/node/fs/realpath.kt
- kotlin-node/src/main/generated/node/fs/rm.kt
- kotlin-node/src/main/generated/node/fs/rmdir.kt
- kotlin-node/src/main/generated/node/fs/stat.kt
- kotlin-node/src/main/generated/node/fs/symlink.kt
- kotlin-node/src/main/generated/node/fs/truncate.kt
- kotlin-node/src/main/generated/node/fs/writeFile.kt
- kotlin-node/src/main/generated/node/vm/measureMemory.kt
> Node. Additional `suspend` adapters [generated]

- kotlin-node/src/main/generated/node/stream/finished.kt
- kotlin-node/src/main/generated/node/stream/finishedAsync.kt
> Node. `stream/promises` [generated]

- kotlin-node/src/main/generated/node/crypto/Hash.kt
- kotlin-node/src/main/generated/node/crypto/Hmac.kt
> Node. `crypto` fix parent types [generated]

- kotlin-node/src/main/generated/node/crypto/ECDH.kt
> Node. Sealed `ECDH` [generated]

- kotlin-browser/src/main/generated/org/w3c/dom/events/Event.types.kt
> Browser. Update events [generated]

- kotlin-js/src/main/kotlin/kotlinx/js/ArrayBuffer.kt
- kotlin-js/src/main/kotlin/kotlinx/js/ArrayBufferView.kt
- kotlin-js/src/main/kotlin/kotlinx/js/DataView.kt
> JS. `DataView` alias

- kotlin-browser/src/main/generated/webgl/Aliases.kt
> WebGL. Aliases [generated]

- kotlin-browser/src/main/generated/webgl/BufferSource.kt
- kotlin-browser/src/main/generated/webgl/Lists.kt
- kotlin-browser/src/main/generated/webgl/WebGL2RenderingContext.kt
- kotlin-browser/src/main/generated/webgl/WebGL2RenderingContextBase.kt
- kotlin-browser/src/main/generated/webgl/WebGL2RenderingContextOverloads.kt
- kotlin-browser/src/main/generated/webgl/WebGLQuery.kt
- kotlin-browser/src/main/generated/webgl/WebGLRenderingContextOverloads.kt
- kotlin-browser/src/main/generated/webgl/WebGLSampler.kt
- kotlin-browser/src/main/generated/webgl/WebGLSync.kt
- kotlin-browser/src/main/generated/webgl/WebGLTransformFeedback.kt
- kotlin-browser/src/main/generated/webgl/WebGLVertexArrayObject.kt
> WebGL. Interfaces [generated]

- kotlin-browser/src/main/generated/webgl/Aliases.kt
- kotlin-browser/src/main/generated/webgl/WebGLExtension.kt
- kotlin-browser/src/main/generated/webgl/WebGLRenderingContextBase.kt
> WebGL. Strict extensions access [generated]

- kotlin-js/src/main/kotlin/kotlinx/js/SuspendableIterator.kt
Adapter for async structures like `AsyncIterator`
> JS. `SuspendableIterator`

- gradle.properties
- kotlin-mui/src/main/generated/muix/pickers/CalendarPicker.kt
- kotlin-mui/src/main/generated/muix/pickers/ClockPicker.kt
- kotlin-mui/src/main/generated/muix/pickers/DateField.kt
- kotlin-mui/src/main/generated/muix/pickers/MonthPicker.kt
- kotlin-mui/src/main/generated/muix/pickers/PickersDay.kt
- kotlin-mui/src/main/generated/muix/pickers/YearPicker.kt
> MUIX Pickers `5.0.0`

- kotlin-csstype/src/main/generated/csstype/AspectRatio.kt
- kotlin-csstype/src/main/generated/csstype/AutoType.kt
- kotlin-csstype/src/main/generated/csstype/GlobalsType.kt
- kotlin-csstype/src/main/generated/csstype/Number.kt
> CSSType. Restore `AspectRatio` [generated]

- kotlin-csstype/src/main/generated/csstype/GlobalsType.kt
- kotlin-csstype/src/main/generated/csstype/Integer.kt
- kotlin-csstype/src/main/generated/csstype/MathDepth.kt
> CSSType. `MathDepth` [generated]

- kotlin-csstype/src/main/generated/csstype/Properties.kt
- kotlin-csstype/src/main/generated/csstype/Reference.functions.kt
- kotlin-csstype/src/main/generated/csstype/Variable.kt
- kotlin-csstype/src/main/generated/csstype/VariableRecord.kt
> CSSType. Initial custom variable support [generated]

- kotlin-js/src/main/kotlin/kotlinx/JsArray.kt
> JS. `JsArray.from`

- kotlin-js/src/main/kotlin/kotlinx/js/structuredClone.kt
> JS. `structuredClone`

- kotlin-js/src/main/kotlin/kotlinx/js/URL.kt
- kotlin-js/src/main/kotlin/kotlinx/js/URLSearchParams.kt
> JS. Actual `URL` and `URLSearchParams`

- kotlin-browser/src/main/kotlin/org/w3c/dom/Worker.kt
- kotlin-js/src/main/kotlin/kotlinx/js/Request.kt
- kotlin-js/src/main/kotlin/kotlinx/js/fetch.kt
- kotlin-js/src/main/kotlin/kotlinx/js/fetchAsync.kt
- kotlin-node/src/main/generated/node/url/URL.alias.kt
- kotlin-node/src/main/generated/node/url/URLSearchParams.alias.kt
- kotlin-react-router-dom/src/main/generated/react/router/dom/SearchParamsInstance.kt
- kotlin-react-router-dom/src/main/generated/react/router/dom/createSearchParams.kt
- kotlin-react-router-dom/src/main/generated/react/router/dom/useSearchParams.kt
> JS. Use actualized `URL` and `URLSearchParams`

- kotlin-js/src/main/kotlin/kotlinx/js/JsIterator.ext.kt
> JS. `JsIterator` extensions

- kotlin-csstype/src/main/generated/csstype/TransformOrigin.kt
> CSSType. `TransformOrigin` factories [generated]

- kotlin-csstype/src/main/generated/csstype/BasicShape.kt
- kotlin-csstype/src/main/generated/csstype/GeometryBox.kt
> CSSType. `BasicShape` types [generated]

- kotlin-csstype/src/main/generated/csstype/Round.kt
- kotlin-csstype/src/main/generated/csstype/Shape.functions.kt
> CSSType. `inset` function [generated]

- kotlin-csstype/src/main/generated/csstype/BackgroundPosition.kt
- kotlin-csstype/src/main/generated/csstype/GeometryPosition.kt
- kotlin-csstype/src/main/generated/csstype/MaskPosition.kt
- kotlin-csstype/src/main/generated/csstype/ObjectPosition.kt
- kotlin-csstype/src/main/generated/csstype/OffsetAnchor.kt
- kotlin-csstype/src/main/generated/csstype/PerspectiveOrigin.kt
- kotlin-csstype/src/main/generated/csstype/TransformOrigin.kt
> CSSType. `GeometryPosition` [generated]

- kotlin-csstype/src/main/generated/csstype/GeometryPosition.kt
- kotlin-csstype/src/main/generated/csstype/LengthType.kt
- kotlin-csstype/src/main/generated/csstype/TransformOrigin.kt
> CSSType. Combine `TransformOrigin` factories [generated]

- kotlin-csstype/src/main/generated/csstype/Shape.functions.kt
> CSSType. `circle`, `ellipse`, `path` [generated]

- kotlin-browser/src/main/kotlin/org/w3c/dom/events/CustomEvent.kt
[Related discussion](https://kotlinlang.slack.com/archives/C0B8L3U69/p1663712044292399)
cc @aerialist7
> Browser. Strict `CustomEvent`

- kotlin-csstype/src/main/kotlin/csstype/Content.ext.kt
> CSSType. `Content` factories

- kotlin-js/src/main/kotlin/kotlinx/js/TypedArray.kt
> JS. `get` operator for typed arrays

- kotlin-browser/src/main/kotlin/org/w3c/dom/events/CustomEvent.kt
> JS. Add missed `CustomEvent.detail`

- gradle.properties
- kotlin-tanstack-query-core/src/main/generated/tanstack/query/core/queriesObserver.kt
- kotlin-tanstack-query-core/src/main/generated/tanstack/query/core/types.kt
- kotlin-tanstack-react-query/src/main/generated/tanstack/react/query/useSyncExternalStore.kt
> Tanstack Query `4.6.0`

- gradle.properties
- kotlin-tanstack-query-core/src/main/generated/tanstack/query/core/queryClient.kt
> Tanstack Query `4.7.1` [generated]

- gradle.properties
- kotlin-mui/src/main/generated/mui/system/createSpacing.ext.kt
- kotlin-popper/src/main/kotlin/popper/core/modifiers/Arrow.ext.kt
- kotlin-popper/src/main/kotlin/popper/core/modifiers/Offset.ext.kt
- kotlin-popper/src/main/kotlin/popper/core/modifiers/PreventOverflow.ext.kt
- kotlin-react-table/src/main/kotlin/react/table/PluginHook.kt
- kotlin-tanstack-table-core/src/main/generated/tanstack/table/core/AggregationFnOption.kt
- kotlin-tanstack-table-core/src/main/generated/tanstack/table/core/ColumnDefTemplate.kt
- kotlin-tanstack-table-core/src/main/generated/tanstack/table/core/Updater.kt
> Kotlin `1.7.20`

- gradle.properties
- kotlin-tanstack-query-core/src/main/generated/tanstack/query/core/types.kt
> Tanstack Query `4.8.0` [generated]

- kotlin-web/src/main/kotlin/web/abort/AbortController.kt
- kotlin-web/src/main/kotlin/web/abort/AbortSignal.kt
> Web. `AbortSignal` factories

- kotlin-browser/src/main/kotlin/web/timers/animationFrame.kt
> Timers. `requestAnimationFrame`

- kotlin-tanstack-query-core/src/main/generated/tanstack/query/core/types.kt
- kotlin-tanstack-react-query/src/main/generated/tanstack/react/query/useBaseQuery.kt
> React Query. Strict types [generated]

- gradle.properties
- kotlin-tanstack-query-core/src/main/generated/tanstack/query/core/mutationCache.kt
> Tanstack Query `4.12.0` [generated]

- gradle.properties
- kotlin-tanstack-query-core/src/main/generated/tanstack/query/core/mutation.kt
- kotlin-tanstack-query-core/src/main/generated/tanstack/query/core/query.kt
- kotlin-tanstack-query-core/src/main/generated/tanstack/query/core/types.kt
> Tanstack Query `4.13.0` [generated]

- kotlin-react-select/src/main/kotlin/react/select/IndicatorSeparator.kt
- kotlin-react-select/src/main/kotlin/react/select/IndicatorsContainerProps.kt
- kotlin-react-select/src/main/kotlin/react/select/Input.kt
- kotlin-react-select/src/main/kotlin/react/select/Placeholder.kt
- kotlin-react-select/src/main/kotlin/react/select/StylesConfig.kt
Added missing style attributes:
- dropdownIndicator
- indicatorsContainer
- indicatorSeparator
- input
- placeholder
> Added missing style attributes

- kotlin-react-dom/src/main/generated/react/dom/events/KeyboardEvent.kt
- kotlin-react-dom/src/main/generated/react/dom/events/ModifierKey.kt
- kotlin-react-dom/src/main/generated/react/dom/events/MouseEvent.kt
- kotlin-react-dom/src/main/generated/react/dom/events/TouchEvent.kt
> React Types `18.0.24` [generated]

- gradle.properties
- kotlin-tanstack-table-core/src/main/generated/tanstack/table/core/ColumnDefBase.kt
- kotlin-tanstack-table-core/src/main/generated/tanstack/table/core/CoreRow.kt
> Tanstack Table `8.5.18` [generated]

- kotlin-node/src/main/generated/node/buffer/INSPECT_MAX_BYTES.kt
- kotlin-node/src/main/generated/node/buffer/kMaxLength.const.kt
- kotlin-node/src/main/generated/node/buffer/kStringMaxLength.const.kt
- kotlin-node/src/main/generated/node/crypto/DEFAULT_ENCODING.kt
- kotlin-node/src/main/generated/node/crypto/fips.const.kt
- kotlin-node/src/main/generated/node/http/METHODS.kt
- kotlin-node/src/main/generated/node/http/maxHeaderSize.const.kt
- kotlin-node/src/main/generated/node/os/EOL.kt
- kotlin-node/src/main/generated/node/os/devNull.const.kt
- kotlin-node/src/main/generated/node/workerThreads/SHARE_ENV.kt
- kotlin-node/src/main/generated/node/workerThreads/isMainThread.const.kt
- kotlin-node/src/main/generated/node/workerThreads/parentPort.const.kt
- kotlin-node/src/main/generated/node/workerThreads/resourceLimits.const.kt
- kotlin-node/src/main/generated/node/workerThreads/threadId.const.kt
> Node. Constants [generated]

- kotlin-react-router/karakum.config.json
- kotlin-react-router/src/main/generated/react/router/CreateMemoryRouterOpts.kt
- kotlin-react-router/src/main/generated/react/router/Hash.kt
- kotlin-react-router/src/main/generated/react/router/Pathname.kt
- kotlin-react-router/src/main/generated/react/router/Search.kt
- kotlin-react-router/src/main/generated/react/router/createMemoryRouter.kt
- kotlin-react-router/src/main/generated/react/router/index.kt
- kotlin-remix-run-router/karakum.config.json
- kotlin-remix-run-router/src/main/generated/remix/run/router/index.kt
index files are converted for Router and Remix Routed packages
> React Router: index files are converted

- kotlin-react-router/karakum/plugins/convertCallableInterfaceDeclaration.js
- kotlin-react-router/src/jsMain/generated/react/router/NavigateFunction.kt
- kotlin-react-router/src/jsMain/kotlin/react/router/NavigateFunction.ext.kt
> React Router: `NavigateFunction` signatures are made callable

- kotlin-react-router-dom/src/jsMain/generated/react/router/dom/HistoryRouter.kt
- kotlin-react-router-dom/src/jsMain/generated/react/router/dom/usePrompt.kt
- kotlin-react-router-dom/src/jsMain/generated/react/router/dom/useScrollRestoration.kt
- kotlin-react-router/src/jsMain/generated/react/router/context.kt
- kotlin-react-router/src/jsMain/generated/react/router/enhanceManualRouteObjects.kt
- kotlin-react-router/src/jsMain/generated/react/router/useBlocker.kt
> React Router. Fix unsafe & unstable API usages

- gradle.properties
- kotlin-react-router/karakum.config.json
- kotlin-react-router/karakum/plugins/convertComponents.js
- kotlin-react-router/src/jsMain/generated/react/router/Navigate.kt
- kotlin-react-router/src/jsMain/generated/react/router/NavigateProps.kt
- kotlin-remix-run-router/src/jsMain/generated/remix/run/router/Router.kt
- kotlin-remix-run-router/src/jsMain/generated/remix/run/router/index.kt
Also component conversion is aligned between `react-router` and `react-router-dom`.
> React Router: bump router versions

- gradle.properties
> MUI Icons `5.11.11`

- kotlin-emotion/README.md
Hi, I worked up this Get Started guide for `kotlin-emotion`...feel free to make edits/comments, and please feel free to reach out if you have any questions. I'm happy to make any changes, and I hope this helps.
Sarah
> Get started guide for kotlin-emotion.

- gradle.properties
- kotlin-mui/src/jsMain/generated/mui/base/InputUnstyled.types.kt
- kotlin-mui/src/jsMain/generated/mui/base/MultiSelectUnstyled.types.kt
- kotlin-mui/src/jsMain/generated/mui/base/SelectUnstyled.types.kt
- kotlin-mui/src/jsMain/generated/mui/system/GlobalStyles.kt
- kotlin-mui/src/jsMain/generated/mui/system/ThemeProvider.kt
> MUI `5.10.1` [generated]

- buildSrc/src/main/kotlin/NpmDependencies.kt
> MUI. Use strict versions

- docs/guide/react.md
- kotlin-react/README.md
I did what I could based on my (admittedly quite shallow) understanding of the new DSL.
I followed the initial documentation from `kotlin-react-legacy`, and adapted to the new DSL.
Please feel free to correct anything in there!
> Add some documentation for the new React DSL

- gradle.properties
- kotlin-mui/src/jsMain/generated/mui/lab/TabList.kt
- kotlin-mui/src/jsMain/generated/mui/material/Card.kt
- kotlin-mui/src/jsMain/generated/mui/material/DialogContentText.kt
- kotlin-mui/src/jsMain/generated/mui/material/DialogTitle.kt
- kotlin-mui/src/jsMain/generated/mui/material/FormLabel.kt
- kotlin-mui/src/jsMain/generated/mui/material/Link.kt
- kotlin-mui/src/jsMain/generated/mui/material/Paper.kt
- kotlin-mui/src/jsMain/generated/mui/material/Typography.kt
- kotlin-mui/src/jsMain/generated/mui/system/Box.kt
- kotlin-mui/src/jsMain/generated/mui/system/StackProps.kt
Closes #2095 
Closes #2004
cc @arkivanov, @hofi99
> MUI. Material `5.14.1` & `Icons` `5.14.1` & `Lab` `5.0.0-alpha.137` [generated]

- docs/guide/react.md
> Docs. React. Remove `VFC` usages

- kotlin-mui/src/jsMain/generated/mui/material/Accordion.kt
- kotlin-mui/src/jsMain/generated/mui/material/AppBar.kt
> MUI. `PaperProps` inheritance for `AccordionProps` & `AppBarProps` [generated]

- kotlin-mui/src/jsMain/generated/mui/material/AccordionSummary.kt
- kotlin-mui/src/jsMain/generated/mui/material/BottomNavigationAction.kt
- kotlin-mui/src/jsMain/generated/mui/material/Button.kt
- kotlin-mui/src/jsMain/generated/mui/material/ButtonBase.kt
- kotlin-mui/src/jsMain/generated/mui/material/CardActionArea.kt
- kotlin-mui/src/jsMain/generated/mui/material/Fab.kt
- kotlin-mui/src/jsMain/generated/mui/material/IconButton.kt
- kotlin-mui/src/jsMain/generated/mui/material/List.kt
- kotlin-mui/src/jsMain/generated/mui/material/ListItem.kt
- kotlin-mui/src/jsMain/generated/mui/material/ListItemButton.kt
- kotlin-mui/src/jsMain/generated/mui/material/MenuItem.kt
- kotlin-mui/src/jsMain/generated/mui/material/MenuList.kt
- kotlin-mui/src/jsMain/generated/mui/material/StepButton.kt
- kotlin-mui/src/jsMain/generated/mui/material/Tab.kt
- kotlin-mui/src/jsMain/generated/mui/material/TableSortLabel.kt
- kotlin-mui/src/jsMain/generated/mui/material/ToggleButton.kt
> MUI. Improve `PropsWithComponent` inheritance [generated]

- kotlin-mui/src/jsMain/generated/mui/material/DialogContentText.kt
- kotlin-mui/src/jsMain/generated/mui/material/DialogTitle.kt
> MUI. Improve `TypographyProps` inheritance [generated]

- kotlin-mui/src/jsMain/generated/mui/base/ClickAwayListener.kt
- kotlin-mui/src/jsMain/generated/mui/base/FocusTrap.types.kt
- kotlin-mui/src/jsMain/generated/mui/base/FormControl.types.kt
- kotlin-mui/src/jsMain/generated/mui/base/Modal.types.kt
- kotlin-mui/src/jsMain/generated/mui/base/useInput.types.kt
- kotlin-mui/src/jsMain/generated/mui/material/Dialog.kt
- kotlin-mui/src/jsMain/generated/mui/material/Drawer.kt
- kotlin-mui/src/jsMain/generated/mui/material/Fade.kt
- kotlin-mui/src/jsMain/generated/mui/material/Grow.kt
- kotlin-mui/src/jsMain/generated/mui/material/Modal.kt
- kotlin-mui/src/jsMain/generated/mui/material/Popover.kt
- kotlin-mui/src/jsMain/generated/mui/material/Slide.kt
- kotlin-mui/src/jsMain/generated/mui/material/Slider.kt
- kotlin-mui/src/jsMain/generated/mui/material/Snackbar.kt
- kotlin-mui/src/jsMain/generated/mui/material/Tooltip.kt
- kotlin-mui/src/jsMain/generated/mui/material/Zoom.kt
> MUI. Improve `PropsWithChildren` inheritance [generated]

- kotlin-mui/src/jsMain/generated/mui/material/useScrollTrigger.kt
> MUI. Support `useScrollTrigger` hook [generated]

- kotlin-js/src/jsMain/kotlin/js/typedarrays/ByteArray.ext.kt
- kotlin-js/src/jsMain/kotlin/js/typedarrays/UByteArray.ext.kt
> Allow converting a Kotlin ByteArray to a JS TypedArray

- kotlin-mui-base/src/jsMain/generated/mui/base/Badge.kt
- kotlin-mui-base/src/jsMain/generated/mui/base/Button.kt
- kotlin-mui-base/src/jsMain/generated/mui/base/Dropdown.kt
- kotlin-mui-base/src/jsMain/generated/mui/base/FocusTrap.kt
- kotlin-mui-base/src/jsMain/generated/mui/base/FormControl.kt
- kotlin-mui-base/src/jsMain/generated/mui/base/Input.kt
- kotlin-mui-base/src/jsMain/generated/mui/base/Menu.kt
- kotlin-mui-base/src/jsMain/generated/mui/base/MenuButton.kt
- kotlin-mui-base/src/jsMain/generated/mui/base/MenuItem.kt
- kotlin-mui-base/src/jsMain/generated/mui/base/Modal.kt
- kotlin-mui-base/src/jsMain/generated/mui/base/NoSsr.kt
- kotlin-mui-base/src/jsMain/generated/mui/base/Option.kt
- kotlin-mui-base/src/jsMain/generated/mui/base/OptionGroup.kt
- kotlin-mui-base/src/jsMain/generated/mui/base/Popper.kt
- kotlin-mui-base/src/jsMain/generated/mui/base/Portal.kt
- kotlin-mui-base/src/jsMain/generated/mui/base/Select.kt
- kotlin-mui-base/src/jsMain/generated/mui/base/Slider.kt
- kotlin-mui-base/src/jsMain/generated/mui/base/Snackbar.kt
- kotlin-mui-base/src/jsMain/generated/mui/base/Switch.kt
- kotlin-mui-base/src/jsMain/generated/mui/base/Tab.kt
- kotlin-mui-base/src/jsMain/generated/mui/base/TabPanel.kt
- kotlin-mui-base/src/jsMain/generated/mui/base/TablePagination.kt
- kotlin-mui-base/src/jsMain/generated/mui/base/Tabs.kt
- kotlin-mui-base/src/jsMain/generated/mui/base/TabsList.kt
- kotlin-mui-base/src/jsMain/generated/mui/base/TextareaAutosize.kt
> MUI Base. Remove redundant `@JsName` [generated] 

- kotlin-mui-base/src/jsMain/generated/mui/base/ClickAwayListener.kt
> MUI Base. Fix import of `ClickAwayListener` component [generated]

- kotlin-mui-material/src/jsMain/generated/mui/material/Card.kt
Closes #2175
Closes #2169
Closes #2111
> MUI. `CardOwnProps` inherits `PaperOwnProps` [generated]

- FAQ.md
Some enhancements to the initially committed FAQ.md
> Adjust inital FAQ info

- kotlin-mui-base/src/jsMain/generated/mui/base/useSlider.types.kt
- kotlin-mui-material/src/jsMain/generated/mui/material/Slider.kt
@turansky, I will clean up other `dynamic`s later on with new PRs
> MUI. Get rid of `dynamic`s [generated]

- kotlin-js/src/jsMain/kotlin/js/objects/Object.kt
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/fromEntries
> JS. `Object.fromEntries`

- kotlin-react-router/karakum/annotations/annotateJsPlainObject.js
- kotlin-react-router/karakum/plugins/convertBooleanFunctions.js
- kotlin-react-router/src/jsMain/generated/react/router/DataRouteObject.kt
- kotlin-react-router/src/jsMain/generated/react/router/MapRoutePropertiesResult.kt
- kotlin-react-router/src/jsMain/generated/react/router/RouteObject.kt
> React Router. Sync generation with committed declarations

- kotlin-styled-next/build.gradle.kts
Updating Gradle config improves build performance, and prepares for future Gradle versions.
> update printBenchmarkResults to register task inputs

- buildSrc/src/main/kotlin/publish-conventions.gradle.kts
https://github.com/JetBrains/kotlin-wrappers/pull/2378#issuecomment-2284651947
> fix 'publishAllPublicationsToLocalBuildRepoRepository' typo

- .github/workflows/publish-github-pages.yml
Corrected the path for Dokka documentation artifacts.
> Fix artifact path for Dokka docs in GitHub Pages workflow

- gradle.properties
Add React 19 to peer dependency range
> React Select `5.9.0`

- kotlin-js-core/src/commonMain/kotlin/js/math/unsafe.kt
- kotlin-js-core/src/jsMain/kotlin/js/math/unsafe.kt
- kotlin-js-core/src/wasmJsMain/kotlin/js/math/unsafe.kt
JS Core. Add utility functions for various math operations. Not used yet.
> JS Core. Add unsafe math operations for JS and Wasm targets (#2449)
